package io.github.kdroidfilter.nucleusnativeaccess.plugin.codegen

import io.github.kdroidfilter.nucleusnativeaccess.plugin.ir.*

/**
 * Generates Rust `#[no_mangle] pub extern "C" fn` bridge code from a [KneModule].
 *
 * The generated bridges expose the Rust library's public API via the C ABI,
 * using the same symbol naming convention that [FfmProxyGenerator] expects.
 * This allows the JVM FFM proxies to call into Rust identically to Kotlin/Native.
 *
 * Object lifecycle uses `Box::into_raw` / `Box::from_raw` (equivalent to Kotlin/Native's StableRef).
 * Error propagation uses a thread-local `KNE_LAST_ERROR` (equivalent to `_kneLastError`).
 * String I/O uses the output-buffer pattern (equivalent to Kotlin/Native's `CPointer<ByteVar>`).
 */
class RustBridgeGenerator {

    fun generate(module: KneModule): String {
        val sb = StringBuilder()
        val prefix = module.libName

        sb.appendPreamble()
        sb.appendErrorInfra(prefix)

        for (cls in module.classes) {
            sb.appendClass(cls, prefix)
        }

        for (enum in module.enums) {
            sb.appendEnum(enum, prefix)
        }

        for (fn in module.functions) {
            sb.appendTopLevelFunction(fn, prefix)
        }

        return sb.toString()
    }

    // --- Preamble ---

    private fun StringBuilder.appendPreamble() {
        appendLine("// Auto-generated by NNA (Nucleus Native Access) — do not edit.")
        appendLine()
        appendLine("use std::cell::RefCell;")
        appendLine("use std::ffi::CStr;")
        appendLine("use std::os::raw::c_char;")
        appendLine("use std::panic::catch_unwind;")
        appendLine()
    }

    // --- Error infrastructure ---

    private fun StringBuilder.appendErrorInfra(prefix: String) {
        appendLine("thread_local! {")
        appendLine("    static KNE_LAST_ERROR: RefCell<Option<String>> = RefCell::new(None);")
        appendLine("}")
        appendLine()
        appendLine("fn kne_set_error(msg: String) {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = Some(msg));")
        appendLine("}")
        appendLine()
        appendLine("fn kne_set_panic_error(err: Box<dyn std::any::Any + Send>) {")
        appendLine("    let msg = if let Some(s) = err.downcast_ref::<&str>() {")
        appendLine("        s.to_string()")
        appendLine("    } else if let Some(s) = err.downcast_ref::<String>() {")
        appendLine("        s.clone()")
        appendLine("    } else {")
        appendLine("        \"Unknown panic\".to_string()")
        appendLine("    };")
        appendLine("    kne_set_error(msg);")
        appendLine("}")
        appendLine()
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${prefix}_kne_hasError() -> i32 {")
        appendLine("    KNE_LAST_ERROR.with(|e| if e.borrow().is_some() { 1 } else { 0 })")
        appendLine("}")
        appendLine()
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${prefix}_kne_getLastError(out_buf: *mut u8, out_buf_len: i32) -> i32 {")
        appendLine("    KNE_LAST_ERROR.with(|e| {")
        appendLine("        let mut err = e.borrow_mut();")
        appendLine("        if let Some(ref msg) = *err {")
        appendLine("            let bytes = msg.as_bytes();")
        appendLine("            let len = bytes.len() as i32;")
        appendLine("            if len < out_buf_len {")
        appendLine("                unsafe {")
        appendLine("                    std::ptr::copy_nonoverlapping(bytes.as_ptr(), out_buf, bytes.len());")
        appendLine("                    *out_buf.add(bytes.len()) = 0;")
        appendLine("                }")
        appendLine("            }")
        appendLine("            *err = None;")
        appendLine("            len + 1")
        appendLine("        } else {")
        appendLine("            0")
        appendLine("        }")
        appendLine("    })")
        appendLine("}")
        appendLine()
    }

    // --- Class bridges ---

    private fun StringBuilder.appendClass(cls: KneClass, prefix: String) {
        val className = cls.simpleName
        val sym = "${prefix}_${className}"

        // Constructor
        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn ${sym}_new(")
        append(cls.constructor.params.joinToString(", ") { p -> "${p.name}: ${rustCType(p.type)}" })
        appendLine(") -> i64 {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
        appendLine("    match catch_unwind(|| {")
        // Convert params
        for (p in cls.constructor.params) {
            appendParamConversion(p)
        }
        append("        let obj = $className::new(")
        append(cls.constructor.params.joinToString(", ") { p -> convertedCallArg(p) })
        appendLine(");")
        appendLine("        Box::into_raw(Box::new(obj)) as i64")
        appendLine("    }) {")
        appendLine("        Ok(h) => h,")
        appendLine("        Err(e) => { kne_set_panic_error(e); 0 }")
        appendLine("    }")
        appendLine("}")
        appendLine()

        // Dispose
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${sym}_dispose(handle: i64) {")
        appendLine("    if handle != 0 {")
        appendLine("        unsafe { drop(Box::from_raw(handle as *mut $className)); }")
        appendLine("    }")
        appendLine("}")
        appendLine()

        // Methods
        for (method in cls.methods) {
            appendMethod(method, cls, prefix)
        }

        // Properties
        for (prop in cls.properties) {
            appendPropertyBridges(prop, cls, prefix)
        }
    }

    private fun StringBuilder.appendMethod(fn: KneFunction, cls: KneClass, prefix: String) {
        val sym = "${prefix}_${cls.simpleName}_${fn.name}"
        val needsBufOutput = needsOutputBuffer(fn.returnType)

        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn $sym(handle: i64")
        for (p in fn.params) {
            if (p.type == KneType.BYTE_ARRAY || p.type is KneType.LIST) {
                append(", ${p.name}_ptr: ${slicePointerType(p.type)}, ${p.name}_len: i32")
            } else if (p.type is KneType.DATA_CLASS) {
                // Expand data class fields as individual C params
                val dc = p.type as KneType.DATA_CLASS
                for (field in dc.fields) {
                    append(", ${p.name}_${field.name}: ${rustCType(field.type)}")
                }
            } else {
                append(", ${p.name}: ${rustCType(p.type)}")
            }
        }
        if (needsBufOutput) {
            append(", out_buf: *mut u8, out_buf_len: i32")
        }
        // Data class return: add per-field out-params
        if (fn.returnType is KneType.DATA_CLASS) {
            val dc = fn.returnType as KneType.DATA_CLASS
            for (field in dc.fields) {
                when (field.type) {
                    KneType.STRING -> {
                        append(", out_${field.name}: *mut u8, out_${field.name}_len: i32")
                    }
                    else -> {
                        append(", out_${field.name}: *mut ${rustCType(field.type)}")
                    }
                }
            }
        }
        appendLine(") -> ${rustCReturnType(fn.returnType)} {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
        appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
        if (fn.isMutating) {
            appendLine("        let obj = unsafe { &mut *(handle as *mut ${cls.simpleName}) };")
        } else {
            appendLine("        let obj = unsafe { &*(handle as *const ${cls.simpleName}) };")
        }
        for (p in fn.params) {
            appendParamConversion(p)
        }
        val callArgs = fn.params.joinToString(", ") { p -> convertedParamName(p) }
        appendReturnHandling("obj.${fn.name}($callArgs)", fn.returnType)
        appendLine("    })) {")
        if (fn.returnType is KneType.DATA_CLASS) {
            appendLine("        Ok(_) => {},")
        } else {
            appendLine("        Ok(v) => v,")
        }
        appendLine("        Err(e) => { kne_set_panic_error(e); ${defaultReturnValue(fn.returnType)} }")
        appendLine("    }")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendPropertyBridges(prop: KneProperty, cls: KneClass, prefix: String) {
        val className = cls.simpleName
        val sym = "${prefix}_${className}"
        val needsBuf = needsOutputBuffer(prop.type)

        // Getter bridge
        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn ${sym}_get_${prop.name}(handle: i64")
        if (needsBuf) append(", out_buf: *mut u8, out_buf_len: i32")
        appendLine(") -> ${rustCReturnType(prop.type)} {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
        appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
        appendLine("        let obj = unsafe { &*(handle as *const $className) };")
        appendReturnHandling("obj.get_${prop.name}()", prop.type)
        appendLine("    })) {")
        appendLine("        Ok(v) => v,")
        appendLine("        Err(e) => { kne_set_panic_error(e); ${defaultReturnValue(prop.type)} }")
        appendLine("    }")
        appendLine("}")
        appendLine()

        // Setter bridge (only if mutable)
        if (prop.mutable) {
            val param = KneParam("value", prop.type)
            appendLine("#[no_mangle]")
            append("pub extern \"C\" fn ${sym}_set_${prop.name}(handle: i64")
            append(", value: ${rustCType(prop.type)}")
            appendLine(") {")
            appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
            appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
            appendLine("        let obj = unsafe { &mut *(handle as *mut $className) };")
            appendParamConversion(param)
            val callArg = convertedParamName(param)
            appendLine("        obj.set_${prop.name}($callArg);")
            appendLine("    })) {")
            appendLine("        Ok(_) => {},")
            appendLine("        Err(e) => { kne_set_panic_error(e); }")
            appendLine("    }")
            appendLine("}")
            appendLine()
        }
    }

    private fun needsOutputBuffer(type: KneType): Boolean = when (type) {
        KneType.STRING, KneType.BYTE_ARRAY -> true
        is KneType.LIST -> true
        is KneType.NULLABLE -> (type as KneType.NULLABLE).inner == KneType.STRING
        is KneType.DATA_CLASS -> false // Data class returns use per-field out-params, not a single buffer
        else -> false
    }

    private fun StringBuilder.appendReturnHandling(expr: String, returnType: KneType) {
        when (returnType) {
            KneType.STRING -> {
                appendLine("        let result = $expr;")
                appendStringOutput("result")
            }
            KneType.BYTE_ARRAY -> {
                appendLine("        let result = $expr;")
                appendLine("        let len = result.len() as i32;")
                appendLine("        if len <= out_buf_len {")
                appendLine("            unsafe { std::ptr::copy_nonoverlapping(result.as_ptr(), out_buf, result.len()); }")
                appendLine("        }")
                appendLine("        len")
            }
            KneType.UNIT -> {
                appendLine("        $expr;")
            }
            is KneType.DATA_CLASS -> {
                appendLine("        let result = $expr;")
                val dc = returnType as KneType.DATA_CLASS
                for (field in dc.fields) {
                    when (field.type) {
                        KneType.STRING -> {
                            appendLine("        let _f_bytes = result.${field.name}.as_bytes();")
                            appendLine("        if (_f_bytes.len() as i32) < out_${field.name}_len {")
                            appendLine("            unsafe { std::ptr::copy_nonoverlapping(_f_bytes.as_ptr(), out_${field.name}, _f_bytes.len()); }")
                            appendLine("            unsafe { *out_${field.name}.add(_f_bytes.len()) = 0; }")
                            appendLine("        }")
                        }
                        else -> {
                            appendLine("        unsafe { *out_${field.name} = result.${field.name}${rustReturnConversion(field.type)}; }")
                        }
                    }
                }
            }
            is KneType.OBJECT -> {
                appendLine("        let result = $expr;")
                appendLine("        Box::into_raw(Box::new(result)) as i64")
            }
            is KneType.NULLABLE -> {
                appendLine("        let result = $expr;")
                appendNullableReturn(returnType)
            }
            is KneType.LIST -> {
                appendLine("        let result = $expr;")
                appendLine("        let len = result.len() as i32;")
                appendLine("        if len <= out_buf_len {")
                appendLine("            for (i, v) in result.iter().enumerate() {")
                appendLine("                unsafe { *(out_buf as *mut i32).add(i) = *v as i32; }")
                appendLine("            }")
                appendLine("        }")
                appendLine("        len")
            }
            else -> {
                appendLine("        $expr${rustReturnConversion(returnType)}")
            }
        }
    }

    // --- Enum bridges ---

    private fun StringBuilder.appendEnum(enum: KneEnum, prefix: String) {
        val sym = "${prefix}_${enum.simpleName}"

        // name(ordinal) -> string
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${sym}_name(ordinal: i32, out_buf: *mut u8, out_buf_len: i32) -> i32 {")
        appendLine("    let name = match ordinal {")
        for ((i, entry) in enum.entries.withIndex()) {
            appendLine("        $i => \"$entry\",")
        }
        appendLine("        _ => \"Unknown\",")
        appendLine("    };")
        appendLine("    let bytes = name.as_bytes();")
        appendLine("    let len = bytes.len() as i32;")
        appendLine("    if len < out_buf_len {")
        appendLine("        unsafe {")
        appendLine("            std::ptr::copy_nonoverlapping(bytes.as_ptr(), out_buf, bytes.len());")
        appendLine("            *out_buf.add(bytes.len()) = 0;")
        appendLine("        }")
        appendLine("    }")
        appendLine("    len + 1")
        appendLine("}")
        appendLine()

        // count() -> i32
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${sym}_count() -> i32 {")
        appendLine("    ${enum.entries.size}")
        appendLine("}")
        appendLine()
    }

    // --- Top-level functions ---

    private fun StringBuilder.appendTopLevelFunction(fn: KneFunction, prefix: String) {
        val sym = "${prefix}_${fn.name}"
        val needsBuf = needsOutputBuffer(fn.returnType)

        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn $sym(")
        val allParams = mutableListOf<String>()
        for (p in fn.params) {
            if (p.type == KneType.BYTE_ARRAY || p.type is KneType.LIST) {
                allParams.add("${p.name}_ptr: ${slicePointerType(p.type)}")
                allParams.add("${p.name}_len: i32")
            } else if (p.type is KneType.DATA_CLASS) {
                val dc = p.type as KneType.DATA_CLASS
                for (field in dc.fields) {
                    allParams.add("${p.name}_${field.name}: ${rustCType(field.type)}")
                }
            } else {
                allParams.add("${p.name}: ${rustCType(p.type)}")
            }
        }
        if (needsBuf) {
            allParams.add("out_buf: *mut u8")
            allParams.add("out_buf_len: i32")
        }
        // Data class return: add per-field out-params
        if (fn.returnType is KneType.DATA_CLASS) {
            val dc = fn.returnType as KneType.DATA_CLASS
            for (field in dc.fields) {
                when (field.type) {
                    KneType.STRING -> {
                        allParams.add("out_${field.name}: *mut u8")
                        allParams.add("out_${field.name}_len: i32")
                    }
                    else -> {
                        allParams.add("out_${field.name}: *mut ${rustCType(field.type)}")
                    }
                }
            }
        }
        append(allParams.joinToString(", "))
        appendLine(") -> ${rustCReturnType(fn.returnType)} {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
        appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
        for (p in fn.params) {
            appendParamConversion(p)
        }
        val callArgs = fn.params.joinToString(", ") { p -> convertedParamName(p) }
        appendReturnHandling("${fn.name}($callArgs)", fn.returnType)
        appendLine("    })) {")
        if (fn.returnType is KneType.DATA_CLASS) {
            appendLine("        Ok(_) => {},")
        } else {
            appendLine("        Ok(v) => v,")
        }
        appendLine("        Err(e) => { kne_set_panic_error(e); ${defaultReturnValue(fn.returnType)} }")
        appendLine("    }")
        appendLine("}")
        appendLine()
    }

    // --- Helpers ---

    private fun StringBuilder.appendParamConversion(p: KneParam) {
        when (p.type) {
            KneType.STRING -> {
                appendLine("        let ${p.name}_conv = unsafe { CStr::from_ptr(${p.name}) }.to_str().unwrap_or(\"\");")
                appendLine("        let ${p.name}_str: String = ${p.name}_conv.to_string();")
            }
            KneType.BOOLEAN -> {
                appendLine("        let ${p.name}_conv = ${p.name} != 0;")
            }
            is KneType.ENUM -> {
                val enumName = (p.type as KneType.ENUM).simpleName
                appendLine("        let ${p.name}_conv: $enumName = unsafe { std::mem::transmute(${p.name} as u8) };")
            }
            is KneType.OBJECT -> {
                val typeName = (p.type as KneType.OBJECT).simpleName
                appendLine("        let ${p.name}_conv = unsafe { &*(${p.name} as *const $typeName) };")
            }
            is KneType.DATA_CLASS -> {
                val dc = p.type as KneType.DATA_CLASS
                // Convert individual string fields from C strings
                for (field in dc.fields) {
                    if (field.type == KneType.STRING) {
                        appendLine("        let ${p.name}_${field.name}_conv = unsafe { CStr::from_ptr(${p.name}_${field.name}) }.to_str().unwrap_or(\"\");")
                    }
                }
                // Reconstruct the struct from expanded fields
                val fieldAssignments = dc.fields.joinToString(", ") { field ->
                    when (field.type) {
                        KneType.STRING -> "${field.name}: ${p.name}_${field.name}_conv.to_string()"
                        KneType.BOOLEAN -> "${field.name}: ${p.name}_${field.name} != 0"
                        else -> "${field.name}: ${p.name}_${field.name}"
                    }
                }
                appendLine("        let ${p.name}_dc = ${dc.simpleName} { $fieldAssignments };")
            }
            KneType.BYTE_ARRAY -> {
                appendLine("        let ${p.name}_slice = unsafe { std::slice::from_raw_parts(${p.name}_ptr, ${p.name}_len as usize) };")
            }
            is KneType.LIST -> {
                appendLine("        let ${p.name}_slice = unsafe { std::slice::from_raw_parts(${p.name}_ptr, ${p.name}_len as usize) };")
            }
            else -> {} // Primitives need no conversion
        }
    }

    /** Param name for method calls — uses isBorrowed to decide &str vs String, &T vs T. */
    private fun convertedParamName(p: KneParam): String = when (p.type) {
        KneType.STRING -> if (p.isBorrowed) "${p.name}_conv" else "${p.name}_str.clone()"
        KneType.BOOLEAN -> "${p.name}_conv"
        is KneType.ENUM -> "&${p.name}_conv"
        is KneType.OBJECT -> if (p.isBorrowed) {
            // Borrowed object: pass as &T
            "${p.name}_conv"
        } else {
            // Owned object — for now still pass as borrow
            "${p.name}_conv"
        }
        is KneType.DATA_CLASS -> if (p.isBorrowed) "&${p.name}_dc" else "${p.name}_dc"
        KneType.BYTE_ARRAY -> "${p.name}_slice"
        is KneType.LIST -> "${p.name}_slice"
        else -> p.name
    }

    /** Param name for constructor calls — String passes owned String. */
    private fun convertedCallArg(p: KneParam): String = when (p.type) {
        KneType.STRING -> "${p.name}_str"
        else -> convertedParamName(p)
    }

    private fun StringBuilder.appendNullableReturn(nullableType: KneType.NULLABLE) {
        when (nullableType.inner) {
            KneType.INT -> {
                appendLine("        match result { Some(v) => v as i64, None => i64::MIN }")
            }
            KneType.LONG -> {
                appendLine("        match result { Some(v) => v, None => i64::MIN }")
            }
            KneType.DOUBLE -> {
                appendLine("        match result { Some(v) => i64::from_ne_bytes(v.to_ne_bytes()), None => i64::MIN }")
            }
            KneType.BOOLEAN -> {
                // Return i32: -1 = null, 0 = false, 1 = true
                appendLine("        match result { Some(true) => 1, Some(false) => 0, None => -1 }")
            }
            KneType.STRING -> {
                // Returns i32 via buffer pattern; -1 means null
                appendLine("        match result {")
                appendLine("            Some(ref s) => {")
                appendLine("                let bytes = s.as_bytes();")
                appendLine("                let len = bytes.len() as i32;")
                appendLine("                if len < out_buf_len {")
                appendLine("                    unsafe {")
                appendLine("                        std::ptr::copy_nonoverlapping(bytes.as_ptr(), out_buf, bytes.len());")
                appendLine("                        *out_buf.add(bytes.len()) = 0;")
                appendLine("                    }")
                appendLine("                }")
                appendLine("                len + 1")
                appendLine("            }")
                appendLine("            None => -1")
                appendLine("        }")
            }
            is KneType.OBJECT -> {
                appendLine("        match result { Some(v) => Box::into_raw(Box::new(v)) as i64, None => 0i64 }")
            }
            else -> {
                appendLine("        match result { Some(v) => v as i64, None => i64::MIN }")
            }
        }
    }

    private fun StringBuilder.appendStringOutput(expr: String) {
        appendLine("        let bytes = $expr.as_bytes();")
        appendLine("        let len = bytes.len() as i32;")
        appendLine("        if len < out_buf_len {")
        appendLine("            unsafe {")
        appendLine("                std::ptr::copy_nonoverlapping(bytes.as_ptr(), out_buf, bytes.len());")
        appendLine("                *out_buf.add(bytes.len()) = 0;")
        appendLine("            }")
        appendLine("        }")
        appendLine("        len + 1")
    }

    /** C ABI pointer type for a slice parameter. */
    private fun slicePointerType(type: KneType): String = when (type) {
        KneType.BYTE_ARRAY -> "*const u8"
        is KneType.LIST -> when (type.elementType) {
            KneType.INT -> "*const i32"
            KneType.LONG -> "*const i64"
            KneType.DOUBLE -> "*const f64"
            KneType.FLOAT -> "*const f32"
            else -> "*const i64"
        }
        else -> "*const u8"
    }

    /** C ABI type for a parameter. */
    private fun rustCType(type: KneType): String = when (type) {
        KneType.INT -> "i32"
        KneType.LONG -> "i64"
        KneType.DOUBLE -> "f64"
        KneType.FLOAT -> "f32"
        KneType.BOOLEAN -> "i32" // 0/1
        KneType.BYTE -> "i8"
        KneType.SHORT -> "i16"
        KneType.STRING -> "*const c_char"
        KneType.UNIT -> "()"
        is KneType.OBJECT -> "i64" // opaque handle
        is KneType.INTERFACE -> "i64"
        is KneType.ENUM -> "i32" // ordinal
        is KneType.NULLABLE -> "i64" // widened or sentinel
        is KneType.LIST -> "i64" // pointer handle
        is KneType.SET -> "i64"
        is KneType.MAP -> "i64"
        KneType.BYTE_ARRAY -> "i64"
        is KneType.DATA_CLASS -> "i64"
        is KneType.FUNCTION -> "i64"
        is KneType.FLOW -> "()"
    }

    /** C ABI return type. Buffer-pattern types return i32 (byte/element count). */
    private fun rustCReturnType(type: KneType): String = when (type) {
        KneType.STRING -> "i32"
        KneType.BYTE_ARRAY -> "i32"
        KneType.UNIT -> "()"
        is KneType.LIST -> "i32"
        is KneType.DATA_CLASS -> "()" // Data class returns use per-field out-params
        is KneType.NULLABLE -> when ((type).inner) {
            KneType.INT, KneType.LONG, KneType.DOUBLE -> "i64"
            KneType.BOOLEAN -> "i32"
            KneType.STRING -> "i32"
            is KneType.OBJECT -> "i64"
            else -> "i64"
        }
        else -> rustCType(type)
    }

    /** Conversion suffix for return expressions (e.g., " as i32" for Boolean). */
    private fun rustReturnConversion(type: KneType): String = when (type) {
        KneType.BOOLEAN -> " as i32"
        is KneType.ENUM -> " as i32"
        else -> ""
    }

    /** Default value returned on panic/error. */
    private fun defaultReturnValue(type: KneType): String = when (type) {
        KneType.INT, KneType.BYTE, KneType.SHORT -> "0"
        KneType.LONG -> "0i64"
        KneType.DOUBLE -> "0.0f64"
        KneType.FLOAT -> "0.0f32"
        KneType.BOOLEAN -> "0"
        KneType.STRING -> "0" // byte count = 0
        KneType.UNIT -> "()"
        is KneType.DATA_CLASS -> "()" // out-params pattern, void return
        is KneType.OBJECT, is KneType.INTERFACE -> "0i64"
        is KneType.ENUM -> "0"
        is KneType.NULLABLE -> when ((type).inner) {
            KneType.BOOLEAN, KneType.STRING -> "0i32"
            else -> "0i64"
        }
        else -> "0"
    }
}
