package io.github.kdroidfilter.nucleusnativeaccess.plugin.codegen

import io.github.kdroidfilter.nucleusnativeaccess.plugin.ir.*

/**
 * Generates Rust `#[no_mangle] pub extern "C" fn` bridge code from a [KneModule].
 *
 * The generated bridges expose the Rust library's public API via the C ABI,
 * using the same symbol naming convention that [FfmProxyGenerator] expects.
 * This allows the JVM FFM proxies to call into Rust identically to Kotlin/Native.
 *
 * Object lifecycle uses `Box::into_raw` / `Box::from_raw` (equivalent to Kotlin/Native's StableRef).
 * Error propagation uses a thread-local `KNE_LAST_ERROR` (equivalent to `_kneLastError`).
 * String I/O uses the output-buffer pattern (equivalent to Kotlin/Native's `CPointer<ByteVar>`).
 */
class RustBridgeGenerator {

    fun generate(module: KneModule): String {
        val sb = StringBuilder()
        val prefix = module.libName

        sb.appendPreamble()
        sb.appendErrorInfra(prefix)

        // Check if any class or top-level function uses suspend or flow
        val hasSuspend = module.classes.any { c -> c.methods.any { it.isSuspend } } ||
            module.functions.any { it.isSuspend }
        val hasFlow = module.classes.any { c -> c.methods.any { it.returnType is KneType.FLOW } } ||
            module.functions.any { it.returnType is KneType.FLOW }
        if (hasSuspend || hasFlow) {
            sb.appendSuspendHelpers(prefix)
        }

        for (cls in module.classes) {
            sb.appendClass(cls, prefix)
        }

        for (enum in module.enums) {
            sb.appendEnum(enum, prefix)
        }

        for (sealed in module.sealedEnums) {
            sb.appendSealedEnum(sealed, prefix)
        }

        for (fn in module.functions) {
            sb.appendTopLevelFunction(fn, prefix)
        }

        return sb.toString()
    }

    // --- Preamble ---

    private fun StringBuilder.appendPreamble() {
        appendLine("// Auto-generated by NNA (Nucleus Native Access) — do not edit.")
        appendLine()
        appendLine("use std::cell::RefCell;")
        appendLine("use std::ffi::CStr;")
        appendLine("use std::os::raw::c_char;")
        appendLine("use std::panic::catch_unwind;")
        appendLine()
    }

    // --- Error infrastructure ---

    private fun StringBuilder.appendErrorInfra(prefix: String) {
        appendLine("thread_local! {")
        appendLine("    static KNE_LAST_ERROR: RefCell<Option<String>> = RefCell::new(None);")
        appendLine("}")
        appendLine()
        appendLine("fn kne_set_error(msg: String) {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = Some(msg));")
        appendLine("}")
        appendLine()
        appendLine("fn kne_set_panic_error(err: Box<dyn std::any::Any + Send>) {")
        appendLine("    let msg = if let Some(s) = err.downcast_ref::<&str>() {")
        appendLine("        s.to_string()")
        appendLine("    } else if let Some(s) = err.downcast_ref::<String>() {")
        appendLine("        s.clone()")
        appendLine("    } else {")
        appendLine("        \"Unknown panic\".to_string()")
        appendLine("    };")
        appendLine("    kne_set_error(msg);")
        appendLine("}")
        appendLine()
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${prefix}_kne_hasError() -> i32 {")
        appendLine("    KNE_LAST_ERROR.with(|e| if e.borrow().is_some() { 1 } else { 0 })")
        appendLine("}")
        appendLine()
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${prefix}_kne_getLastError(out_buf: *mut u8, out_buf_len: i32) -> i32 {")
        appendLine("    KNE_LAST_ERROR.with(|e| {")
        appendLine("        let mut err = e.borrow_mut();")
        appendLine("        if let Some(ref msg) = *err {")
        appendLine("            let bytes = msg.as_bytes();")
        appendLine("            let len = bytes.len() as i32;")
        appendLine("            if len < out_buf_len {")
        appendLine("                unsafe {")
        appendLine("                    std::ptr::copy_nonoverlapping(bytes.as_ptr(), out_buf, bytes.len());")
        appendLine("                    *out_buf.add(bytes.len()) = 0;")
        appendLine("                }")
        appendLine("            }")
        appendLine("            *err = None;")
        appendLine("            len + 1")
        appendLine("        } else {")
        appendLine("            0")
        appendLine("        }")
        appendLine("    })")
        appendLine("}")
        appendLine()
    }

    // --- Class bridges ---

    private fun StringBuilder.appendClass(cls: KneClass, prefix: String) {
        val className = cls.simpleName
        val rustTypeName = cls.rustTypeName
        val sym = "${prefix}_${className}"

        if (cls.constructor.kind != KneConstructorKind.NONE) {
            appendConstructor(cls, prefix)
        }

        // Dispose
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${sym}_dispose(handle: i64) {")
        if (cls.isOpaque) {
            appendLine("    let _ = handle;")
        } else {
            appendLine("    if handle != 0 {")
            appendLine("        unsafe { drop(Box::from_raw(handle as *mut $rustTypeName)); }")
            appendLine("    }")
        }
        appendLine("}")
        appendLine()

        // Methods
        for (method in cls.methods) {
            appendMethod(method, cls, prefix)
        }

        for (method in cls.companionMethods) {
            appendCompanionMethod(method, cls, prefix)
        }

        // Properties
        for (prop in cls.properties) {
            appendPropertyBridges(prop, cls, prefix)
        }
    }

    private fun StringBuilder.appendConstructor(cls: KneClass, prefix: String) {
        val className = cls.simpleName
        val sym = "${prefix}_${className}"
        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn ${sym}_new(")
        append(cls.constructor.params.joinToString(", ") { p -> "${p.name}: ${rustCType(p.type)}" })
        appendLine(") -> i64 {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
        appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
        for (p in cls.constructor.params) {
            appendParamConversion(p)
        }
        val ctorExpr = when (cls.constructor.kind) {
            KneConstructorKind.FUNCTION -> {
                val args = cls.constructor.params.joinToString(", ") { p -> convertedCallArg(p) }
                "$className::new($args)"
            }
            KneConstructorKind.STRUCT_LITERAL -> {
                val args = cls.constructor.params.joinToString(", ") { p -> "${p.name}: ${convertedCallArg(p)}" }
                "$className { $args }"
            }
            KneConstructorKind.NONE -> error("unreachable")
        }
        if (cls.constructor.canFail) {
            appendFallibleReturnHandling(ctorExpr, KneType.OBJECT(cls.fqName, className))
        } else {
            appendValueReturnHandling(ctorExpr, KneType.OBJECT(cls.fqName, className))
        }
        appendLine("    })) {")
        appendLine("        Ok(v) => v,")
        appendLine("        Err(e) => { kne_set_panic_error(e); 0i64 }")
        appendLine("    }")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendMethod(fn: KneFunction, cls: KneClass, prefix: String) {
        if (fn.returnType is KneType.FLOW) {
            appendFlowMethod(fn, cls, prefix)
            return
        }
        if (fn.isSuspend) {
            appendSuspendMethod(fn, cls, prefix)
            return
        }
        if (!isSupportedReturnType(fn.returnType)) return
        val sym = "${prefix}_${cls.simpleName}_${fn.name}"
        val needsBufOutput = needsOutputBuffer(fn.returnType)

        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn $sym(handle: i64")
        for (p in fn.params) {
            val ndc = nullableDataClass(p.type)
            if (p.type == KneType.BYTE_ARRAY || p.type is KneType.LIST) {
                append(", ${p.name}_ptr: ${slicePointerType(p.type)}, ${p.name}_len: i32")
            } else if (ndc != null) {
                appendNullableDataClassSignatureParams(p.name, ndc)
            } else if (p.type is KneType.DATA_CLASS) {
                // Expand data class fields as individual C params
                val dc = p.type as KneType.DATA_CLASS
                for (field in dc.fields) {
                    append(", ${p.name}_${field.name}: ${rustCType(field.type)}")
                }
            } else {
                append(", ${p.name}: ${rustCType(p.type)}")
            }
        }
        if (needsBufOutput) {
            append(", out_buf: *mut u8, out_buf_len: i32")
        }
        // Data class return (or nullable data class): add per-field out-params
        val returnDc = extractReturnDataClass(fn.returnType)
        if (returnDc != null) {
            for (field in returnDc.fields) {
                when (field.type) {
                    KneType.STRING -> {
                        append(", out_${field.name}: *mut u8, out_${field.name}_len: i32")
                    }
                    else -> {
                        append(", out_${field.name}: *mut ${rustCType(field.type)}")
                    }
                }
            }
        }
        // MAP return: dual key/value buffers + max count
        extractMapReturnType(fn.returnType)?.let { mapType ->
            append(", out_keys: ${mapOutPointerType(mapType.keyType)}")
            if (mapType.keyType == KneType.STRING) append(", out_keys_len: i32")
            append(", out_values: ${mapOutPointerType(mapType.valueType)}")
            if (mapType.valueType == KneType.STRING) append(", out_values_len: i32")
            append(", out_max_len: i32")
        }
        appendLine(") -> ${rustCReturnType(fn.returnType)} {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
        appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
        appendReceiverBinding(fn, cls.rustTypeName)
        for (p in fn.params) {
            appendParamConversion(p)
        }
        val callArgs = fn.params.joinToString(", ") { p -> convertedParamName(p) }
        val expr = wrapCallForSafety("obj.${fn.name}($callArgs)", fn.isUnsafe)
        if (fn.canFail) {
            appendFallibleReturnHandling(expr, fn.returnType, fn.returnRustType, fn.returnsBorrowed)
        } else {
            appendValueReturnHandling(expr, fn.returnType, fn.returnRustType, fn.returnsBorrowed)
        }
        appendLine("    })) {")
        if (fn.returnType is KneType.DATA_CLASS) {
            appendLine("        Ok(_) => {},")
        } else {
            appendLine("        Ok(v) => v,")
        }
        appendLine("        Err(e) => { kne_set_panic_error(e); ${defaultReturnValue(fn.returnType)} }")
        appendLine("    }")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendCompanionMethod(fn: KneFunction, cls: KneClass, prefix: String) {
        if (!isSupportedReturnType(fn.returnType)) return
        val sym = "${prefix}_${cls.simpleName}_companion_${fn.name}"
        val needsBuf = needsOutputBuffer(fn.returnType)

        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn $sym(")
        val allParams = mutableListOf<String>()
        for (p in fn.params) {
            val ndc = nullableDataClass(p.type)
            if (p.type == KneType.BYTE_ARRAY || p.type is KneType.LIST) {
                allParams.add("${p.name}_ptr: ${slicePointerType(p.type)}")
                allParams.add("${p.name}_len: i32")
            } else if (ndc != null) {
                allParams.addAll(nullableDataClassSignatureParamList(p.name, ndc))
            } else if (p.type is KneType.DATA_CLASS) {
                val dc = p.type as KneType.DATA_CLASS
                for (field in dc.fields) {
                    allParams.add("${p.name}_${field.name}: ${rustCType(field.type)}")
                }
            } else {
                allParams.add("${p.name}: ${rustCType(p.type)}")
            }
        }
        if (needsBuf) {
            allParams.add("out_buf: *mut u8")
            allParams.add("out_buf_len: i32")
        }
        val companionReturnDc = extractReturnDataClass(fn.returnType)
        if (companionReturnDc != null) {
            for (field in companionReturnDc.fields) {
                when (field.type) {
                    KneType.STRING -> {
                        allParams.add("out_${field.name}: *mut u8")
                        allParams.add("out_${field.name}_len: i32")
                    }
                    else -> allParams.add("out_${field.name}: *mut ${rustCType(field.type)}")
                }
            }
        }
        // MAP return: dual key/value buffers + max count
        extractMapReturnType(fn.returnType)?.let { mapType ->
            allParams.add("out_keys: ${mapOutPointerType(mapType.keyType)}")
            if (mapType.keyType == KneType.STRING) allParams.add("out_keys_len: i32")
            allParams.add("out_values: ${mapOutPointerType(mapType.valueType)}")
            if (mapType.valueType == KneType.STRING) allParams.add("out_values_len: i32")
            allParams.add("out_max_len: i32")
        }
        append(allParams.joinToString(", "))
        appendLine(") -> ${rustCReturnType(fn.returnType)} {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
        appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
        for (p in fn.params) {
            appendParamConversion(p)
        }
        val callArgs = fn.params.joinToString(", ") { p -> convertedParamName(p) }
        val expr = wrapCallForSafety("${cls.simpleName}::${fn.name}($callArgs)", fn.isUnsafe)
        if (fn.canFail) {
            appendFallibleReturnHandling(expr, fn.returnType, fn.returnRustType, fn.returnsBorrowed)
        } else {
            appendValueReturnHandling(expr, fn.returnType, fn.returnRustType, fn.returnsBorrowed)
        }
        appendLine("    })) {")
        if (fn.returnType is KneType.DATA_CLASS) {
            appendLine("        Ok(_) => {},")
        } else {
            appendLine("        Ok(v) => v,")
        }
        appendLine("        Err(e) => { kne_set_panic_error(e); ${defaultReturnValue(fn.returnType)} }")
        appendLine("    }")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendPropertyBridges(prop: KneProperty, cls: KneClass, prefix: String) {
        if (!isSupportedReturnType(prop.type)) return
        val className = cls.simpleName
        val sym = "${prefix}_${className}"

        if (prop.type is KneType.MAP) {
            appendMapPropertyGetter(prop, cls, sym)
            return
        }

        val needsBuf = needsOutputBuffer(prop.type)

        // Getter bridge
        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn ${sym}_get_${prop.name}(handle: i64")
        if (needsBuf) append(", out_buf: *mut u8, out_buf_len: i32")
        appendLine(") -> ${rustCReturnType(prop.type)} {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
        appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
        appendLine("        let obj = unsafe { &*(handle as *const ${cls.rustTypeName}) };")
        appendValueReturnHandling("obj.get_${prop.name}()", prop.type)
        appendLine("    })) {")
        appendLine("        Ok(v) => v,")
        appendLine("        Err(e) => { kne_set_panic_error(e); ${defaultReturnValue(prop.type)} }")
        appendLine("    }")
        appendLine("}")
        appendLine()

        // Setter bridge (only if mutable)
        if (prop.mutable) {
            val param = KneParam("value", prop.type)
            appendLine("#[no_mangle]")
            append("pub extern \"C\" fn ${sym}_set_${prop.name}(handle: i64")
            append(", value: ${rustCType(prop.type)}")
            appendLine(") {")
            appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
            appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
            appendLine("        let obj = unsafe { &mut *(handle as *mut ${cls.rustTypeName}) };")
            appendParamConversion(param)
            val callArg = convertedParamName(param)
            appendLine("        obj.set_${prop.name}($callArg);")
            appendLine("    })) {")
            appendLine("        Ok(_) => {},")
            appendLine("        Err(e) => { kne_set_panic_error(e); }")
            appendLine("    }")
            appendLine("}")
            appendLine()
        }
    }

    private fun StringBuilder.appendMapPropertyGetter(prop: KneProperty, cls: KneClass, sym: String) {
        val mapType = prop.type as KneType.MAP
        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn ${sym}_get_${prop.name}(handle: i64")
        append(", out_keys: ${mapOutPointerType(mapType.keyType)}")
        if (mapType.keyType == KneType.STRING) append(", out_keys_len: i32")
        append(", out_values: ${mapOutPointerType(mapType.valueType)}")
        if (mapType.valueType == KneType.STRING) append(", out_values_len: i32")
        appendLine(", out_max_len: i32) -> i32 {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
        appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
        appendLine("        let obj = unsafe { &*(handle as *const ${cls.rustTypeName}) };")
        appendMapReturnFromBinding("obj.get_${prop.name}()", mapType, "        ")
        appendLine("    })) {")
        appendLine("        Ok(v) => v,")
        appendLine("        Err(e) => { kne_set_panic_error(e); 0 }")
        appendLine("    }")
        appendLine("}")
        appendLine()
    }

    /** Extract a DATA_CLASS from a return type (handles both direct and nullable). */
    private fun extractReturnDataClass(type: KneType): KneType.DATA_CLASS? = when (type) {
        is KneType.DATA_CLASS -> type
        is KneType.NULLABLE -> type.inner as? KneType.DATA_CLASS
        else -> null
    }

    /** Check if the return type is fully supported by the Rust bridge generator. */
    private fun isSupportedReturnType(type: KneType): Boolean = when (type) {
        is KneType.MAP -> true
        is KneType.SET -> true
        is KneType.NULLABLE -> when (type.inner) {
            is KneType.DATA_CLASS -> true
            is KneType.LIST, is KneType.SET, is KneType.MAP -> true
            else -> true
        }
        else -> true
    }

    /** Extract MAP type from a direct MAP or Nullable<MAP> return. */
    private fun extractMapReturnType(type: KneType): KneType.MAP? = when (type) {
        is KneType.MAP -> type
        is KneType.NULLABLE -> type.inner as? KneType.MAP
        else -> null
    }

    /** Returns the Rust pointer type for a MAP out-parameter buffer. */
    private fun mapOutPointerType(elemType: KneType): String = when (elemType) {
        KneType.STRING -> "*mut u8"
        KneType.INT, KneType.BOOLEAN -> "*mut i32"
        KneType.LONG -> "*mut i64"
        KneType.DOUBLE -> "*mut f64"
        KneType.FLOAT -> "*mut f32"
        KneType.SHORT -> "*mut i16"
        KneType.BYTE -> "*mut i8"
        is KneType.ENUM -> "*mut i32"
        is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM -> "*mut i64"
        else -> "*mut i64"
    }

    private fun needsOutputBuffer(type: KneType): Boolean = when (type) {
        KneType.STRING, KneType.BYTE_ARRAY -> true
        is KneType.LIST, is KneType.SET -> true
        is KneType.NULLABLE -> when (type.inner) {
            KneType.STRING -> true
            is KneType.LIST, is KneType.SET -> true
            else -> false
        }
        is KneType.DATA_CLASS -> false // Data class returns use per-field out-params, not a single buffer
        is KneType.MAP -> false // MAP uses dual buffers, handled separately
        else -> false
    }

    private fun StringBuilder.appendReturnHandling(expr: String, returnType: KneType) {
        appendValueReturnHandling(expr, returnType)
    }

    private fun StringBuilder.appendFallibleReturnHandling(
        expr: String,
        returnType: KneType,
        returnRustType: String? = null,
        returnsBorrowed: Boolean = false,
    ) {
        appendLine("        match $expr {")
        appendLine("            Ok(result) => {")
        appendValueReturnFromBinding("result", returnType, returnRustType, returnsBorrowed, "            ")
        appendLine("            }")
        appendLine("            Err(e) => {")
        appendLine("                kne_set_error(e.to_string());")
        appendLine("                ${defaultReturnValue(returnType)}")
        appendLine("            }")
        appendLine("        }")
    }

    private fun StringBuilder.appendValueReturnHandling(
        expr: String,
        returnType: KneType,
        returnRustType: String? = null,
        returnsBorrowed: Boolean = false,
    ) {
        appendLine("        let result = $expr;")
        appendValueReturnFromBinding("result", returnType, returnRustType, returnsBorrowed, "        ")
    }

    private fun StringBuilder.appendValueReturnFromBinding(
        binding: String,
        returnType: KneType,
        returnRustType: String? = null,
        returnsBorrowed: Boolean = false,
        indent: String = "        ",
    ) {
        when (returnType) {
            KneType.STRING -> {
                appendStringOutput(binding, indent, returnRustType)
            }
            KneType.BYTE_ARRAY -> {
                appendLine("${indent}let len = $binding.len() as i32;")
                appendLine("${indent}if len <= out_buf_len {")
                appendLine("${indent}    unsafe { std::ptr::copy_nonoverlapping($binding.as_ptr(), out_buf, $binding.len()); }")
                appendLine("${indent}}")
                appendLine("${indent}len")
            }
            KneType.UNIT -> {
                appendLine("${indent}()")
            }
            is KneType.DATA_CLASS -> {
                val dc = returnType
                for (field in dc.fields) {
                    when (field.type) {
                        KneType.STRING -> {
                            appendLine("${indent}let _f_bytes = $binding.${field.name}.as_bytes();")
                            appendLine("${indent}if (_f_bytes.len() as i32) < out_${field.name}_len {")
                            appendLine("${indent}    unsafe { std::ptr::copy_nonoverlapping(_f_bytes.as_ptr(), out_${field.name}, _f_bytes.len()); }")
                            appendLine("${indent}    unsafe { *out_${field.name}.add(_f_bytes.len()) = 0; }")
                            appendLine("${indent}}")
                        }
                        else -> {
                            appendLine("${indent}unsafe { *out_${field.name} = ${rustReturnExpr("$binding.${field.name}", field.type, field.rustType)}; }")
                        }
                    }
                }
                appendLine("${indent}()")
            }
            is KneType.OBJECT -> {
                if (returnsBorrowed) {
                    appendLine("${indent}$binding as *const _ as i64")
                } else {
                    appendLine("${indent}Box::into_raw(Box::new($binding)) as i64")
                }
            }
            is KneType.INTERFACE -> {
                if (returnsBorrowed) {
                    appendLine("${indent}$binding as *const _ as i64")
                } else {
                    appendLine("${indent}Box::into_raw(Box::new($binding)) as i64")
                }
            }
            is KneType.SEALED_ENUM -> {
                if (returnsBorrowed) {
                    appendLine("${indent}$binding as *const _ as i64")
                } else {
                    appendLine("${indent}Box::into_raw(Box::new($binding)) as i64")
                }
            }
            is KneType.NULLABLE -> {
                appendNullableReturn(returnType, binding, returnsBorrowed, returnRustType, indent)
            }
            is KneType.LIST -> {
                appendListReturnFromBinding(binding, returnType, indent, returnRustType)
            }
            is KneType.SET -> {
                appendListReturnFromBinding(binding, KneType.LIST(returnType.elementType), indent, returnRustType)
            }
            is KneType.MAP -> {
                appendMapReturnFromBinding(binding, returnType, indent, returnRustType)
            }
            else -> { appendLine("${indent}${rustReturnExpr(binding, returnType, returnRustType, returnsBorrowed)}")
            }
        }
    }

    // --- Enum bridges ---

    private fun StringBuilder.appendListReturnFromBinding(binding: String, listType: KneType.LIST, indent: String, returnRustType: String? = null) {
        val elemType = listType.elementType
        when (elemType) {
            is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM -> {
                // Return borrowed pointers - ownership remains with parent
                appendLine("${indent}let len = $binding.len() as i32;")
                appendLine("${indent}if len <= out_buf_len {")
                appendLine("${indent}    for (i, v) in $binding.iter().enumerate() {")
                appendLine("${indent}        unsafe { *(out_buf as *mut i64).add(i) = v as *const _ as i64; }")
                appendLine("${indent}    }")
                appendLine("${indent}}")
                appendLine("${indent}len")
            }
            KneType.STRING -> {
                // Serialize strings as null-terminated, concatenated in buffer
                val needsLossy = isPathLikeRustType(returnRustType)
                appendLine("${indent}let len = $binding.len() as i32;")
                appendLine("${indent}let mut offset = 0usize;")
                appendLine("${indent}for s in $binding.iter() {")
                if (needsLossy) {
                    appendLine("${indent}    let _lossy = s.to_string_lossy();")
                    appendLine("${indent}    let bytes = _lossy.as_bytes();")
                } else {
                    appendLine("${indent}    let bytes = s.as_bytes();")
                }
                appendLine("${indent}    if offset + bytes.len() + 1 > out_buf_len as usize {")
                appendLine("${indent}        break;")
                appendLine("${indent}    }")
                appendLine("${indent}    unsafe {")
                appendLine("${indent}        std::ptr::copy_nonoverlapping(bytes.as_ptr(), out_buf.add(offset), bytes.len());")
                appendLine("${indent}        *out_buf.add(offset + bytes.len()) = 0;")
                appendLine("${indent}    }")
                appendLine("${indent}    offset += bytes.len() + 1;")
                appendLine("${indent}}")
                appendLine("${indent}len")
            }
            KneType.LONG -> {
                appendLine("${indent}let len = $binding.len() as i32;")
                appendLine("${indent}if len <= out_buf_len {")
                appendLine("${indent}    for (i, v) in $binding.iter().enumerate() {")
                appendLine("${indent}        unsafe { *(out_buf as *mut i64).add(i) = *v as i64; }")
                appendLine("${indent}    }")
                appendLine("${indent}}")
                appendLine("${indent}len")
            }
            KneType.DOUBLE -> {
                appendLine("${indent}let len = $binding.len() as i32;")
                appendLine("${indent}if len <= out_buf_len {")
                appendLine("${indent}    for (i, v) in $binding.iter().enumerate() {")
                appendLine("${indent}        unsafe { *(out_buf as *mut f64).add(i) = *v as f64; }")
                appendLine("${indent}    }")
                appendLine("${indent}}")
                appendLine("${indent}len")
            }
            KneType.FLOAT -> {
                appendLine("${indent}let len = $binding.len() as i32;")
                appendLine("${indent}if len <= out_buf_len {")
                appendLine("${indent}    for (i, v) in $binding.iter().enumerate() {")
                appendLine("${indent}        unsafe { *(out_buf as *mut f32).add(i) = *v as f32; }")
                appendLine("${indent}    }")
                appendLine("${indent}}")
                appendLine("${indent}len")
            }
            KneType.BOOLEAN -> {
                appendLine("${indent}let len = $binding.len() as i32;")
                appendLine("${indent}if len <= out_buf_len {")
                appendLine("${indent}    for (i, v) in $binding.iter().enumerate() {")
                appendLine("${indent}        unsafe { *(out_buf as *mut i32).add(i) = if *v { 1 } else { 0 }; }")
                appendLine("${indent}    }")
                appendLine("${indent}}")
                appendLine("${indent}len")
            }
            is KneType.ENUM -> {
                appendLine("${indent}let len = $binding.len() as i32;")
                appendLine("${indent}if len <= out_buf_len {")
                appendLine("${indent}    for (i, v) in $binding.iter().enumerate() {")
                appendLine("${indent}        unsafe { *(out_buf as *mut i32).add(i) = v.clone() as i32; }")
                appendLine("${indent}    }")
                appendLine("${indent}}")
                appendLine("${indent}len")
            }
            else -> {
                // Default: treat as i32 primitives
                appendLine("${indent}let len = $binding.len() as i32;")
                appendLine("${indent}if len <= out_buf_len {")
                appendLine("${indent}    for (i, v) in $binding.iter().enumerate() {")
                appendLine("${indent}        unsafe { *(out_buf as *mut i32).add(i) = *v as i32; }")
                appendLine("${indent}    }")
                appendLine("${indent}}")
                appendLine("${indent}len")
            }
        }
    }

    // ── MAP return bridge ────────────────────────────────────────────────────

    private fun StringBuilder.appendMapReturnFromBinding(
        binding: String, mapType: KneType.MAP, indent: String, returnRustType: String? = null
    ) {
        val keyType = mapType.keyType
        val valueType = mapType.valueType
        appendLine("${indent}let len = $binding.len() as i32;")
        appendLine("${indent}if len <= out_max_len {")
        // Write keys
        appendMapElementWrite("$binding.keys()", keyType, "out_keys", indent + "    ", returnRustType)
        // Write values
        appendMapElementWrite("$binding.values()", valueType, "out_values", indent + "    ", returnRustType)
        appendLine("${indent}}")
        appendLine("${indent}len")
    }

    private fun StringBuilder.appendMapElementWrite(
        iterExpr: String, elemType: KneType, bufName: String,
        indent: String, returnRustType: String? = null,
    ) {
        when (elemType) {
            KneType.STRING -> {
                val needsLossy = isPathLikeRustType(returnRustType)
                appendLine("${indent}let mut offset = 0usize;")
                appendLine("${indent}for s in $iterExpr {")
                if (needsLossy) {
                    appendLine("${indent}    let _lossy = s.to_string_lossy();")
                    appendLine("${indent}    let bytes = _lossy.as_bytes();")
                } else {
                    appendLine("${indent}    let bytes = s.as_bytes();")
                }
                appendLine("${indent}    unsafe {")
                appendLine("${indent}        std::ptr::copy_nonoverlapping(bytes.as_ptr(), $bufName.add(offset), bytes.len());")
                appendLine("${indent}        *$bufName.add(offset + bytes.len()) = 0;")
                appendLine("${indent}    }")
                appendLine("${indent}    offset += bytes.len() + 1;")
                appendLine("${indent}}")
            }
            KneType.LONG -> {
                appendLine("${indent}for (i, v) in $iterExpr.enumerate() {")
                appendLine("${indent}    unsafe { *($bufName as *mut i64).add(i) = *v as i64; }")
                appendLine("${indent}}")
            }
            KneType.INT -> {
                appendLine("${indent}for (i, v) in $iterExpr.enumerate() {")
                appendLine("${indent}    unsafe { *($bufName as *mut i32).add(i) = *v as i32; }")
                appendLine("${indent}}")
            }
            KneType.DOUBLE -> {
                appendLine("${indent}for (i, v) in $iterExpr.enumerate() {")
                appendLine("${indent}    unsafe { *($bufName as *mut f64).add(i) = *v as f64; }")
                appendLine("${indent}}")
            }
            KneType.FLOAT -> {
                appendLine("${indent}for (i, v) in $iterExpr.enumerate() {")
                appendLine("${indent}    unsafe { *($bufName as *mut f32).add(i) = *v as f32; }")
                appendLine("${indent}}")
            }
            KneType.BOOLEAN -> {
                appendLine("${indent}for (i, v) in $iterExpr.enumerate() {")
                appendLine("${indent}    unsafe { *($bufName as *mut i32).add(i) = if *v { 1 } else { 0 }; }")
                appendLine("${indent}}")
            }
            is KneType.ENUM -> {
                appendLine("${indent}for (i, v) in $iterExpr.enumerate() {")
                appendLine("${indent}    unsafe { *($bufName as *mut i32).add(i) = v.clone() as i32; }")
                appendLine("${indent}}")
            }
            is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM -> {
                appendLine("${indent}for (i, v) in $iterExpr.enumerate() {")
                appendLine("${indent}    unsafe { *($bufName as *mut i64).add(i) = v as *const _ as i64; }")
                appendLine("${indent}}")
            }
            else -> {
                appendLine("${indent}for (i, v) in $iterExpr.enumerate() {")
                appendLine("${indent}    unsafe { *($bufName as *mut i32).add(i) = *v as i32; }")
                appendLine("${indent}}")
            }
        }
    }

    // ── Enum bridges ─────────────────────────────────────────────────────────

    private fun StringBuilder.appendEnum(enum: KneEnum, prefix: String) {
        val sym = "${prefix}_${enum.simpleName}"

        // name(ordinal) -> string
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${sym}_name(ordinal: i32, out_buf: *mut u8, out_buf_len: i32) -> i32 {")
        appendLine("    let name = match ordinal {")
        for ((i, entry) in enum.entries.withIndex()) {
            appendLine("        $i => \"$entry\",")
        }
        appendLine("        _ => \"Unknown\",")
        appendLine("    };")
        appendLine("    let bytes = name.as_bytes();")
        appendLine("    let len = bytes.len() as i32;")
        appendLine("    if len < out_buf_len {")
        appendLine("        unsafe {")
        appendLine("            std::ptr::copy_nonoverlapping(bytes.as_ptr(), out_buf, bytes.len());")
        appendLine("            *out_buf.add(bytes.len()) = 0;")
        appendLine("        }")
        appendLine("    }")
        appendLine("    len + 1")
        appendLine("}")
        appendLine()

        // count() -> i32
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${sym}_count() -> i32 {")
        appendLine("    ${enum.entries.size}")
        appendLine("}")
        appendLine()
    }

    // --- Sealed enums (tagged enums with data variants) ---

    private fun StringBuilder.appendSealedEnum(sealed: KneSealedEnum, prefix: String) {
        val sym = "${prefix}_${sealed.simpleName}"
        val rustName = sealed.simpleName

        // dispose(handle)
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${sym}_dispose(handle: i64) {")
        appendLine("    if handle != 0 {")
        appendLine("        unsafe { drop(Box::from_raw(handle as *mut $rustName)); }")
        appendLine("    }")
        appendLine("}")
        appendLine()

        // tag(handle) -> i32
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${sym}_tag(handle: i64) -> i32 {")
        appendLine("    let obj = unsafe { &*(handle as *const $rustName) };")
        appendLine("    match obj {")
        for ((i, variant) in sealed.variants.withIndex()) {
            val pattern = when {
                variant.fields.isEmpty() -> "$rustName::${variant.name}"
                variant.isTuple -> "$rustName::${variant.name}(..)"
                else -> "$rustName::${variant.name} { .. }"
            }
            appendLine("        $pattern => $i,")
        }
        appendLine("        _ => -1,")
        appendLine("    }")
        appendLine("}")
        appendLine()

        // Per-variant constructors and field getters
        for ((i, variant) in sealed.variants.withIndex()) {
            appendSealedVariantConstructor(sym, rustName, variant, prefix)
            appendSealedVariantFieldGetters(sym, rustName, variant, prefix)
        }
    }

    private fun StringBuilder.appendSealedVariantConstructor(
        sym: String, rustName: String, variant: KneSealedVariant, prefix: String
    ) {
        // Skip variants with unsupported field types
        if (variant.fields.any { it.type is KneType.LIST || it.type is KneType.SET || it.type is KneType.MAP }) return
        val fnName = "${sym}_new_${variant.name}"
        appendLine("#[no_mangle]")
        val params = variant.fields.joinToString(", ") { f ->
            when (f.type) {
                KneType.BYTE_ARRAY, is KneType.LIST -> "${f.name}_ptr: ${slicePointerType(f.type)}, ${f.name}_len: i32"
                else -> "${f.name}: ${rustCType(f.type)}"
            }
        }
        appendLine("pub extern \"C\" fn $fnName($params) -> i64 {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
        appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
        for (f in variant.fields) {
            appendParamConversion(f)
        }
        if (variant.fields.isEmpty()) {
            appendLine("        Box::into_raw(Box::new($rustName::${variant.name})) as i64")
        } else if (variant.isTuple) {
            val args = variant.fields.joinToString(", ") { convertedCallArg(it) }
            appendLine("        Box::into_raw(Box::new($rustName::${variant.name}($args))) as i64")
        } else {
            val fieldArgs = variant.fields.joinToString(", ") { f ->
                "${f.name}: ${convertedCallArg(f)}"
            }
            appendLine("        Box::into_raw(Box::new($rustName::${variant.name} { $fieldArgs })) as i64")
        }
        appendLine("    })) {")
        appendLine("        Ok(v) => v,")
        appendLine("        Err(e) => { kne_set_panic_error(e); 0i64 }")
        appendLine("    }")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendSealedFieldConversion(f: KneParam) {
        when (f.type) {
            KneType.STRING -> {
                appendLine("    let ${f.name} = unsafe { CStr::from_ptr(${f.name}) }.to_str().unwrap_or(\"\").to_string();")
            }
            KneType.BOOLEAN -> {
                appendLine("    let ${f.name} = ${f.name} != 0;")
            }
            else -> {} // Primitives don't need conversion
        }
    }

    private fun sealedFieldArgExpr(f: KneParam): String = when (f.type) {
        KneType.STRING -> f.name // already converted to String above
        KneType.BOOLEAN -> f.name // already converted to bool above
        KneType.FLOAT -> "${f.name} as f32" // i32 → f32 not needed, but f32 C param is f32
        else -> f.name
    }

    private fun StringBuilder.appendSealedVariantFieldGetters(
        sym: String, rustName: String, variant: KneSealedVariant, prefix: String
    ) {
        for (f in variant.fields) {
            // Handle MAP fields specially with dual buffers
            if (f.type is KneType.MAP) {
                appendSealedMapVariantFieldGetter(sym, rustName, variant, f)
                continue
            }

            val fnName = "${sym}_${variant.name}_get_${f.name}"
            val needsBuf = needsOutputBuffer(f.type)

            appendLine("#[no_mangle]")
            if (needsBuf) {
                appendLine("pub extern \"C\" fn $fnName(handle: i64, out_buf: *mut u8, out_buf_len: i32) -> i32 {")
            } else {
                appendLine("pub extern \"C\" fn $fnName(handle: i64) -> ${rustCType(f.type)} {")
            }
            appendLine("    let obj = unsafe { &*(handle as *const $rustName) };")

            // Build match pattern and value expression based on tuple vs struct
            val fieldIndex = variant.fields.indexOf(f)
            val (fieldPattern, valExpr) = if (variant.isTuple) {
                // Tuple variant: match positionally
                if (variant.fields.size == 1) {
                    "$rustName::${variant.name}(ref _v)" to "_v"
                } else {
                    val wildcards = variant.fields.indices.joinToString(", ") { i ->
                        if (i == fieldIndex) "ref _v$i" else "_"
                    }
                    "$rustName::${variant.name}($wildcards)" to "_v$fieldIndex"
                }
            } else {
                // Struct variant: match by field name
                "$rustName::${variant.name} { ref ${f.name}, .. }" to f.name
            }

            appendLine("    match obj {")
            if (needsBuf) {
                appendLine("        $fieldPattern => {")
                appendValueReturnFromBinding(
                    sealedGetterBindingExpr(f, valExpr),
                    f.type,
                    f.rustType,
                    returnsBorrowed = sealedGetterReturnsBorrowed(f.type),
                    indent = "            ",
                )
                appendLine("        }")
            } else {
                val bindingExpr = sealedGetterBindingExpr(f, valExpr)
                appendLine("        $fieldPattern => ${rustReturnExpr(bindingExpr, f.type, f.rustType, sealedGetterReturnsBorrowed(f.type))},")
            }
            appendLine("        _ => ${defaultCReturnValue(f.type)}")
            appendLine("    }")
            appendLine("}")
            appendLine()
        }
    }

    private fun StringBuilder.appendSealedMapVariantFieldGetter(
        sym: String, rustName: String, variant: KneSealedVariant, f: KneParam
    ) {
        val fnName = "${sym}_${variant.name}_get_${f.name}"
        val mapType = f.type as KneType.MAP

        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn $fnName(handle: i64")
        append(", out_keys: ${mapOutPointerType(mapType.keyType)}")
        if (mapType.keyType == KneType.STRING) append(", out_keys_len: i32")
        append(", out_values: ${mapOutPointerType(mapType.valueType)}")
        if (mapType.valueType == KneType.STRING) append(", out_values_len: i32")
        appendLine(", out_max_len: i32) -> i32 {")
        appendLine("    let obj = unsafe { &*(handle as *const $rustName) };")

        // Build match pattern and value expression based on tuple vs struct
        val fieldIndex = variant.fields.indexOf(f)
        val (fieldPattern, valExpr) = if (variant.isTuple) {
            // Tuple variant: match positionally
            if (variant.fields.size == 1) {
                "$rustName::${variant.name}(ref _v)" to "_v"
            } else {
                val wildcards = variant.fields.indices.joinToString(", ") { i ->
                    if (i == fieldIndex) "ref _v$i" else "_"
                }
                "$rustName::${variant.name}($wildcards)" to "_v$fieldIndex"
            }
        } else {
            // Struct variant: match by field name
            "$rustName::${variant.name} { ref ${f.name}, .. }" to f.name
        }

        appendLine("    match obj {")
        appendLine("        $fieldPattern => {")
        appendMapReturnFromBinding(
            sealedGetterBindingExpr(f, valExpr),
            mapType,
            "            ",
            f.rustType
        )
        appendLine("        }")
        appendLine("        _ => 0")
        appendLine("    }")
        appendLine("}")
        appendLine()
    }

    private fun defaultCReturnValue(type: KneType): String {
        val v = when (type) {
            KneType.DOUBLE -> "0.0"
            KneType.FLOAT -> "0.0"
            KneType.STRING -> "0"
            else -> "0"
        }
        return "$v,"
    }

    // --- Top-level functions ---

    private fun StringBuilder.appendTopLevelFunction(fn: KneFunction, prefix: String) {
        val sym = "${prefix}_${fn.name}"
        val needsBuf = needsOutputBuffer(fn.returnType)

        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn $sym(")
        val allParams = mutableListOf<String>()
        for (p in fn.params) {
            val ndc = nullableDataClass(p.type)
            if (p.type == KneType.BYTE_ARRAY || p.type is KneType.LIST) {
                allParams.add("${p.name}_ptr: ${slicePointerType(p.type)}")
                allParams.add("${p.name}_len: i32")
            } else if (ndc != null) {
                allParams.addAll(nullableDataClassSignatureParamList(p.name, ndc))
            } else if (p.type is KneType.DATA_CLASS) {
                val dc = p.type as KneType.DATA_CLASS
                for (field in dc.fields) {
                    allParams.add("${p.name}_${field.name}: ${rustCType(field.type)}")
                }
            } else {
                allParams.add("${p.name}: ${rustCType(p.type)}")
            }
        }
        if (needsBuf) {
            allParams.add("out_buf: *mut u8")
            allParams.add("out_buf_len: i32")
        }
        // Data class return: add per-field out-params
        if (fn.returnType is KneType.DATA_CLASS) {
            val dc = fn.returnType as KneType.DATA_CLASS
            for (field in dc.fields) {
                when (field.type) {
                    KneType.STRING -> {
                        allParams.add("out_${field.name}: *mut u8")
                        allParams.add("out_${field.name}_len: i32")
                    }
                    else -> {
                        allParams.add("out_${field.name}: *mut ${rustCType(field.type)}")
                    }
                }
            }
        }
        // MAP return: dual key/value buffers + max count
        extractMapReturnType(fn.returnType)?.let { mapType ->
            allParams.add("out_keys: ${mapOutPointerType(mapType.keyType)}")
            if (mapType.keyType == KneType.STRING) allParams.add("out_keys_len: i32")
            allParams.add("out_values: ${mapOutPointerType(mapType.valueType)}")
            if (mapType.valueType == KneType.STRING) allParams.add("out_values_len: i32")
            allParams.add("out_max_len: i32")
        }
        append(allParams.joinToString(", "))
        appendLine(") -> ${rustCReturnType(fn.returnType)} {")
        appendLine("    KNE_LAST_ERROR.with(|e| *e.borrow_mut() = None);")
        appendLine("    match catch_unwind(std::panic::AssertUnwindSafe(|| {")
        for (p in fn.params) {
            appendParamConversion(p)
        }
        val callArgs = fn.params.joinToString(", ") { p -> convertedParamName(p) }
        val expr = wrapCallForSafety("${fn.name}($callArgs)", fn.isUnsafe)
        if (fn.canFail) {
            appendFallibleReturnHandling(expr, fn.returnType, fn.returnRustType, fn.returnsBorrowed)
        } else {
            appendValueReturnHandling(expr, fn.returnType, fn.returnRustType, fn.returnsBorrowed)
        }
        appendLine("    })) {")
        if (fn.returnType is KneType.DATA_CLASS) {
            appendLine("        Ok(_) => {},")
        } else {
            appendLine("        Ok(v) => v,")
        }
        appendLine("        Err(e) => { kne_set_panic_error(e); ${defaultReturnValue(fn.returnType)} }")
        appendLine("    }")
        appendLine("}")
        appendLine()
    }

    // --- Suspend infrastructure ---

    private fun StringBuilder.appendSuspendHelpers(prefix: String) {
        appendLine("// ── Suspend helpers ──────────────────────────────────────────────────")
        appendLine()
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${prefix}_kne_cancelJob(job_handle: i64) {")
        appendLine("    if job_handle == 0 { return; }")
        appendLine("    let flag = unsafe { &*(job_handle as *const std::sync::atomic::AtomicBool) };")
        appendLine("    flag.store(true, std::sync::atomic::Ordering::SeqCst);")
        appendLine("}")
        appendLine()
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${prefix}_kne_disposeRef(handle: i64) {")
        appendLine("    if handle == 0 { return; }")
        appendLine("    unsafe { drop(Box::from_raw(handle as *mut String)); }")
        appendLine("}")
        appendLine()
        appendLine("#[no_mangle]")
        appendLine("pub extern \"C\" fn ${prefix}_kne_readStringRef(handle: i64, out_buf: *mut u8, out_buf_len: i32) -> i32 {")
        appendLine("    let s = unsafe { &*(handle as *const String) };")
        appendLine("    let bytes = s.as_bytes();")
        appendLine("    let len = bytes.len() as i32;")
        appendLine("    if len < out_buf_len {")
        appendLine("        unsafe {")
        appendLine("            std::ptr::copy_nonoverlapping(bytes.as_ptr(), out_buf, bytes.len());")
        appendLine("            *out_buf.add(bytes.len()) = 0;")
        appendLine("        }")
        appendLine("    }")
        appendLine("    len + 1")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendFlowMethod(fn: KneFunction, cls: KneClass, prefix: String) {
        val sym = "${prefix}_${cls.simpleName}_${fn.name}"
        val className = cls.simpleName
        val flowType = fn.returnType as KneType.FLOW
        val elemType = flowType.elementType

        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn $sym(handle: i64")
        for (p in fn.params) {
            val ndc = nullableDataClass(p.type)
            if (p.type == KneType.BYTE_ARRAY || p.type is KneType.LIST) {
                append(", ${p.name}_ptr: ${slicePointerType(p.type)}, ${p.name}_len: i32")
            } else if (ndc != null) {
                appendNullableDataClassSignatureParams(p.name, ndc)
            } else if (p.type is KneType.DATA_CLASS) {
                val dc = p.type as KneType.DATA_CLASS
                for (field in dc.fields) {
                    append(", ${p.name}_${field.name}: ${rustCType(field.type)}")
                }
            } else {
                append(", ${p.name}: ${rustCType(p.type)}")
            }
        }
        append(", next_ptr: i64, error_ptr: i64, complete_ptr: i64, cancel_out: *mut i64")
        appendLine(") {")

        // Create cancellation flag
        appendLine("    let cancel_flag = Box::into_raw(Box::new(std::sync::atomic::AtomicBool::new(false)));")
        appendLine("    unsafe { *cancel_out = cancel_flag as i64; }")
        appendLine("    let cancel_addr = cancel_flag as usize;")
        appendLine()

        // Spawn thread
        appendLine("    std::thread::spawn(move || {")
        appendLine("        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {")
        if (fn.isMutating) {
            appendLine("            let obj = unsafe { &mut *(handle as *mut $className) };")
        } else {
            appendLine("            let obj = unsafe { &*(handle as *const $className) };")
        }
        // Param conversions inside the closure
        for (p in fn.params) {
            appendSuspendParamConversion(p)
        }
        val callArgs = fn.params.joinToString(", ") { p -> convertedParamName(p) }
        appendLine("            obj.${fn.name}($callArgs)")
        appendLine("        }));")
        appendLine()
        appendLine("        match result {")
        appendLine("            Ok(vec) => {")
        appendLine("                let next_fn: extern \"C\" fn(i64) = unsafe { std::mem::transmute(next_ptr) };")
        appendLine("                let cancel = unsafe { &*(cancel_addr as *const std::sync::atomic::AtomicBool) };")
        appendLine("                for item in vec {")
        appendLine("                    if cancel.load(std::sync::atomic::Ordering::SeqCst) { break; }")
        appendLine("                    next_fn(${flowElementEncode(elemType)});")
        appendLine("                }")
        appendLine("                let complete_fn: extern \"C\" fn() = unsafe { std::mem::transmute(complete_ptr) };")
        appendLine("                complete_fn();")
        appendLine("            }")
        appendLine("            Err(e) => {")
        appendLine("                kne_set_panic_error(e);")
        appendLine("                let msg = KNE_LAST_ERROR.with(|e| e.borrow_mut().take().unwrap_or_default());")
        appendLine("                let msg_handle = Box::into_raw(Box::new(msg)) as i64;")
        appendLine("                let error_fn: extern \"C\" fn(i64) = unsafe { std::mem::transmute(error_ptr) };")
        appendLine("                error_fn(msg_handle);")
        appendLine("            }")
        appendLine("        }")
        appendLine("    });")
        appendLine("}")
        appendLine()
    }

    /** Encodes a flow element value to i64 for the next_fn callback. */
    private fun flowElementEncode(elemType: KneType): String = when (elemType) {
        KneType.INT -> "item as i64"
        KneType.LONG -> "item as i64"
        KneType.BYTE -> "item as i64"
        KneType.SHORT -> "item as i64"
        KneType.BOOLEAN -> "if item { 1i64 } else { 0i64 }"
        KneType.STRING -> "Box::into_raw(Box::new(item)) as i64"
        KneType.DOUBLE -> "i64::from_ne_bytes(item.to_ne_bytes())"
        KneType.FLOAT -> "item.to_bits() as i64"
        is KneType.ENUM -> "item as i64"
        is KneType.OBJECT -> "Box::into_raw(Box::new(item)) as i64"
        else -> "item as i64"
    }

    private fun StringBuilder.appendSuspendMethod(fn: KneFunction, cls: KneClass, prefix: String) {
        val sym = "${prefix}_${cls.simpleName}_${fn.name}"
        val className = cls.simpleName

        appendLine("#[no_mangle]")
        append("pub extern \"C\" fn $sym(handle: i64")
        for (p in fn.params) {
            val ndc = nullableDataClass(p.type)
            if (p.type == KneType.BYTE_ARRAY || p.type is KneType.LIST) {
                append(", ${p.name}_ptr: ${slicePointerType(p.type)}, ${p.name}_len: i32")
            } else if (ndc != null) {
                appendNullableDataClassSignatureParams(p.name, ndc)
            } else if (p.type is KneType.DATA_CLASS) {
                val dc = p.type as KneType.DATA_CLASS
                for (field in dc.fields) {
                    append(", ${p.name}_${field.name}: ${rustCType(field.type)}")
                }
            } else {
                append(", ${p.name}: ${rustCType(p.type)}")
            }
        }
        append(", cont_ptr: i64, exc_ptr: i64, cancel_out: *mut i64")
        appendLine(") {")

        // Create cancellation flag
        appendLine("    let cancel_flag = Box::into_raw(Box::new(std::sync::atomic::AtomicBool::new(false)));")
        appendLine("    unsafe { *cancel_out = cancel_flag as i64; }")
        appendLine()

        // Spawn thread
        appendLine("    std::thread::spawn(move || {")
        appendLine("        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {")
        if (fn.isMutating) {
            appendLine("            let obj = unsafe { &mut *(handle as *mut $className) };")
        } else {
            appendLine("            let obj = unsafe { &*(handle as *const $className) };")
        }
        // Param conversions inside the closure
        for (p in fn.params) {
            appendSuspendParamConversion(p)
        }
        val callArgs = fn.params.joinToString(", ") { p -> convertedParamName(p) }
        appendLine("            obj.${fn.name}($callArgs)")
        appendLine("        }));")
        appendLine()
        appendLine("        match result {")
        appendLine("            Ok(value) => {")
        appendSuspendContinuationCall(fn.returnType)
        appendLine("            }")
        appendLine("            Err(e) => {")
        appendLine("                kne_set_panic_error(e);")
        appendLine("                let msg = KNE_LAST_ERROR.with(|e| e.borrow_mut().take().unwrap_or_default());")
        appendLine("                let msg_handle = Box::into_raw(Box::new(msg)) as i64;")
        appendLine("                let exc_fn: extern \"C\" fn(i64) = unsafe { std::mem::transmute(exc_ptr) };")
        appendLine("                exc_fn(msg_handle);")
        appendLine("            }")
        appendLine("        }")
        appendLine("    });")
        appendLine("}")
        appendLine()
    }

    /** Generates the continuation callback invocation based on the return type. */
    private fun StringBuilder.appendSuspendContinuationCall(returnType: KneType) {
        appendLine("                let cont_fn: extern \"C\" fn(i32, i64) = unsafe { std::mem::transmute(cont_ptr) };")
        when (returnType) {
            KneType.INT -> appendLine("                cont_fn(1, value as i64);")
            KneType.LONG -> appendLine("                cont_fn(1, value);")
            KneType.DOUBLE -> appendLine("                cont_fn(1, f64::to_bits(value) as i64);")
            KneType.FLOAT -> appendLine("                cont_fn(1, f32::to_bits(value) as i64);")
            KneType.BOOLEAN -> appendLine("                cont_fn(1, (value as i32) as i64);")
            KneType.BYTE -> appendLine("                cont_fn(1, value as i64);")
            KneType.SHORT -> appendLine("                cont_fn(1, value as i64);")
            KneType.STRING -> {
                appendLine("                let str_handle = Box::into_raw(Box::new(value)) as i64;")
                appendLine("                cont_fn(1, str_handle);")
            }
            KneType.UNIT -> appendLine("                cont_fn(1, 0i64);")
            is KneType.OBJECT -> {
                appendLine("                let obj_handle = Box::into_raw(Box::new(value)) as i64;")
                appendLine("                cont_fn(1, obj_handle);")
            }
            is KneType.ENUM -> appendLine("                cont_fn(1, (value as i32) as i64);")
            else -> appendLine("                cont_fn(1, value as i64);")
        }
    }

    /** Param conversion for suspend methods (indented one extra level for the thread closure). */
    private fun StringBuilder.appendSuspendParamConversion(p: KneParam) {
        appendParamConversion(p, "            ")
    }

    // --- Helpers ---

    private fun StringBuilder.appendReceiverBinding(fn: KneFunction, rustTypeName: String) {
        when (fn.receiverKind) {
            KneReceiverKind.BORROWED_SHARED -> {
                appendLine("        let obj = unsafe { &*(handle as *const $rustTypeName) };")
            }
            KneReceiverKind.BORROWED_MUT -> {
                appendLine("        let obj = unsafe { &mut *(handle as *mut $rustTypeName) };")
            }
            KneReceiverKind.OWNED -> {
                // Use ptr::read instead of Box::from_raw to avoid UB on borrowed handles
                // (e.g. objects returned from MAP). Safe for Copy types; for non-Copy types
                // the caller must ensure the handle is owned.
                appendLine("        let obj = unsafe { std::ptr::read(handle as *const $rustTypeName) };")
            }
            KneReceiverKind.NONE -> {
                if (fn.isMutating) {
                    appendLine("        let obj = unsafe { &mut *(handle as *mut $rustTypeName) };")
                } else {
                    appendLine("        let obj = unsafe { &*(handle as *const $rustTypeName) };")
                }
            }
        }
    }

    private fun StringBuilder.appendParamConversion(p: KneParam, indent: String = "        ") {
        when (p.type) {
            KneType.STRING -> {
                appendLine("${indent}let ${p.name}_conv = unsafe { CStr::from_ptr(${p.name}) }.to_str().unwrap_or(\"\");")
                when {
                    requiresStaticStr(p.rustType) -> {
                        appendLine("${indent}let ${p.name}_static_str: &'static str = Box::leak(${p.name}_conv.to_string().into_boxed_str());")
                    }
                    isOsStrLikeRustType(p.rustType) && (p.isBorrowed || isBorrowedRustType(p.rustType)) -> {
                        appendLine("${indent}let ${p.name}_path = std::ffi::OsStr::new(${p.name}_conv);")
                    }
                    isOsStrLikeRustType(p.rustType) -> {
                        appendLine("${indent}let ${p.name}_path = std::ffi::OsString::from(${p.name}_conv.to_string());")
                    }
                    isPathLikeRustType(p.rustType) && (p.isBorrowed || isBorrowedRustType(p.rustType)) -> {
                        appendLine("${indent}let ${p.name}_path = std::path::Path::new(${p.name}_conv);")
                    }
                    isPathLikeRustType(p.rustType) -> {
                        appendLine("${indent}let ${p.name}_path = std::path::PathBuf::from(${p.name}_conv);")
                    }
                    !p.isBorrowed -> {
                        appendLine("${indent}let ${p.name}_str: String = ${p.name}_conv.to_string();")
                    }
                }
            }
            KneType.BOOLEAN -> {
                appendLine("${indent}let ${p.name}_conv = ${p.name} != 0;")
            }
            is KneType.ENUM -> {
                val enumName = (p.type as KneType.ENUM).simpleName
                appendLine("${indent}let ${p.name}_conv: $enumName = unsafe { std::mem::transmute(${p.name} as u8) };")
            }
            is KneType.OBJECT -> {
                appendObjectHandleConversion(p.name, rustHandleTypeName(p.type, p.rustType), p.isBorrowed, indent)
            }
            is KneType.INTERFACE -> {
                appendObjectHandleConversion(p.name, rustHandleTypeName(p.type, p.rustType), p.isBorrowed, indent)
            }
            is KneType.SEALED_ENUM -> {
                appendObjectHandleConversion(p.name, rustHandleTypeName(p.type, p.rustType), p.isBorrowed, indent)
            }
            is KneType.DATA_CLASS -> {
                appendDataClassParamConversion(p, p.type as KneType.DATA_CLASS, indent)
            }
            is KneType.NULLABLE -> {
                appendNullableParamConversion(p, indent)
            }
            is KneType.FUNCTION -> {
                appendFunctionParamConversion(p, indent)
            }
            KneType.BYTE_ARRAY -> {
                appendLine("${indent}let ${p.name}_slice = unsafe { std::slice::from_raw_parts(${p.name}_ptr, ${p.name}_len as usize) };")
                if (expectsOwnedVecLike(p.rustType, p.isBorrowed)) {
                    appendLine("${indent}let ${p.name}_vec = ${p.name}_slice.to_vec();")
                }
            }
            is KneType.LIST -> {
                appendLine("${indent}let ${p.name}_slice = unsafe { std::slice::from_raw_parts(${p.name}_ptr, ${p.name}_len as usize) };")
                if (expectsOwnedVecLike(p.rustType, p.isBorrowed)) {
                    appendLine("${indent}let ${p.name}_vec = ${p.name}_slice.to_vec();")
                }
            }
            else -> {
                primitiveCastType(p.type, p.rustType)?.let { castType ->
                    appendLine("${indent}let ${p.name}_conv = ${p.name} as $castType;")
                }
            }
        }
    }

    private fun StringBuilder.appendObjectHandleConversion(
        name: String,
        rustTypeName: String,
        borrowed: Boolean,
        indent: String,
    ) {
        val useInferredCast = requiresInferredObjectCast(rustTypeName)
        if (borrowed) {
            if (useInferredCast) {
                appendLine("${indent}let ${name}_borrowed = unsafe { &*(${name} as *const _) };")
            } else {
                appendLine("${indent}let ${name}_borrowed = unsafe { &*(${name} as *const $rustTypeName) };")
            }
        } else {
            if (useInferredCast) {
                appendLine("${indent}let ${name}_owned = unsafe { *Box::from_raw(${name} as *mut _) };")
            } else {
                appendLine("${indent}let ${name}_owned = unsafe { *Box::from_raw(${name} as *mut $rustTypeName) };")
            }
        }
    }

    private fun StringBuilder.appendDataClassParamConversion(
        p: KneParam,
        dc: KneType.DATA_CLASS,
        indent: String,
    ) {
        for (field in dc.fields) {
            if (field.type == KneType.STRING) {
                appendLine("${indent}let ${p.name}_${field.name}_conv = unsafe { CStr::from_ptr(${p.name}_${field.name}) }.to_str().unwrap_or(\"\");")
            }
        }
        val fieldAssignments = dc.fields.joinToString(", ") { field ->
            val sourceName = "${p.name}_${field.name}"
            when (field.type) {
                KneType.STRING -> when {
                    requiresStaticStr(field.rustType) -> "${field.name}: Box::leak(${sourceName}_conv.to_string().into_boxed_str())"
                    isPathLikeRustType(field.rustType) -> "${field.name}: std::path::PathBuf::from(${sourceName}_conv)"
                    field.isBorrowed -> "${field.name}: ${sourceName}_conv"
                    else -> "${field.name}: ${sourceName}_conv.to_string()"
                }
                KneType.BOOLEAN -> "${field.name}: ${sourceName} != 0"
                is KneType.ENUM -> "${field.name}: unsafe { std::mem::transmute(${sourceName} as u8) }"
                else -> {
                    primitiveCastType(field.type, field.rustType)?.let { castType ->
                        "${field.name}: ${sourceName} as $castType"
                    } ?: "${field.name}: $sourceName"
                }
            }
        }
        appendLine("${indent}let ${p.name}_dc = ${dc.simpleName} { $fieldAssignments };")
    }

    private fun StringBuilder.appendNullableParamConversion(p: KneParam, indent: String) {
        val inner = (p.type as KneType.NULLABLE).inner
        val optionInnerRustType = optionInnerRustType(p.rustType)
        when (inner) {
            KneType.INT -> {
                val cast = primitiveCastType(inner, optionInnerRustType)
                val rustInner = cast ?: "i32"
                val someExpr = cast?.let { "${p.name} as $it" } ?: "${p.name} as i32"
                appendLine("${indent}let ${p.name}_opt: Option<$rustInner> = if ${p.name} == i64::MIN { None } else { Some($someExpr) };")
            }
            KneType.LONG -> {
                val cast = primitiveCastType(inner, optionInnerRustType)
                val rustInner = cast ?: "i64"
                val someExpr = cast?.let { "${p.name} as $it" } ?: p.name
                appendLine("${indent}let ${p.name}_opt: Option<$rustInner> = if ${p.name} == i64::MIN { None } else { Some($someExpr) };")
            }
            KneType.STRING -> {
                appendLine("${indent}let ${p.name}_opt = if ${p.name}.is_null() { None } else {")
                appendLine("${indent}    let ${p.name}_value = unsafe { CStr::from_ptr(${p.name}) }.to_str().unwrap_or(\"\");")
                when {
                    requiresStaticStr(optionInnerRustType) -> {
                        appendLine("${indent}    Some(Box::leak(${p.name}_value.to_string().into_boxed_str()) as &'static str)")
                    }
                    isPathLikeRustType(optionInnerRustType) && isBorrowedRustType(optionInnerRustType) -> {
                        appendLine("${indent}    Some(std::path::Path::new(${p.name}_value))")
                    }
                    isPathLikeRustType(optionInnerRustType) -> {
                        appendLine("${indent}    Some(std::path::PathBuf::from(${p.name}_value))")
                    }
                    isBorrowedRustType(optionInnerRustType) -> {
                        appendLine("${indent}    Some(${p.name}_value)")
                    }
                    else -> {
                        appendLine("${indent}    Some(${p.name}_value.to_string())")
                    }
                }
                appendLine("${indent}};")
            }
            KneType.BOOLEAN -> {
                appendLine("${indent}let ${p.name}_opt = if ${p.name} < 0 { None } else { Some(${p.name} != 0) };")
            }
            KneType.DOUBLE -> {
                appendLine("${indent}let ${p.name}_opt = if ${p.name} == i64::MIN { None } else { Some(f64::from_ne_bytes(${p.name}.to_ne_bytes())) };")
            }
            KneType.FLOAT -> {
                appendLine("${indent}let ${p.name}_opt = if ${p.name} == i64::MIN { None } else { Some(f32::from_bits(${p.name} as u32)) };")
            }
            KneType.BYTE -> {
                val cast = primitiveCastType(inner, optionInnerRustType) ?: "i8"
                appendLine("${indent}let ${p.name}_opt = if ${p.name} == i32::MIN { None } else { Some(${p.name} as $cast) };")
            }
            KneType.SHORT -> {
                val cast = primitiveCastType(inner, optionInnerRustType) ?: "i16"
                appendLine("${indent}let ${p.name}_opt = if ${p.name} == i32::MIN { None } else { Some(${p.name} as $cast) };")
            }
            is KneType.ENUM -> {
                val enumName = inner.simpleName
                appendLine("${indent}let ${p.name}_opt: Option<$enumName> = if ${p.name} < 0 { None } else { Some(unsafe { std::mem::transmute(${p.name} as u8) }) };")
            }
            is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM -> {
                val rustTypeName = rustHandleTypeName(inner, optionInnerRustType)
                val borrowed = isBorrowedRustType(optionInnerRustType)
                if (borrowed) {
                    if (requiresInferredObjectCast(rustTypeName)) {
                        appendLine("${indent}let ${p.name}_opt = if ${p.name} == 0 { None } else { Some(unsafe { &*(${p.name} as *const _) }) };")
                    } else {
                        appendLine("${indent}let ${p.name}_opt = if ${p.name} == 0 { None } else { Some(unsafe { &*(${p.name} as *const $rustTypeName) }) };")
                    }
                } else {
                    if (requiresInferredObjectCast(rustTypeName)) {
                        appendLine("${indent}let ${p.name}_opt = if ${p.name} == 0 { None } else { Some(unsafe { *Box::from_raw(${p.name} as *mut _) }) };")
                    } else {
                        appendLine("${indent}let ${p.name}_opt = if ${p.name} == 0 { None } else { Some(unsafe { *Box::from_raw(${p.name} as *mut $rustTypeName) }) };")
                    }
                }
            }
            is KneType.DATA_CLASS -> {
                val dc = inner
                val borrowed = isBorrowedRustType(optionInnerRustType)
                // Reconstruct the data class from expanded fields
                for (field in dc.fields) {
                    if (field.type == KneType.STRING) {
                        appendLine("${indent}let ${p.name}_${field.name}_conv = unsafe { CStr::from_ptr(${p.name}_${field.name}) }.to_str().unwrap_or(\"\");")
                    }
                }
                val fieldAssignments = dc.fields.joinToString(", ") { field ->
                    val sourceName = "${p.name}_${field.name}"
                    when (field.type) {
                        KneType.STRING -> when {
                            requiresStaticStr(field.rustType) -> "${field.name}: Box::leak(${sourceName}_conv.to_string().into_boxed_str())"
                            isPathLikeRustType(field.rustType) -> "${field.name}: std::path::PathBuf::from(${sourceName}_conv)"
                            field.isBorrowed -> "${field.name}: ${sourceName}_conv"
                            else -> "${field.name}: ${sourceName}_conv.to_string()"
                        }
                        KneType.BOOLEAN -> "${field.name}: ${sourceName} != 0"
                        is KneType.ENUM -> "${field.name}: unsafe { std::mem::transmute(${sourceName} as u8) }"
                        else -> {
                            primitiveCastType(field.type, field.rustType)?.let { castType ->
                                "${field.name}: ${sourceName} as $castType"
                            } ?: "${field.name}: $sourceName"
                        }
                    }
                }
                val dcVal = "${dc.simpleName} { $fieldAssignments }"
                if (borrowed) {
                    // Declare the value outside the Option so the borrow lives long enough
                    appendLine("${indent}let ${p.name}_dc_val = $dcVal;")
                    appendLine("${indent}let ${p.name}_opt = if ${p.name}_has != 0 { None } else { Some(&${p.name}_dc_val) };")
                } else {
                    appendLine("${indent}let ${p.name}_opt = if ${p.name}_has != 0 { None } else { Some($dcVal) };")
                }
            }
            else -> {
                appendLine("${indent}let ${p.name}_opt = if ${p.name} == i64::MIN { None } else { Some(${p.name}) };")
            }
        }
    }

    /**
     * Generates conversion for a FUNCTION param.
     * For simple types (all primitives): transmute directly to Rust fn() pointer.
     * For types needing conversion (bool, String): transmute to extern "C" fn + closure wrapper.
     */
    private fun StringBuilder.appendFunctionParamConversion(p: KneParam, indent: String) {
        val fnType = p.type as KneType.FUNCTION
        val needsConversion = fnType.paramTypes.any { it == KneType.BOOLEAN || it == KneType.STRING } ||
            (fnType.returnType == KneType.BOOLEAN || fnType.returnType == KneType.STRING)

        if (!needsConversion) {
            // Direct transmute to Rust fn pointer (safe for primitives on x86-64/aarch64)
            val nativeParams = fnType.paramTypes.joinToString(", ") { rustNativeType(it) }
            val nativeRet = if (fnType.returnType == KneType.UNIT) "()" else rustNativeType(fnType.returnType)
            appendLine("${indent}let ${p.name}_fn: fn($nativeParams) -> $nativeRet = unsafe { std::mem::transmute(${p.name}) };")
        } else {
            // Transmute to extern "C" fn, then wrap in closure for type conversion
            val cParamTypes = fnType.paramTypes.mapIndexed { i, t ->
                "_p$i: ${rustCType(t)}"
            }.joinToString(", ")
            val cRetType = if (fnType.returnType == KneType.UNIT) "()" else rustCType(fnType.returnType)
            appendLine("${indent}let ${p.name}_c: extern \"C\" fn($cParamTypes) -> $cRetType = unsafe { std::mem::transmute(${p.name}) };")

            val closureParams = fnType.paramTypes.mapIndexed { i, t ->
                "_cp$i: ${rustNativeType(t)}"
            }.joinToString(", ")
            val closureRetType = if (fnType.returnType == KneType.UNIT) "" else " -> ${rustNativeType(fnType.returnType)}"
            val callArgs = fnType.paramTypes.mapIndexed { i, t ->
                rustToCCallArgConvert("_cp$i", t)
            }.joinToString(", ")
            val callExpr = "${p.name}_c($callArgs)"
            val returnExpr = rustFromCRetConvert(callExpr, fnType.returnType)
            appendLine("${indent}let ${p.name}_fn = |$closureParams|$closureRetType { $returnExpr };")
        }
    }

    /** Rust native type (not C ABI) for closure params. */
    private fun rustNativeType(type: KneType): String = when (type) {
        KneType.INT -> "i32"
        KneType.LONG -> "i64"
        KneType.DOUBLE -> "f64"
        KneType.FLOAT -> "f32"
        KneType.BOOLEAN -> "bool"
        KneType.BYTE -> "i8"
        KneType.SHORT -> "i16"
        KneType.STRING -> "String"
        else -> rustCType(type) // fallback
    }

    /** Convert a Rust native value to C ABI for calling into a C callback. */
    private fun rustToCCallArgConvert(expr: String, type: KneType): String = when (type) {
        KneType.BOOLEAN -> "if $expr { 1 } else { 0 }"
        KneType.STRING -> "std::ffi::CString::new($expr).unwrap().into_raw()"
        else -> expr
    }

    /** Convert a C ABI return value back to Rust native type. */
    private fun rustFromCRetConvert(expr: String, type: KneType): String = when (type) {
        KneType.UNIT -> expr
        KneType.BOOLEAN -> "$expr != 0"
        KneType.STRING -> "unsafe { std::ffi::CString::from_raw($expr as *mut c_char) }.into_string().unwrap_or_default()"
        else -> expr
    }

    /** Param name for method calls — uses isBorrowed to decide &str vs String, &T vs T. */
    private fun convertedParamName(p: KneParam): String = when (p.type) {
        KneType.STRING -> when {
            requiresStaticStr(p.rustType) -> "${p.name}_static_str"
            isPathLikeRustType(p.rustType) -> "${p.name}_path"
            p.isBorrowed || isBorrowedRustType(p.rustType) -> "${p.name}_conv"
            else -> "${p.name}_str"
        }
        KneType.BOOLEAN -> "${p.name}_conv"
        is KneType.FUNCTION -> "${p.name}_fn"
        is KneType.ENUM -> if (p.isBorrowed) "&${p.name}_conv" else "${p.name}_conv"
        is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM ->
            if (p.isBorrowed) "${p.name}_borrowed" else "${p.name}_owned"
        is KneType.DATA_CLASS -> if (p.isBorrowed) "&${p.name}_dc" else "${p.name}_dc"
        is KneType.NULLABLE -> "${p.name}_opt"
        KneType.BYTE_ARRAY -> if (expectsOwnedVecLike(p.rustType, p.isBorrowed)) "${p.name}_vec" else "${p.name}_slice"
        is KneType.LIST -> if (expectsOwnedVecLike(p.rustType, p.isBorrowed)) "${p.name}_vec" else "${p.name}_slice"
        else -> if (primitiveCastType(p.type, p.rustType) != null) "${p.name}_conv" else p.name
    }

    /** Param name for constructor calls — String passes owned String. */
    private fun convertedCallArg(p: KneParam): String = convertedParamName(p)

    private fun StringBuilder.appendNullableReturn(
        nullableType: KneType.NULLABLE,
        binding: String,
        returnsBorrowed: Boolean = false,
        rustType: String? = null,
        indent: String = "        ",
    ) {
        when (nullableType.inner) {
            KneType.INT -> {
                appendLine("${indent}match $binding { Some(v) => v as i64, None => i64::MIN }")
            }
            KneType.LONG -> {
                appendLine("${indent}match $binding { Some(v) => v as i64, None => i64::MIN }")
            }
            KneType.DOUBLE -> {
                appendLine("${indent}match $binding { Some(v) => i64::from_ne_bytes(v.to_ne_bytes()), None => i64::MIN }")
            }
            KneType.FLOAT -> {
                appendLine("${indent}match $binding { Some(v) => v.to_bits() as i64, None => i64::MIN }")
            }
            KneType.BOOLEAN -> {
                appendLine("${indent}match $binding { Some(true) => 1, Some(false) => 0, None => -1 }")
            }
            KneType.BYTE -> {
                appendLine("${indent}match $binding { Some(v) => v as i32, None => i32::MIN }")
            }
            KneType.SHORT -> {
                appendLine("${indent}match $binding { Some(v) => v as i32, None => i32::MIN }")
            }
            KneType.STRING -> {
                appendLine("${indent}match $binding {")
                appendLine("${indent}    Some(ref s) => {")
                appendStringOutput("s", "$indent        ", rustType)
                appendLine("${indent}    }")
                appendLine("${indent}    None => -1")
                appendLine("${indent}}")
            }
            is KneType.ENUM -> {
                appendLine("${indent}match $binding { Some(v) => v as i32, None => -1 }")
            }
            is KneType.DATA_CLASS -> {
                val dc = nullableType.inner
                appendLine("${indent}match $binding {")
                appendLine("${indent}    Some(v) => {")
                for (field in dc.fields) {
                    when (field.type) {
                        KneType.STRING -> {
                            appendLine("${indent}        let _f_bytes = v.${field.name}.as_bytes();")
                            appendLine("${indent}        if (_f_bytes.len() as i32) < out_${field.name}_len {")
                            appendLine("${indent}            unsafe { std::ptr::copy_nonoverlapping(_f_bytes.as_ptr(), out_${field.name}, _f_bytes.len()); }")
                            appendLine("${indent}            unsafe { *out_${field.name}.add(_f_bytes.len()) = 0; }")
                            appendLine("${indent}        }")
                        }
                        else -> {
                            appendLine("${indent}        unsafe { *out_${field.name} = ${rustReturnExpr("v.${field.name}", field.type, field.rustType)}; }")
                        }
                    }
                }
                appendLine("${indent}        1i32")
                appendLine("${indent}    }")
                appendLine("${indent}    None => 0i32")
                appendLine("${indent}}")
            }
            is KneType.LIST -> {
                appendLine("${indent}match $binding {")
                appendLine("${indent}    Some(v) => {")
                appendListReturnFromBinding("v", nullableType.inner as KneType.LIST, "${indent}        ", rustType)
                appendLine("${indent}    }")
                appendLine("${indent}    None => -1")
                appendLine("${indent}}")
            }
            is KneType.SET -> {
                appendLine("${indent}match $binding {")
                appendLine("${indent}    Some(v) => {")
                appendListReturnFromBinding("v", KneType.LIST((nullableType.inner as KneType.SET).elementType), "${indent}        ", rustType)
                appendLine("${indent}    }")
                appendLine("${indent}    None => -1")
                appendLine("${indent}}")
            }
            is KneType.MAP -> {
                appendLine("${indent}match $binding {")
                appendLine("${indent}    Some(v) => {")
                appendMapReturnFromBinding("v", nullableType.inner as KneType.MAP, "${indent}        ", rustType)
                appendLine("${indent}    }")
                appendLine("${indent}    None => -1")
                appendLine("${indent}}")
            }
            is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM -> {
                appendLine("${indent}match $binding {")
                if (returnsBorrowed) {
                    appendLine("${indent}    Some(v) => v as *const _ as i64,")
                } else {
                    appendLine("${indent}    Some(v) => Box::into_raw(Box::new(v)) as i64,")
                }
                appendLine("${indent}    None => 0i64")
                appendLine("${indent}}")
            }
            else -> {
                appendLine("${indent}match $binding { Some(v) => v as i64, None => i64::MIN }")
            }
        }
    }

    private fun rustReturnExpr(
        binding: String,
        returnType: KneType,
        returnRustType: String? = null,
        returnsBorrowed: Boolean = false,
    ): String = when (returnType) {
        KneType.INT -> "$binding as i32"
        KneType.LONG -> "$binding as i64"
        KneType.DOUBLE -> "$binding as f64"
        KneType.FLOAT -> "$binding as f32"
        KneType.BYTE -> "$binding as i8"
        KneType.SHORT -> "$binding as i16"
        KneType.BOOLEAN -> "if $binding { 1 } else { 0 }"
        is KneType.ENUM -> "$binding as i32"
        is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM ->
            if (returnsBorrowed) "$binding as *const _ as i64" else "Box::into_raw(Box::new($binding)) as i64"
        else -> binding
    }

    private fun StringBuilder.appendStringOutput(expr: String, indent: String = "        ", rustType: String? = null) {
        if (isPathLikeRustType(rustType)) {
            appendLine("${indent}let _s = $expr.to_string_lossy();")
            appendLine("${indent}let bytes = _s.as_bytes();")
        } else {
            appendLine("${indent}let bytes = $expr.as_bytes();")
        }
        appendLine("${indent}let len = bytes.len() as i32;")
        appendLine("${indent}if len < out_buf_len {")
        appendLine("${indent}    unsafe {")
        appendLine("${indent}        std::ptr::copy_nonoverlapping(bytes.as_ptr(), out_buf, bytes.len());")
        appendLine("${indent}        *out_buf.add(bytes.len()) = 0;")
        appendLine("${indent}    }")
        appendLine("${indent}}")
        appendLine("${indent}len + 1")
    }

    private fun expectsOwnedVecLike(rustType: String?, isBorrowed: Boolean): Boolean {
        if (isBorrowed) return false
        val normalized = normalizeRustType(rustType) ?: return false
        return normalized.startsWith("Vec<") || normalized.startsWith("Into<Vec<") || normalized.startsWith("From<Vec<")
    }

    private fun wrapCallForSafety(expr: String, isUnsafe: Boolean): String =
        if (isUnsafe) "unsafe { $expr }" else expr

    private fun primitiveCastType(type: KneType, rustType: String?): String? {
        val normalized = normalizeRustType(rustType) ?: return null
        val defaultRustType = when (type) {
            KneType.INT -> "i32"
            KneType.LONG -> "i64"
            KneType.DOUBLE -> "f64"
            KneType.FLOAT -> "f32"
            KneType.BYTE -> "i8"
            KneType.SHORT -> "i16"
            else -> null
        } ?: return null
        return when (normalized) {
            defaultRustType -> null
            "u32", "u64", "usize", "isize", "u16", "u8" -> normalized
            else -> null
        }
    }

    private fun rustHandleTypeName(type: KneType, rustType: String?): String {
        val normalized = unwrapRustWrapperType(rustType)
        return when (type) {
            is KneType.OBJECT -> normalized ?: type.simpleName
            is KneType.INTERFACE -> normalized ?: type.simpleName
            is KneType.SEALED_ENUM -> normalized ?: type.simpleName
            else -> normalized ?: error("Expected handle-backed type, got $type")
        }
    }

    private fun requiresInferredObjectCast(rustTypeName: String): Boolean =
        rustTypeName.contains("::") &&
            !rustTypeName.startsWith("dpi::") &&
            !rustTypeName.startsWith("std::")

    private fun unwrapRustWrapperType(rustType: String?): String? {
        var current = rustType?.trim() ?: return null
        var changed = true
        while (changed) {
            changed = false
            normalizeRustType(current)?.let { normalized ->
                if (normalized != current) {
                    current = normalized
                    changed = true
                }
            }
            for (wrapper in listOf("Option", "Into", "From")) {
                extractGenericInner(current, wrapper)?.let { inner ->
                    current = inner
                    changed = true
                }
            }
        }
        return current.ifBlank { null }
    }

    private fun extractGenericInner(rustType: String, wrapper: String): String? {
        val prefix = "$wrapper<"
        if (!rustType.startsWith(prefix) || !rustType.endsWith(">")) return null
        return rustType.substring(prefix.length, rustType.length - 1).trim()
    }

    private fun optionInnerRustType(rustType: String?): String? =
        rustType?.trim()?.let { extractGenericInner(it, "Option") }

    private fun normalizeRustType(rustType: String?): String? {
        var result = rustType?.trim() ?: return null
        var changed = true
        while (changed) {
            changed = false
            if (result.startsWith("&")) {
                result = result.removePrefix("&").trim()
                changed = true
            }
            if (result.startsWith("mut ")) {
                result = result.removePrefix("mut ").trim()
                changed = true
            }
            if (result.startsWith("'")) {
                val afterLifetime = result.substringAfter(' ', result).trim()
                if (afterLifetime != result) {
                    result = afterLifetime
                    changed = true
                }
            }
        }
        return result.ifBlank { null }
    }

    private fun isBorrowedRustType(rustType: String?): Boolean = rustType?.trim()?.startsWith("&") == true

    private fun isPathLikeRustType(rustType: String?): Boolean {
        val normalized = normalizeRustType(rustType) ?: return false
        return normalized.contains("Path") || normalized.contains("OsStr") || normalized.contains("OsString")
    }

    private fun isOsStrLikeRustType(rustType: String?): Boolean {
        val normalized = normalizeRustType(rustType) ?: return false
        return normalized.contains("OsStr") || normalized.contains("OsString")
    }

    private fun requiresStaticStr(rustType: String?): Boolean =
        rustType?.contains("'static str") == true

    private fun sealedGetterReturnsBorrowed(type: KneType): Boolean = when (type) {
        is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM -> true
        is KneType.NULLABLE -> sealedGetterReturnsBorrowed(type.inner)
        else -> false
    }

    private fun sealedGetterBindingExpr(field: KneParam, valueExpr: String): String = when (field.type) {
        KneType.STRING, KneType.BYTE_ARRAY,
        is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM,
        is KneType.NULLABLE, is KneType.LIST, is KneType.SET, is KneType.MAP -> valueExpr
        else -> "*$valueExpr"
    }

    /** C ABI pointer type for a slice parameter. */
    private fun slicePointerType(type: KneType): String = when (type) {
        KneType.BYTE_ARRAY -> "*const u8"
        is KneType.LIST -> when (type.elementType) {
            KneType.INT -> "*const i32"
            KneType.LONG -> "*const i64"
            KneType.DOUBLE -> "*const f64"
            KneType.FLOAT -> "*const f32"
            else -> "*const i64"
        }
        else -> "*const u8"
    }

    /** Extract DATA_CLASS from a nullable param type, if applicable. */
    private fun nullableDataClass(type: KneType): KneType.DATA_CLASS? =
        (type as? KneType.NULLABLE)?.inner as? KneType.DATA_CLASS

    /** Append C ABI params for a nullable DATA_CLASS: a sentinel flag + expanded fields. */
    private fun StringBuilder.appendNullableDataClassSignatureParams(paramName: String, dc: KneType.DATA_CLASS, separator: String = ", ") {
        append("${separator}${paramName}_has: i32")
        for (field in dc.fields) {
            append(", ${paramName}_${field.name}: ${rustCType(field.type)}")
        }
    }

    /** Same as [appendNullableDataClassSignatureParams] but returns list entries. */
    private fun nullableDataClassSignatureParamList(paramName: String, dc: KneType.DATA_CLASS): List<String> {
        val params = mutableListOf("${paramName}_has: i32")
        for (field in dc.fields) {
            params.add("${paramName}_${field.name}: ${rustCType(field.type)}")
        }
        return params
    }

    /** C ABI type for a parameter. */
    private fun rustCType(type: KneType): String = when (type) {
        KneType.INT -> "i32"
        KneType.LONG -> "i64"
        KneType.DOUBLE -> "f64"
        KneType.FLOAT -> "f32"
        KneType.BOOLEAN -> "i32" // 0/1
        KneType.BYTE -> "i8"
        KneType.SHORT -> "i16"
        KneType.STRING -> "*const c_char"
        KneType.UNIT -> "()"
        is KneType.OBJECT -> "i64" // opaque handle
        is KneType.INTERFACE -> "i64"
        is KneType.SEALED_ENUM -> "i64" // opaque handle
        is KneType.ENUM -> "i32" // ordinal
        is KneType.NULLABLE -> when ((type).inner) {
            KneType.STRING -> "*const c_char" // null pointer = None
            KneType.BOOLEAN -> "i32" // -1 = null
            KneType.BYTE, KneType.SHORT -> "i32"
            is KneType.ENUM -> "i32"
            is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM -> "i64"
            else -> "i64" // widened or sentinel
        }
        is KneType.LIST -> "i64" // pointer handle
        is KneType.SET -> "i64"
        is KneType.MAP -> "i64"
        KneType.BYTE_ARRAY -> "i64"
        is KneType.DATA_CLASS -> "i64"
        is KneType.FUNCTION -> "i64"
        is KneType.FLOW -> "()"
    }

    /** C ABI return type. Buffer-pattern types return i32 (byte/element count). */
    private fun rustCReturnType(type: KneType): String = when (type) {
        KneType.STRING -> "i32"
        KneType.BYTE_ARRAY -> "i32"
        KneType.UNIT -> "()"
        is KneType.LIST -> "i32"
        is KneType.MAP -> "i32" // element count
        is KneType.DATA_CLASS -> "()" // Data class returns use per-field out-params
        is KneType.NULLABLE -> when ((type).inner) {
            KneType.INT, KneType.LONG, KneType.DOUBLE, KneType.FLOAT -> "i64"
            KneType.BOOLEAN, KneType.BYTE, KneType.SHORT, KneType.STRING -> "i32"
            is KneType.ENUM -> "i32"
            is KneType.DATA_CLASS -> "i32" // 0=None, 1=Some (fields in out-params)
            is KneType.LIST, is KneType.SET, is KneType.MAP -> "i32" // count or -1 for None
            is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM -> "i64"
            else -> "i64"
        }
        else -> rustCType(type)
    }

    /** Conversion suffix for return expressions (e.g., " as i32" for Boolean). */
    private fun rustReturnConversion(type: KneType): String = when (type) {
        KneType.BOOLEAN -> " as i32"
        is KneType.ENUM -> " as i32"
        else -> ""
    }

    /** Default value returned on panic/error. */
    private fun defaultReturnValue(type: KneType): String = when (type) {
        KneType.INT, KneType.BYTE, KneType.SHORT -> "0"
        KneType.LONG -> "0i64"
        KneType.DOUBLE -> "0.0f64"
        KneType.FLOAT -> "0.0f32"
        KneType.BOOLEAN -> "0"
        KneType.STRING -> "0" // byte count = 0
        KneType.UNIT -> "()"
        is KneType.MAP -> "0" // element count = 0
        is KneType.DATA_CLASS -> "()" // out-params pattern, void return
        is KneType.OBJECT, is KneType.INTERFACE, is KneType.SEALED_ENUM -> "0i64"
        is KneType.ENUM -> "0"
        is KneType.NULLABLE -> when ((type).inner) {
            KneType.BOOLEAN, KneType.BYTE, KneType.SHORT, KneType.STRING -> "0i32"
            is KneType.ENUM -> "0i32"
            is KneType.DATA_CLASS -> "0i32" // 0 = None
            is KneType.LIST, is KneType.SET, is KneType.MAP -> "0" // count = 0 on error
            else -> "0i64"
        }
        else -> "0"
    }
}
