package io.github.kdroidfilter.kotlinnativeexport.plugin.codegen

import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneClass
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneDataClass
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneEnum
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneFunction
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneModule
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneParam
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneProperty
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneType

/**
 * Generates Kotlin/JVM FFM proxy code.
 *
 * Inspired by swift-java's FFMSwift2JavaGenerator:
 *  - Each exported symbol gets a descriptor class with FunctionDescriptor + MethodHandle
 *    (mirroring swift-java's inner descriptor classes per method).
 *  - Object lifecycle uses Java Cleaner + a captured Long handle
 *    (mirrors swift-java's AllocatingSwiftArena + swift_retain/swift_release pattern).
 *  - String I/O uses the output-buffer pattern (Arena.allocate + get/set ADDRESS).
 *  - Exception propagation: every downcall is followed by KneRuntime.checkError()
 *    which queries the native @ThreadLocal error state.
 *
 * Generated classes have the exact same API as the native Kotlin classes,
 * making the bridge fully transparent to the JVM developer.
 */
class FfmProxyGenerator {

    companion object {
        private const val STRING_BUF_SIZE = 8192
        private const val ERR_BUF_SIZE = 8192
    }

    private fun KneType.returnsViaBuffer(): Boolean =
        this == KneType.STRING || (this is KneType.NULLABLE && inner == KneType.STRING)

    private fun KneType.isStringLike(): Boolean =
        this == KneType.STRING || (this is KneType.NULLABLE && inner == KneType.STRING)

    private fun KneType.isFunctionType(): Boolean = this is KneType.FUNCTION

    /** Check if a function needs a confined arena (for string alloc only — callbacks use persistent arena). */
    private fun needsConfinedArena(params: List<KneParam>, returnType: KneType): Boolean =
        params.any { it.type.isStringLike() } || returnType.isStringLike()

    private fun classHasCallbacks(cls: KneClass): Boolean =
        cls.methods.any { fn -> fn.params.any { it.type is KneType.FUNCTION } } ||
        cls.companionMethods.any { fn -> fn.params.any { it.type is KneType.FUNCTION } }

    /**
     * Generates all proxy files for the module.
     * Returns a map of filename → file content.
     */
    fun generate(module: KneModule, jvmPackage: String): Map<String, String> {
        val files = mutableMapOf<String, String>()

        // Collect all unique callback signatures used across the module
        val callbackSignatures = collectCallbackSignatures(module)

        files["KneRuntime.kt"] = generateRuntime(module.libName, jvmPackage, callbackSignatures)
        files["KotlinNativeException.kt"] = generateException(jvmPackage)

        module.dataClasses.filter { !it.isCommon }.forEach { dc ->
            files["${dc.simpleName}.kt"] = generateDataClassFile(dc, jvmPackage)
        }

        module.classes.forEach { cls ->
            files["${cls.simpleName}.kt"] = generateClassProxy(cls, module, jvmPackage)
        }

        module.enums.forEach { enum ->
            files["${enum.simpleName}.kt"] = generateEnumProxy(enum, module, jvmPackage)
        }

        if (module.functions.isNotEmpty()) {
            val objectName = module.libName.replaceFirstChar { it.uppercaseChar() }
            files["$objectName.kt"] = generateFunctionObject(module.functions, objectName, module, jvmPackage)
        }

        return files
    }

    // ── Runtime helper ────────────────────────────────────────────────────────

    /** Collect all unique KneType.FUNCTION signatures used as parameters in the module. */
    private fun collectCallbackSignatures(module: KneModule): Set<KneType.FUNCTION> {
        val signatures = mutableSetOf<KneType.FUNCTION>()
        fun scanParams(params: List<KneParam>) {
            params.forEach { p -> if (p.type is KneType.FUNCTION) signatures.add(p.type) }
        }
        module.classes.forEach { cls ->
            cls.methods.forEach { scanParams(it.params) }
            cls.companionMethods.forEach { scanParams(it.params) }
        }
        module.functions.forEach { scanParams(it.params) }
        return signatures
    }

    /** Generate a unique identifier for a callback signature. */
    private fun callbackId(fnType: KneType.FUNCTION): String {
        val params = fnType.paramTypes.joinToString("_") { it.jvmTypeName }
        val ret = fnType.returnType.jvmTypeName
        return "${params.ifEmpty { "Void" }}_to_$ret"
    }

    private fun generateRuntime(libName: String, pkg: String, callbackSignatures: Set<KneType.FUNCTION> = emptySet()): String = buildString {
        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("import java.lang.foreign.Arena")
        appendLine("import java.lang.foreign.FunctionDescriptor")
        appendLine("import java.lang.foreign.Linker")
        appendLine("import java.lang.foreign.SymbolLookup")
        appendLine("import java.lang.foreign.MemorySegment")
        appendLine("import java.lang.foreign.ValueLayout.*")
        appendLine("import java.lang.invoke.MethodHandle")
        appendLine("import java.nio.file.Paths")
        appendLine()
        appendLine("/**")
        appendLine(" * Shared FFM runtime: loads the native library, resolves MethodHandles,")
        appendLine(" * and propagates exceptions from the native side.")
        appendLine(" */")
        appendLine("internal object KneRuntime {")
        appendLine()
        appendLine("    val linker: Linker = Linker.nativeLinker()")
        appendLine("    private val globalArena: Arena = Arena.global()")
        appendLine()
        appendLine("    val library: SymbolLookup by lazy { loadLibrary(\"$libName\") }")
        appendLine()
        appendLine("    private fun loadLibrary(name: String): SymbolLookup {")
        appendLine("        val fileName = System.mapLibraryName(name)")
        appendLine("        val sep = if (System.getProperty(\"os.name\").lowercase().contains(\"win\")) \";\" else \":\"")
        appendLine("        val basePaths = System.getProperty(\"java.library.path\", \"\").split(sep)")
        appendLine("        val extraDirs = mutableListOf(System.getProperty(\"user.dir\", \".\"))")
        appendLine("        try {")
        appendLine("            ProcessHandle.current().info().command().ifPresent { cmd ->")
        appendLine("                Paths.get(cmd).parent?.toString()?.let { extraDirs.add(it) }")
        appendLine("            }")
        appendLine("        } catch (_: Exception) {}")
        appendLine("        val allBases = (basePaths + extraDirs).distinct().filter { it.isNotBlank() }")
        appendLine("        val paths = allBases + allBases.map { Paths.get(it, \"lib\").toString() }")
        appendLine("        for (dir in paths) {")
        appendLine("            val file = Paths.get(dir, fileName).toFile()")
        appendLine("            if (file.exists()) return SymbolLookup.libraryLookup(file.toPath(), globalArena)")
        appendLine("        }")
        appendLine("        return SymbolLookup.loaderLookup()")
        appendLine("    }")
        appendLine()
        appendLine("    fun handle(symbol: String, descriptor: FunctionDescriptor): MethodHandle =")
        appendLine("        linker.downcallHandle(")
        appendLine("            library.find(symbol).orElseThrow { UnsatisfiedLinkError(\"Symbol not found: \$symbol\") },")
        appendLine("            descriptor,")
        appendLine("        )")
        appendLine()
        appendLine("    // ── Exception propagation ────────────────────────────────────────────")
        appendLine()
        appendLine("    private val HAS_ERROR_HANDLE: MethodHandle by lazy {")
        appendLine("        handle(\"${libName}_kne_hasError\", FunctionDescriptor.of(JAVA_INT))")
        appendLine("    }")
        appendLine("    private val GET_LAST_ERROR_HANDLE: MethodHandle by lazy {")
        appendLine("        handle(\"${libName}_kne_getLastError\", FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT))")
        appendLine("    }")
        appendLine()
        appendLine("    fun checkError() {")
        appendLine("        val hasError = HAS_ERROR_HANDLE.invoke() as Int")
        appendLine("        if (hasError != 0) {")
        appendLine("            Arena.ofConfined().use { arena ->")
        appendLine("                val buf = arena.allocate($ERR_BUF_SIZE.toLong())")
        appendLine("                GET_LAST_ERROR_HANDLE.invoke(buf, $ERR_BUF_SIZE)")
        appendLine("                throw KotlinNativeException(buf.getString(0))")
        appendLine("            }")
        appendLine("        }")
        appendLine("    }")

        // Generate upcall infrastructure for each callback signature
        if (callbackSignatures.isNotEmpty()) {
            appendLine()
            appendLine("    // ── Callback upcall stubs ────────────────────────────────────────────")
            for (sig in callbackSignatures) {
                appendUpcallInfrastructure(sig)
            }
        }

        appendLine("}")
    }

    // ── Exception class ──────────────────────────────────────────────────────

    private fun generateException(pkg: String): String = buildString {
        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("/**")
        appendLine(" * Exception thrown when a Kotlin/Native function throws across the FFM boundary.")
        appendLine(" * The message contains the original Kotlin exception's message.")
        appendLine(" */")
        appendLine("class KotlinNativeException(message: String) : RuntimeException(message)")
    }

    /**
     * Generates upcall infrastructure for a callback signature:
     * - A JVM static target method that invokes the lambda
     * - A lazy MethodHandle for the target
     * - A factory method to create upcall stubs
     */
    private fun StringBuilder.appendUpcallInfrastructure(sig: KneType.FUNCTION) {
        val id = callbackId(sig)
        val paramCount = sig.paramTypes.size

        // Static upcall target method
        // Expand DATA_CLASS params into individual field params at C ABI level
        data class FlatParam(val name: String, val type: KneType)
        val flatParams = mutableListOf<FlatParam>()
        sig.paramTypes.forEachIndexed { i, t ->
            if (t is KneType.DATA_CLASS) {
                t.fields.forEach { f -> flatParams.add(FlatParam("p${i}_${f.name}", f.type)) }
            } else {
                flatParams.add(FlatParam("p$i", t))
            }
        }

        val targetParams = buildList {
            add("fn: Any")
            flatParams.forEach { add("${it.name}: ${upcallJvmType(it.type)}") }
        }.joinToString(", ")

        val returnJvmType = upcallJvmType(sig.returnType)
        val returnDecl = if (sig.returnType == KneType.UNIT) "" else ": $returnJvmType"

        appendLine()
        appendLine("    @JvmStatic")
        appendLine("    fun _upcall_$id($targetParams)$returnDecl {")

        appendLine("        @Suppress(\"UNCHECKED_CAST\")")
        appendLine("        val _fn = fn as ${sig.jvmTypeName}")

        // Reconstruct DATA_CLASS params from flat fields, convert others
        val invokeConvertedArgs = sig.paramTypes.mapIndexed { i, t ->
            when (t) {
                KneType.BOOLEAN -> "p$i != 0"
                KneType.STRING -> "p$i.reinterpret(8192).getString(0)"
                is KneType.ENUM -> "${t.simpleName}.entries[p$i]"
                is KneType.DATA_CLASS -> {
                    val fieldArgs = t.fields.joinToString(", ") { f ->
                        val pName = "p${i}_${f.name}"
                        when (f.type) {
                            KneType.BOOLEAN -> "${f.name} = $pName != 0"
                            KneType.STRING -> "${f.name} = $pName.reinterpret(8192).getString(0)"
                            else -> "${f.name} = $pName"
                        }
                    }
                    "${t.simpleName}($fieldArgs)"
                }
                else -> "p$i"
            }
        }.joinToString(", ")

        if (sig.returnType == KneType.UNIT) {
            appendLine("        _fn.invoke($invokeConvertedArgs)")
        } else if (sig.returnType == KneType.BOOLEAN) {
            appendLine("        return if (_fn.invoke($invokeConvertedArgs)) 1 else 0")
        } else if (sig.returnType == KneType.STRING) {
            appendLine("        return Arena.ofAuto().allocateFrom(_fn.invoke($invokeConvertedArgs))")
        } else if (sig.returnType is KneType.ENUM) {
            appendLine("        return _fn.invoke($invokeConvertedArgs).ordinal")
        } else {
            appendLine("        return _fn.invoke($invokeConvertedArgs)")
        }
        appendLine("    }")

        // MethodHandle for the upcall target
        val methodTypeArgs = buildList {
            add(upcallMethodTypeArg(sig.returnType))
            add("Any::class.java")
            flatParams.forEach { add(upcallMethodTypeArg(it.type)) }
        }.joinToString(", ")

        appendLine()
        appendLine("    val UPCALL_MH_$id: MethodHandle by lazy {")
        appendLine("        java.lang.invoke.MethodHandles.lookup().findStatic(")
        appendLine("            KneRuntime::class.java, \"_upcall_$id\",")
        appendLine("            java.lang.invoke.MethodType.methodType($methodTypeArgs)")
        appendLine("        )")
        appendLine("    }")

        // FunctionDescriptor for the callback's C ABI (DATA_CLASS expanded to fields)
        val descLayouts = flatParams.joinToString(", ") { upcallLayout(it.type) }
        val descExpr = if (sig.returnType == KneType.UNIT) {
            if (descLayouts.isEmpty()) "FunctionDescriptor.ofVoid()"
            else "FunctionDescriptor.ofVoid($descLayouts)"
        } else {
            val retLayout = upcallLayout(sig.returnType)
            if (descLayouts.isEmpty()) "FunctionDescriptor.of($retLayout)"
            else "FunctionDescriptor.of($retLayout, $descLayouts)"
        }
        appendLine("    val UPCALL_DESC_$id: FunctionDescriptor = $descExpr")

        // Factory method to create upcall stubs
        appendLine()
        appendLine("    fun createUpcallStub_$id(fn: ${sig.jvmTypeName}, arena: Arena): Long {")
        appendLine("        val bound = UPCALL_MH_$id.bindTo(fn)")
        appendLine("        return linker.upcallStub(bound, UPCALL_DESC_$id, arena).address()")
        appendLine("    }")
    }

    /** The Java type name for upcall method signatures (C ABI compatible). */
    private fun upcallJvmType(type: KneType): String = when (type) {
        KneType.INT -> "Int"
        KneType.LONG -> "Long"
        KneType.DOUBLE -> "Double"
        KneType.FLOAT -> "Float"
        KneType.BOOLEAN -> "Int" // C ABI: int for bool
        KneType.BYTE -> "Byte"
        KneType.SHORT -> "Short"
        KneType.STRING -> "MemorySegment"
        KneType.UNIT -> "Unit"
        else -> "Int"
    }

    /** The MethodType argument for a callback param/return type. */
    private fun upcallMethodTypeArg(type: KneType): String = when (type) {
        KneType.UNIT -> "Void.TYPE"
        KneType.STRING -> "java.lang.foreign.MemorySegment::class.java"
        else -> "${upcallJvmType(type)}::class.javaPrimitiveType"
    }

    /** The FFM ValueLayout for a callback parameter/return type. */
    private fun upcallLayout(type: KneType): String = when (type) {
        KneType.INT -> "JAVA_INT"
        KneType.LONG -> "JAVA_LONG"
        KneType.DOUBLE -> "JAVA_DOUBLE"
        KneType.FLOAT -> "JAVA_FLOAT"
        KneType.BOOLEAN -> "JAVA_INT"
        KneType.BYTE -> "JAVA_BYTE"
        KneType.SHORT -> "JAVA_SHORT"
        KneType.STRING -> "ADDRESS"
        else -> "JAVA_INT"
    }

    // ── Class proxy ──────────────────────────────────────────────────────────

    private fun generateClassProxy(cls: KneClass, module: KneModule, pkg: String): String = buildString {
        val p = module.libName
        val n = cls.simpleName

        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("import java.lang.foreign.Arena")
        appendLine("import java.lang.foreign.FunctionDescriptor")
        appendLine("import java.lang.foreign.MemorySegment")
        appendLine("import java.lang.foreign.ValueLayout.*")
        appendLine("import java.lang.invoke.MethodHandle")
        appendLine("import java.lang.ref.Cleaner")
        appendLine()

        appendLine("/**")
        appendLine(" * JVM proxy for Kotlin/Native class [$n].")
        appendLine(" * Uses FFM MethodHandles to dispatch every call to the native shared library.")
        appendLine(" * Object lifecycle is managed via Java Cleaner (automatic GC) or explicit close().")
        appendLine(" */")
        val hasCallbacks = classHasCallbacks(cls)

        appendLine("class $n private constructor(internal val handle: Long) : AutoCloseable {")
        if (hasCallbacks) {
            appendLine("    internal val _callbackArena: Arena = Arena.ofShared()")
        }
        appendLine()

        val companionHasCallbacks = cls.companionMethods.any { fn -> fn.params.any { it.type is KneType.FUNCTION } }

        // Companion: MethodHandles + factory
        appendLine("    companion object {")
        appendLine("        private val CLEANER = Cleaner.create()")
        if (companionHasCallbacks) {
            appendLine("        private val _companionCallbackArena: Arena = Arena.ofShared()")
        }
        appendLine()

        val ctorLayouts = buildLayouts(cls.constructor.params.map { it.type })
        appendLine("        private val NEW_HANDLE: MethodHandle by lazy {")
        appendLine("            KneRuntime.handle(\"${p}_${n}_new\",")
        appendLine("                FunctionDescriptor.of(JAVA_LONG$ctorLayouts))")
        appendLine("        }")
        appendLine("        private val DISPOSE_HANDLE: MethodHandle by lazy {")
        appendLine("            KneRuntime.handle(\"${p}_${n}_dispose\",")
        appendLine("                FunctionDescriptor.ofVoid(JAVA_LONG))")
        appendLine("        }")

        cls.methods.forEach { method ->
            val handleName = "${method.name.uppercase()}_HANDLE"
            val descriptor = buildMethodDescriptor(method)
            appendLine("        private val $handleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_${method.name}\",")
            appendLine("                $descriptor)")
            appendLine("        }")
        }

        cls.properties.forEach { prop ->
            val getHandleName = "GET_${prop.name.uppercase()}_HANDLE"
            val getDescriptor = buildGetterDescriptor(prop)
            appendLine("        private val $getHandleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_get_${prop.name}\",")
            appendLine("                $getDescriptor)")
            appendLine("        }")
            if (prop.mutable) {
                val setHandleName = "SET_${prop.name.uppercase()}_HANDLE"
                val setLayouts = buildLayouts(listOf(prop.type))
                appendLine("        private val $setHandleName: MethodHandle by lazy {")
                appendLine("            KneRuntime.handle(\"${p}_${n}_set_${prop.name}\",")
                appendLine("                FunctionDescriptor.ofVoid(JAVA_LONG$setLayouts))")
                appendLine("        }")
            }
        }

        cls.companionMethods.forEach { method ->
            val handleName = "COMPANION_${method.name.uppercase()}_HANDLE"
            val descriptor = buildTopLevelDescriptor(method)
            appendLine("        private val $handleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_companion_${method.name}\",")
            appendLine("                $descriptor)")
            appendLine("        }")
        }
        cls.companionProperties.forEach { prop ->
            val getHandleName = "COMPANION_GET_${prop.name.uppercase()}_HANDLE"
            val getDescriptor = buildCompanionGetterDescriptor(prop)
            appendLine("        private val $getHandleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_companion_get_${prop.name}\",")
            appendLine("                $getDescriptor)")
            appendLine("        }")
            if (prop.mutable) {
                val setHandleName = "COMPANION_SET_${prop.name.uppercase()}_HANDLE"
                appendLine("        private val $setHandleName: MethodHandle by lazy {")
                appendLine("            KneRuntime.handle(\"${p}_${n}_companion_set_${prop.name}\",")
                appendLine("                FunctionDescriptor.ofVoid(${prop.type.ffmLayout}))")
                appendLine("        }")
            }
        }

        // Factory
        val ctorParams = cls.constructor.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }
        appendLine()
        appendLine("        /**")
        appendLine("         * Creates a new [$n] backed by a Kotlin/Native object.")
        appendLine("         * The native object is automatically released when GC'd or close() is called.")
        appendLine("         */")
        appendLine("        operator fun invoke($ctorParams): $n {")
        if (cls.constructor.params.any { it.type.isStringLike() || it.type.isFunctionType() }) {
            appendLine("            Arena.ofConfined().use { arena ->")
            appendStringInvokeArgsAlloc("                ", cls.constructor.params)
            val ctorInvokeArgs = buildCtorInvokeArgs(cls.constructor.params)
            appendLine("                val h = NEW_HANDLE.invoke($ctorInvokeArgs) as Long")
            appendLine("                KneRuntime.checkError()")
            appendLine("                return fromNativeHandle(h)")
            appendLine("            }")
        } else {
            val ctorInvokeArgs = buildCtorInvokeArgs(cls.constructor.params)
            appendLine("            val h = NEW_HANDLE.invoke($ctorInvokeArgs) as Long")
            appendLine("            KneRuntime.checkError()")
            appendLine("            return fromNativeHandle(h)")
        }
        appendLine("        }")
        appendLine()

        appendLine("        internal fun fromNativeHandle(h: Long): $n {")
        appendLine("            val obj = $n(h)")
        if (hasCallbacks) {
            appendLine("            val cbArena = obj._callbackArena")
            appendLine("            CLEANER.register(obj) { runCatching { cbArena.close() }; runCatching { DISPOSE_HANDLE.invoke(h) } }")
        } else {
            appendLine("            CLEANER.register(obj) { runCatching { DISPOSE_HANDLE.invoke(h) } }")
        }
        appendLine("            return obj")
        appendLine("        }")

        // Companion methods
        cls.companionMethods.forEach { method -> appendCompanionMethodProxy(method) }
        cls.companionProperties.forEach { prop -> appendCompanionPropertyProxy(prop) }

        appendLine("    }")
        appendLine()

        // Methods
        cls.methods.forEach { method -> appendMethodProxy(method, cls, p) }
        cls.properties.forEach { prop -> appendPropertyProxy(prop, cls) }

        // close()
        appendLine("    override fun close() {")
        if (hasCallbacks) {
            appendLine("        runCatching { _callbackArena.close() }")
        }
        appendLine("        runCatching { DISPOSE_HANDLE.invoke(handle) }")
        appendLine("    }")
        appendLine("}")
    }

    private fun StringBuilder.appendMethodProxy(fn: KneFunction, cls: KneClass, prefix: String) {
        val handleName = "${fn.name.uppercase()}_HANDLE"
        val params = fn.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }

        appendLine("    fun ${fn.name}($params): ${fn.returnType.jvmTypeName} {")

        // Allocate callback stubs in persistent arena (survives async calls)
        appendCallbackStubAlloc("        ", fn.params, "_callbackArena")

        val returnsDataClass = fn.returnType is KneType.DATA_CLASS
        val hasDataClassParams = fn.params.any { it.type is KneType.DATA_CLASS }
        val needsConfinedArena = needsConfinedArena(fn.params, fn.returnType) || returnsDataClass ||
            hasDataClassParams && fn.params.any { it.type is KneType.DATA_CLASS && it.type.fields.any { f -> f.type == KneType.STRING } }

        if (needsConfinedArena || returnsDataClass) {
            appendLine("        Arena.ofConfined().use { arena ->")
            appendStringInvokeArgsAlloc("            ", fn.params)
            if (returnsDataClass) {
                appendDataClassReturnProxy("            ", fn, handleName)
            } else {
                val invokeArgs = buildClassInvokeArgsExpanded(fn)
                appendCallAndReturn("            ", fn.returnType, handleName, invokeArgs)
            }
            appendLine("        }")
        } else {
            val invokeArgs = buildClassInvokeArgsExpandedDirect(fn)
            appendCallAndReturn("        ", fn.returnType, handleName, invokeArgs)
        }

        appendLine("    }")
        appendLine()
    }

    /** Generate the return-via-out-params pattern for DATA_CLASS return types. */
    private fun StringBuilder.appendDataClassReturnProxy(indent: String, fn: KneFunction, handleName: String) {
        val dc = fn.returnType as KneType.DATA_CLASS

        // Allocate out-params for each field
        dc.fields.forEach { f ->
            if (f.type == KneType.STRING) {
                appendLine("${indent}val out_${f.name} = arena.allocate($STRING_BUF_SIZE.toLong())")
            } else {
                appendLine("${indent}val out_${f.name} = arena.allocate(${f.type.ffmLayout})")
            }
        }

        // Build invoke args: handle + expanded params + out-params
        val paramArgs = buildList {
            add("handle")
            fn.params.forEach { p -> addAll(buildExpandedInvokeArgs(p)) }
            dc.fields.forEach { f ->
                if (f.type == KneType.STRING) {
                    add("out_${f.name}"); add("$STRING_BUF_SIZE")
                } else {
                    add("out_${f.name}")
                }
            }
        }.joinToString(", ")

        appendLine("${indent}$handleName.invoke($paramArgs)")
        appendLine("${indent}KneRuntime.checkError()")

        // Read fields and construct data class
        val ctorArgs = dc.fields.joinToString(", ") { f ->
            when (f.type) {
                KneType.STRING -> "${f.name} = out_${f.name}.getString(0)"
                KneType.BOOLEAN -> "${f.name} = out_${f.name}.get(JAVA_INT, 0) != 0"
                else -> "${f.name} = out_${f.name}.get(${f.type.ffmLayout}, 0) as ${f.type.jvmTypeName}"
            }
        }
        appendLine("${indent}return ${dc.simpleName}($ctorArgs)")
    }

    /** Build invoke args with DATA_CLASS params expanded into individual fields. */
    private fun buildClassInvokeArgsExpanded(fn: KneFunction): String {
        val args = buildList {
            add("handle")
            fn.params.forEach { p -> addAll(buildExpandedInvokeArgs(p)) }
            if (fn.returnType.returnsViaBuffer()) { add("buf"); add("$STRING_BUF_SIZE") }
        }
        return args.joinToString(", ")
    }

    private fun buildClassInvokeArgsExpandedDirect(fn: KneFunction): String {
        val args = buildList {
            add("handle")
            fn.params.forEach { p -> addAll(buildExpandedInvokeArgs(p)) }
        }
        return args.joinToString(", ")
    }

    /** Expand a single param into invoke args. DATA_CLASS becomes N args (one per field). */
    private fun buildExpandedInvokeArgs(p: KneParam): List<String> {
        if (p.type !is KneType.DATA_CLASS) return listOf(buildJvmInvokeArg(p.name, p.type))
        return p.type.fields.map { f ->
            when (f.type) {
                KneType.STRING -> "${p.name}_${f.name}Seg" // allocated in appendStringInvokeArgsAlloc
                KneType.BOOLEAN -> "if (${p.name}.${f.name}) 1 else 0"
                else -> "${p.name}.${f.name}"
            }
        }
    }

    private fun StringBuilder.appendPropertyProxy(prop: KneProperty, cls: KneClass) {
        val getHandleName = "GET_${prop.name.uppercase()}_HANDLE"
        if (prop.mutable) {
            appendLine("    var ${prop.name}: ${prop.type.jvmTypeName}")
        } else {
            appendLine("    val ${prop.name}: ${prop.type.jvmTypeName}")
        }
        appendLine("        get() {")
        val needsArena = prop.type.returnsViaBuffer()
        if (needsArena) {
            appendLine("            Arena.ofConfined().use { arena ->")
            appendLine("                val buf = arena.allocate($STRING_BUF_SIZE.toLong())")
            if (prop.type is KneType.NULLABLE) {
                appendLine("                val len = $getHandleName.invoke(handle, buf, $STRING_BUF_SIZE) as Int")
                appendLine("                KneRuntime.checkError()")
                appendLine("                return if (len < 0) null else buf.getString(0)")
            } else {
                appendLine("                $getHandleName.invoke(handle, buf, $STRING_BUF_SIZE)")
                appendLine("                KneRuntime.checkError()")
                appendLine("                return buf.getString(0)")
            }
            appendLine("            }")
        } else {
            appendCallAndReturn("            ", prop.type, getHandleName, "handle")
        }
        appendLine("        }")

        if (prop.mutable) {
            val setHandleName = "SET_${prop.name.uppercase()}_HANDLE"
            appendLine("        set(value) {")
            appendSetterInvoke("            ", setHandleName, prop.type, "handle")
            appendLine("        }")
        }
        appendLine()
    }

    // ── Companion method/property proxies ────────────────────────────────────

    private fun StringBuilder.appendCompanionMethodProxy(fn: KneFunction) {
        val handleName = "COMPANION_${fn.name.uppercase()}_HANDLE"
        val params = fn.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }

        appendLine()
        appendLine("        fun ${fn.name}($params): ${fn.returnType.jvmTypeName} {")

        appendCallbackStubAlloc("            ", fn.params, "_companionCallbackArena")

        val arenaNeeded = needsConfinedArena(fn.params, fn.returnType)
        if (arenaNeeded) {
            appendLine("            Arena.ofConfined().use { arena ->")
            appendStringInvokeArgsAlloc("                ", fn.params)
            val invokeArgs = buildTopLevelInvokeArgs(fn)
            appendCallAndReturn("                ", fn.returnType, handleName, invokeArgs)
            appendLine("            }")
        } else {
            val invokeArgs = fn.params.joinToString(", ") { p -> buildJvmInvokeArg(p.name, p.type) }
            appendCallAndReturn("            ", fn.returnType, handleName, invokeArgs)
        }

        appendLine("        }")
    }

    private fun StringBuilder.appendCompanionPropertyProxy(prop: KneProperty) {
        val getHandleName = "COMPANION_GET_${prop.name.uppercase()}_HANDLE"
        appendLine()
        if (prop.mutable) {
            appendLine("        var ${prop.name}: ${prop.type.jvmTypeName}")
        } else {
            appendLine("        val ${prop.name}: ${prop.type.jvmTypeName}")
        }
        appendLine("            get() {")
        val needsArena = prop.type.returnsViaBuffer()
        if (needsArena) {
            appendLine("                Arena.ofConfined().use { arena ->")
            appendLine("                    val buf = arena.allocate($STRING_BUF_SIZE.toLong())")
            if (prop.type is KneType.NULLABLE) {
                appendLine("                    val len = $getHandleName.invoke(buf, $STRING_BUF_SIZE) as Int")
                appendLine("                    KneRuntime.checkError()")
                appendLine("                    return if (len < 0) null else buf.getString(0)")
            } else {
                appendLine("                    $getHandleName.invoke(buf, $STRING_BUF_SIZE)")
                appendLine("                    KneRuntime.checkError()")
                appendLine("                    return buf.getString(0)")
            }
            appendLine("                }")
        } else {
            appendCallAndReturn("                ", prop.type, getHandleName, "")
        }
        appendLine("            }")

        if (prop.mutable) {
            val setHandleName = "COMPANION_SET_${prop.name.uppercase()}_HANDLE"
            appendLine("            set(value) {")
            appendSetterInvoke("                ", setHandleName, prop.type, null)
            appendLine("            }")
        }
    }

    // ── Data class file ───────────────────────────────────────────────────────

    private fun generateDataClassFile(dc: KneDataClass, pkg: String): String = buildString {
        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        val fields = dc.fields.joinToString(", ") { "val ${it.name}: ${it.type.jvmTypeName}" }
        appendLine("data class ${dc.simpleName}($fields)")
    }

    // ── Enum proxy ───────────────────────────────────────────────────────────

    private fun generateEnumProxy(enum: KneEnum, module: KneModule, pkg: String): String = buildString {
        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("enum class ${enum.simpleName} {")
        enum.entries.forEachIndexed { idx, entry ->
            val separator = if (idx < enum.entries.size - 1) "," else ";"
            appendLine("    $entry$separator")
        }
        appendLine("}")
    }

    // ── Top-level function object ────────────────────────────────────────────

    private fun generateFunctionObject(
        fns: List<KneFunction>,
        objectName: String,
        module: KneModule,
        pkg: String,
    ): String = buildString {
        val p = module.libName

        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("import java.lang.foreign.Arena")
        appendLine("import java.lang.foreign.FunctionDescriptor")
        appendLine("import java.lang.foreign.MemorySegment")
        appendLine("import java.lang.foreign.ValueLayout.*")
        appendLine("import java.lang.invoke.MethodHandle")
        appendLine()

        val objectHasCallbacks = fns.any { fn -> fn.params.any { it.type is KneType.FUNCTION } }

        appendLine("object $objectName {")
        if (objectHasCallbacks) {
            appendLine("    private val _callbackArena: Arena = Arena.ofShared()")
        }
        appendLine()

        fns.forEach { fn ->
            val handleName = "${fn.name.uppercase()}_HANDLE"
            val descriptor = buildTopLevelDescriptor(fn)
            appendLine("    private val $handleName: MethodHandle by lazy {")
            appendLine("        KneRuntime.handle(\"${p}_${fn.name}\", $descriptor)")
            appendLine("    }")
        }
        appendLine()

        fns.forEach { fn ->
            val handleName = "${fn.name.uppercase()}_HANDLE"
            val params = fn.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }
            appendLine("    fun ${fn.name}($params): ${fn.returnType.jvmTypeName} {")

            appendCallbackStubAlloc("        ", fn.params, "_callbackArena")

            val arenaNeeded = needsConfinedArena(fn.params, fn.returnType)
            if (arenaNeeded) {
                appendLine("        Arena.ofConfined().use { arena ->")
                appendStringInvokeArgsAlloc("            ", fn.params)
                val invokeArgs = buildTopLevelInvokeArgs(fn)
                appendCallAndReturn("            ", fn.returnType, handleName, invokeArgs)
                appendLine("        }")
            } else {
                val invokeArgs = fn.params.joinToString(", ") { fp ->
                    buildJvmInvokeArg(fp.name, fp.type)
                }
                appendCallAndReturn("        ", fn.returnType, handleName, invokeArgs)
            }

            appendLine("    }")
            appendLine()
        }

        appendLine("}")
    }

    // ── Descriptor builders ──────────────────────────────────────────────────

    private fun buildMethodDescriptor(fn: KneFunction): String {
        val paramLayouts = buildList {
            add("JAVA_LONG") // handle
            fn.params.forEach { p ->
                if (p.type is KneType.DATA_CLASS) {
                    p.type.fields.forEach { f -> add(f.type.ffmLayout) }
                } else {
                    add(p.type.ffmLayout)
                }
            }
            if (fn.returnType.returnsViaBuffer()) {
                add("ADDRESS"); add("JAVA_INT")
            }
            if (fn.returnType is KneType.DATA_CLASS) {
                (fn.returnType as KneType.DATA_CLASS).fields.forEach { f ->
                    if (f.type == KneType.STRING) {
                        add("ADDRESS"); add("JAVA_INT")
                    } else {
                        add("ADDRESS")
                    }
                }
            }
        }
        val effectiveReturn = if (fn.returnType is KneType.DATA_CLASS) KneType.UNIT else fn.returnType
        return buildDescriptor(effectiveReturn, paramLayouts)
    }

    private fun buildGetterDescriptor(prop: KneProperty): String {
        val paramLayouts = buildList {
            add("JAVA_LONG")
            if (prop.type.returnsViaBuffer()) {
                add("ADDRESS"); add("JAVA_INT")
            }
        }
        return buildDescriptor(prop.type, paramLayouts)
    }

    private fun buildCompanionGetterDescriptor(prop: KneProperty): String {
        val paramLayouts = buildList {
            if (prop.type.returnsViaBuffer()) {
                add("ADDRESS"); add("JAVA_INT")
            }
        }
        return buildDescriptor(prop.type, paramLayouts)
    }

    private fun buildTopLevelDescriptor(fn: KneFunction): String {
        val paramLayouts = buildList {
            fn.params.forEach { p -> add(p.type.ffmLayout) }
            if (fn.returnType.returnsViaBuffer()) {
                add("ADDRESS"); add("JAVA_INT")
            }
        }
        return buildDescriptor(fn.returnType, paramLayouts)
    }

    private fun buildDescriptor(returnType: KneType, paramLayouts: List<String>): String {
        val params = paramLayouts.filter { it.isNotEmpty() }.joinToString(", ")
        return if (returnType == KneType.UNIT || returnType.returnsViaBuffer()) {
            val retLayout = if (returnType.returnsViaBuffer()) "JAVA_INT" else ""
            if (retLayout.isEmpty()) "FunctionDescriptor.ofVoid($params)"
            else "FunctionDescriptor.of($retLayout${if (params.isNotEmpty()) ", $params" else ""})"
        } else {
            "FunctionDescriptor.of(${returnType.ffmLayout}${if (params.isNotEmpty()) ", $params" else ""})"
        }
    }

    private fun buildLayouts(types: List<KneType>): String =
        types.filter { it.ffmLayout.isNotEmpty() }.joinToString("") { ", ${it.ffmLayout}" }

    // ── Invoke arg builders ──────────────────────────────────────────────────

    private fun buildJvmInvokeArg(name: String, type: KneType): String = when (type) {
        KneType.STRING -> "${name}Seg"
        KneType.BOOLEAN -> "if ($name) 1 else 0"
        is KneType.OBJECT -> "$name.handle"
        is KneType.ENUM -> "$name.ordinal"
        is KneType.NULLABLE -> buildNullableJvmInvokeArg(name, type)
        is KneType.FUNCTION -> "${name}Stub"
        else -> name
    }

    private fun buildNullableJvmInvokeArg(name: String, type: KneType.NULLABLE): String = when (type.inner) {
        KneType.STRING -> "${name}Seg"
        KneType.BOOLEAN -> "if ($name == null) -1 else if ($name) 1 else 0"
        KneType.INT -> "$name?.toLong() ?: Long.MIN_VALUE"
        KneType.LONG -> "$name ?: Long.MIN_VALUE"
        KneType.SHORT -> "$name?.toInt() ?: Int.MIN_VALUE"
        KneType.BYTE -> "$name?.toInt() ?: Int.MIN_VALUE"
        KneType.FLOAT -> "if ($name != null) $name.toRawBits().toLong() else Long.MIN_VALUE"
        KneType.DOUBLE -> "if ($name != null) $name.toRawBits() else Long.MIN_VALUE"
        is KneType.OBJECT -> "$name?.handle ?: 0L"
        is KneType.ENUM -> "$name?.ordinal ?: -1"
        else -> name
    }

    private fun buildCtorInvokeArgs(params: List<KneParam>): String {
        if (params.isEmpty()) return ""
        return params.joinToString(", ") { p -> buildJvmInvokeArg(p.name, p.type) }
    }

    private fun buildClassInvokeArgs(fn: KneFunction): String {
        val args = buildList {
            add("handle")
            fn.params.forEach { p -> add(buildJvmInvokeArg(p.name, p.type)) }
            if (fn.returnType.returnsViaBuffer()) { add("buf"); add("$STRING_BUF_SIZE") }
        }
        return args.joinToString(", ")
    }

    private fun buildClassInvokeArgsDirect(fn: KneFunction): String {
        val args = buildList {
            add("handle")
            fn.params.forEach { p -> add(buildJvmInvokeArg(p.name, p.type)) }
        }
        return args.joinToString(", ")
    }

    private fun buildTopLevelInvokeArgs(fn: KneFunction): String {
        val args = buildList {
            fn.params.forEach { p -> add(buildJvmInvokeArg(p.name, p.type)) }
            if (fn.returnType.returnsViaBuffer()) { add("buf"); add("$STRING_BUF_SIZE") }
        }
        return args.joinToString(", ")
    }

    // ── Code emission helpers ────────────────────────────────────────────────

    private fun StringBuilder.appendStringInvokeArgsAlloc(indent: String, params: List<KneParam>) {
        params.filter { it.type == KneType.STRING }.forEach { p ->
            appendLine("${indent}val ${p.name}Seg = arena.allocateFrom(${p.name})")
        }
        params.filter { it.type is KneType.NULLABLE && (it.type as KneType.NULLABLE).inner == KneType.STRING }.forEach { p ->
            appendLine("${indent}val ${p.name}Seg = if (${p.name} != null) arena.allocateFrom(${p.name}) else MemorySegment.NULL")
        }
        // Allocate String fields from data class params
        params.filter { it.type is KneType.DATA_CLASS }.forEach { p ->
            (p.type as KneType.DATA_CLASS).fields.filter { it.type == KneType.STRING }.forEach { f ->
                appendLine("${indent}val ${p.name}_${f.name}Seg = arena.allocateFrom(${p.name}.${f.name})")
            }
        }
    }

    /** Emit callback stub allocation using the persistent arena. */
    private fun StringBuilder.appendCallbackStubAlloc(indent: String, params: List<KneParam>, arenaExpr: String) {
        params.filter { it.type is KneType.FUNCTION }.forEach { p ->
            val fnType = p.type as KneType.FUNCTION
            val id = callbackId(fnType)
            appendLine("${indent}val ${p.name}Stub = KneRuntime.createUpcallStub_$id(${p.name}, $arenaExpr)")
        }
    }

    /**
     * Emits a handle invocation with checkError() after the call.
     * For value-returning functions, stores result in a local var, checks error, then returns.
     */
    private fun StringBuilder.appendCallAndReturn(
        indent: String,
        returnType: KneType,
        handleName: String,
        invokeArgs: String,
    ) {
        when (returnType) {
            KneType.UNIT -> {
                appendLine("${indent}$handleName.invoke($invokeArgs)")
                appendLine("${indent}KneRuntime.checkError()")
            }
            KneType.STRING -> {
                appendLine("${indent}val buf = arena.allocate($STRING_BUF_SIZE.toLong())")
                appendLine("${indent}$handleName.invoke($invokeArgs)")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return buf.getString(0)")
            }
            KneType.BOOLEAN -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r != 0")
            }
            KneType.INT -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            KneType.LONG -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            KneType.DOUBLE -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Double")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            KneType.FLOAT -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Float")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            KneType.BYTE -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Byte")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            KneType.SHORT -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Short")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            is KneType.OBJECT -> {
                appendLine("${indent}val resultHandle = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return ${returnType.simpleName}.fromNativeHandle(resultHandle)")
            }
            is KneType.ENUM -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return ${returnType.simpleName}.entries[_r]")
            }
            is KneType.NULLABLE -> appendNullableCallAndReturn(indent, returnType, handleName, invokeArgs)
            is KneType.FUNCTION -> {
                appendLine("${indent}$handleName.invoke($invokeArgs)")
                appendLine("${indent}KneRuntime.checkError()")
            }
            is KneType.DATA_CLASS -> {
                // DATA_CLASS returns are handled separately in appendMethodProxy
                appendLine("${indent}$handleName.invoke($invokeArgs)")
                appendLine("${indent}KneRuntime.checkError()")
            }
        }
    }

    private fun StringBuilder.appendNullableCallAndReturn(
        indent: String,
        type: KneType.NULLABLE,
        handleName: String,
        invokeArgs: String,
    ) {
        when (type.inner) {
            KneType.STRING -> {
                appendLine("${indent}val buf = arena.allocate($STRING_BUF_SIZE.toLong())")
                appendLine("${indent}val len = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (len < 0) null else buf.getString(0)")
            }
            KneType.BOOLEAN -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw < 0) null else raw != 0")
            }
            KneType.INT -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Long.MIN_VALUE) null else raw.toInt()")
            }
            KneType.LONG -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Long.MIN_VALUE) null else raw")
            }
            KneType.SHORT -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Int.MIN_VALUE) null else raw.toShort()")
            }
            KneType.BYTE -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Int.MIN_VALUE) null else raw.toByte()")
            }
            KneType.FLOAT -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Long.MIN_VALUE) null else Float.fromBits(raw.toInt())")
            }
            KneType.DOUBLE -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Long.MIN_VALUE) null else Double.fromBits(raw)")
            }
            is KneType.OBJECT -> {
                appendLine("${indent}val resultHandle = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (resultHandle == 0L) null else ${type.inner.simpleName}.fromNativeHandle(resultHandle)")
            }
            is KneType.ENUM -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw < 0) null else ${type.inner.simpleName}.entries[raw]")
            }
            KneType.UNIT -> {
                appendLine("${indent}$handleName.invoke($invokeArgs)")
                appendLine("${indent}KneRuntime.checkError()")
            }
            else -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs)")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
        }
    }

    private fun StringBuilder.appendSetterInvoke(indent: String, handleName: String, type: KneType, handleArg: String?) {
        val prefix = if (handleArg != null) "$handleArg, " else ""
        when (type) {
            KneType.STRING -> {
                appendLine("${indent}Arena.ofConfined().use { arena ->")
                appendLine("${indent}    val valueSeg = arena.allocateFrom(value)")
                appendLine("${indent}    $handleName.invoke(${prefix}valueSeg)")
                appendLine("${indent}    KneRuntime.checkError()")
                appendLine("${indent}}")
            }
            KneType.BOOLEAN -> {
                appendLine("${indent}$handleName.invoke(${prefix}if (value) 1 else 0)")
                appendLine("${indent}KneRuntime.checkError()")
            }
            is KneType.OBJECT -> {
                appendLine("${indent}$handleName.invoke(${prefix}value.handle)")
                appendLine("${indent}KneRuntime.checkError()")
            }
            is KneType.ENUM -> {
                appendLine("${indent}$handleName.invoke(${prefix}value.ordinal)")
                appendLine("${indent}KneRuntime.checkError()")
            }
            is KneType.NULLABLE -> appendNullableSetterInvoke(indent, handleName, type, handleArg)
            else -> {
                appendLine("${indent}$handleName.invoke(${prefix}value)")
                appendLine("${indent}KneRuntime.checkError()")
            }
        }
    }

    private fun StringBuilder.appendNullableSetterInvoke(indent: String, handleName: String, type: KneType.NULLABLE, handleArg: String?) {
        val prefix = if (handleArg != null) "$handleArg, " else ""
        when (type.inner) {
            KneType.STRING -> {
                appendLine("${indent}Arena.ofConfined().use { arena ->")
                appendLine("${indent}    val valueSeg = if (value != null) arena.allocateFrom(value) else MemorySegment.NULL")
                appendLine("${indent}    $handleName.invoke(${prefix}valueSeg)")
                appendLine("${indent}    KneRuntime.checkError()")
                appendLine("${indent}}")
            }
            else -> {
                val valueExpr = when (type.inner) {
                    KneType.BOOLEAN -> "if (value == null) -1 else if (value) 1 else 0"
                    KneType.INT -> "value?.toLong() ?: Long.MIN_VALUE"
                    KneType.LONG -> "value ?: Long.MIN_VALUE"
                    KneType.SHORT -> "value?.toInt() ?: Int.MIN_VALUE"
                    KneType.BYTE -> "value?.toInt() ?: Int.MIN_VALUE"
                    KneType.FLOAT -> "if (value != null) value.toRawBits().toLong() else Long.MIN_VALUE"
                    KneType.DOUBLE -> "if (value != null) value.toRawBits() else Long.MIN_VALUE"
                    is KneType.OBJECT -> "value?.handle ?: 0L"
                    is KneType.ENUM -> "value?.ordinal ?: -1"
                    else -> "value"
                }
                appendLine("${indent}$handleName.invoke(${prefix}$valueExpr)")
                appendLine("${indent}KneRuntime.checkError()")
            }
        }
    }
}
