package io.github.kdroidfilter.kotlinnativeexport.plugin.codegen

import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneClass
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneEnum
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneFunction
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneModule
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneParam
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneProperty
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneType

/**
 * Generates Kotlin/JVM FFM proxy code.
 *
 * Inspired by swift-java's FFMSwift2JavaGenerator:
 *  - Each exported symbol gets a descriptor class with FunctionDescriptor + MethodHandle
 *    (mirroring swift-java's inner descriptor classes per method).
 *  - Object lifecycle uses Java Cleaner + a captured Long handle
 *    (mirrors swift-java's AllocatingSwiftArena + swift_retain/swift_release pattern).
 *  - String I/O uses the output-buffer pattern (Arena.allocate + get/set ADDRESS).
 *  - Exception propagation: every downcall is followed by KneRuntime.checkError()
 *    which queries the native @ThreadLocal error state.
 *
 * Generated classes have the exact same API as the native Kotlin classes,
 * making the bridge fully transparent to the JVM developer.
 */
class FfmProxyGenerator {

    companion object {
        private const val STRING_BUF_SIZE = 8192
        private const val ERR_BUF_SIZE = 8192
    }

    private fun KneType.returnsViaBuffer(): Boolean =
        this == KneType.STRING || (this is KneType.NULLABLE && inner == KneType.STRING)

    private fun KneType.isStringLike(): Boolean =
        this == KneType.STRING || (this is KneType.NULLABLE && inner == KneType.STRING)

    /**
     * Generates all proxy files for the module.
     * Returns a map of filename → file content.
     */
    fun generate(module: KneModule, jvmPackage: String): Map<String, String> {
        val files = mutableMapOf<String, String>()

        files["KneRuntime.kt"] = generateRuntime(module.libName, jvmPackage)
        files["KotlinNativeException.kt"] = generateException(jvmPackage)

        module.classes.forEach { cls ->
            files["${cls.simpleName}.kt"] = generateClassProxy(cls, module, jvmPackage)
        }

        module.enums.forEach { enum ->
            files["${enum.simpleName}.kt"] = generateEnumProxy(enum, module, jvmPackage)
        }

        if (module.functions.isNotEmpty()) {
            val objectName = module.libName.replaceFirstChar { it.uppercaseChar() }
            files["$objectName.kt"] = generateFunctionObject(module.functions, objectName, module, jvmPackage)
        }

        return files
    }

    // ── Runtime helper ────────────────────────────────────────────────────────

    private fun generateRuntime(libName: String, pkg: String): String = buildString {
        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("import java.lang.foreign.Arena")
        appendLine("import java.lang.foreign.FunctionDescriptor")
        appendLine("import java.lang.foreign.Linker")
        appendLine("import java.lang.foreign.SymbolLookup")
        appendLine("import java.lang.foreign.ValueLayout.*")
        appendLine("import java.lang.invoke.MethodHandle")
        appendLine("import java.nio.file.Paths")
        appendLine()
        appendLine("/**")
        appendLine(" * Shared FFM runtime: loads the native library, resolves MethodHandles,")
        appendLine(" * and propagates exceptions from the native side.")
        appendLine(" */")
        appendLine("internal object KneRuntime {")
        appendLine()
        appendLine("    val linker: Linker = Linker.nativeLinker()")
        appendLine("    private val globalArena: Arena = Arena.global()")
        appendLine()
        appendLine("    val library: SymbolLookup by lazy { loadLibrary(\"$libName\") }")
        appendLine()
        appendLine("    private fun loadLibrary(name: String): SymbolLookup {")
        appendLine("        val fileName = System.mapLibraryName(name)")
        appendLine("        val sep = if (System.getProperty(\"os.name\").lowercase().contains(\"win\")) \";\" else \":\"")
        appendLine("        val basePaths = System.getProperty(\"java.library.path\", \"\").split(sep)")
        appendLine("        val extraDirs = mutableListOf(System.getProperty(\"user.dir\", \".\"))")
        appendLine("        try {")
        appendLine("            ProcessHandle.current().info().command().ifPresent { cmd ->")
        appendLine("                Paths.get(cmd).parent?.toString()?.let { extraDirs.add(it) }")
        appendLine("            }")
        appendLine("        } catch (_: Exception) {}")
        appendLine("        val allBases = (basePaths + extraDirs).distinct().filter { it.isNotBlank() }")
        appendLine("        val paths = allBases + allBases.map { Paths.get(it, \"lib\").toString() }")
        appendLine("        for (dir in paths) {")
        appendLine("            val file = Paths.get(dir, fileName).toFile()")
        appendLine("            if (file.exists()) return SymbolLookup.libraryLookup(file.toPath(), globalArena)")
        appendLine("        }")
        appendLine("        return SymbolLookup.loaderLookup()")
        appendLine("    }")
        appendLine()
        appendLine("    fun handle(symbol: String, descriptor: FunctionDescriptor): MethodHandle =")
        appendLine("        linker.downcallHandle(")
        appendLine("            library.find(symbol).orElseThrow { UnsatisfiedLinkError(\"Symbol not found: \$symbol\") },")
        appendLine("            descriptor,")
        appendLine("        )")
        appendLine()
        appendLine("    // ── Exception propagation ────────────────────────────────────────────")
        appendLine()
        appendLine("    private val HAS_ERROR_HANDLE: MethodHandle by lazy {")
        appendLine("        handle(\"${libName}_kne_hasError\", FunctionDescriptor.of(JAVA_INT))")
        appendLine("    }")
        appendLine("    private val GET_LAST_ERROR_HANDLE: MethodHandle by lazy {")
        appendLine("        handle(\"${libName}_kne_getLastError\", FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT))")
        appendLine("    }")
        appendLine()
        appendLine("    fun checkError() {")
        appendLine("        val hasError = HAS_ERROR_HANDLE.invoke() as Int")
        appendLine("        if (hasError != 0) {")
        appendLine("            Arena.ofConfined().use { arena ->")
        appendLine("                val buf = arena.allocate($ERR_BUF_SIZE.toLong())")
        appendLine("                GET_LAST_ERROR_HANDLE.invoke(buf, $ERR_BUF_SIZE)")
        appendLine("                throw KotlinNativeException(buf.getString(0))")
        appendLine("            }")
        appendLine("        }")
        appendLine("    }")
        appendLine("}")
    }

    // ── Exception class ──────────────────────────────────────────────────────

    private fun generateException(pkg: String): String = buildString {
        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("/**")
        appendLine(" * Exception thrown when a Kotlin/Native function throws across the FFM boundary.")
        appendLine(" * The message contains the original Kotlin exception's message.")
        appendLine(" */")
        appendLine("class KotlinNativeException(message: String) : RuntimeException(message)")
    }

    // ── Class proxy ──────────────────────────────────────────────────────────

    private fun generateClassProxy(cls: KneClass, module: KneModule, pkg: String): String = buildString {
        val p = module.libName
        val n = cls.simpleName

        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("import java.lang.foreign.Arena")
        appendLine("import java.lang.foreign.FunctionDescriptor")
        appendLine("import java.lang.foreign.MemorySegment")
        appendLine("import java.lang.foreign.ValueLayout.*")
        appendLine("import java.lang.invoke.MethodHandle")
        appendLine("import java.lang.ref.Cleaner")
        appendLine()

        appendLine("/**")
        appendLine(" * JVM proxy for Kotlin/Native class [$n].")
        appendLine(" * Uses FFM MethodHandles to dispatch every call to the native shared library.")
        appendLine(" * Object lifecycle is managed via Java Cleaner (automatic GC) or explicit close().")
        appendLine(" */")
        appendLine("class $n private constructor(internal val handle: Long) : AutoCloseable {")
        appendLine()

        // Companion: MethodHandles + factory
        appendLine("    companion object {")
        appendLine("        private val CLEANER = Cleaner.create()")
        appendLine()

        val ctorLayouts = buildLayouts(cls.constructor.params.map { it.type })
        appendLine("        private val NEW_HANDLE: MethodHandle by lazy {")
        appendLine("            KneRuntime.handle(\"${p}_${n}_new\",")
        appendLine("                FunctionDescriptor.of(JAVA_LONG$ctorLayouts))")
        appendLine("        }")
        appendLine("        private val DISPOSE_HANDLE: MethodHandle by lazy {")
        appendLine("            KneRuntime.handle(\"${p}_${n}_dispose\",")
        appendLine("                FunctionDescriptor.ofVoid(JAVA_LONG))")
        appendLine("        }")

        cls.methods.forEach { method ->
            val handleName = "${method.name.uppercase()}_HANDLE"
            val descriptor = buildMethodDescriptor(method)
            appendLine("        private val $handleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_${method.name}\",")
            appendLine("                $descriptor)")
            appendLine("        }")
        }

        cls.properties.forEach { prop ->
            val getHandleName = "GET_${prop.name.uppercase()}_HANDLE"
            val getDescriptor = buildGetterDescriptor(prop)
            appendLine("        private val $getHandleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_get_${prop.name}\",")
            appendLine("                $getDescriptor)")
            appendLine("        }")
            if (prop.mutable) {
                val setHandleName = "SET_${prop.name.uppercase()}_HANDLE"
                val setLayouts = buildLayouts(listOf(prop.type))
                appendLine("        private val $setHandleName: MethodHandle by lazy {")
                appendLine("            KneRuntime.handle(\"${p}_${n}_set_${prop.name}\",")
                appendLine("                FunctionDescriptor.ofVoid(JAVA_LONG$setLayouts))")
                appendLine("        }")
            }
        }

        cls.companionMethods.forEach { method ->
            val handleName = "COMPANION_${method.name.uppercase()}_HANDLE"
            val descriptor = buildTopLevelDescriptor(method)
            appendLine("        private val $handleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_companion_${method.name}\",")
            appendLine("                $descriptor)")
            appendLine("        }")
        }
        cls.companionProperties.forEach { prop ->
            val getHandleName = "COMPANION_GET_${prop.name.uppercase()}_HANDLE"
            val getDescriptor = buildCompanionGetterDescriptor(prop)
            appendLine("        private val $getHandleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_companion_get_${prop.name}\",")
            appendLine("                $getDescriptor)")
            appendLine("        }")
            if (prop.mutable) {
                val setHandleName = "COMPANION_SET_${prop.name.uppercase()}_HANDLE"
                appendLine("        private val $setHandleName: MethodHandle by lazy {")
                appendLine("            KneRuntime.handle(\"${p}_${n}_companion_set_${prop.name}\",")
                appendLine("                FunctionDescriptor.ofVoid(${prop.type.ffmLayout}))")
                appendLine("        }")
            }
        }

        // Factory
        val ctorParams = cls.constructor.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }
        appendLine()
        appendLine("        /**")
        appendLine("         * Creates a new [$n] backed by a Kotlin/Native object.")
        appendLine("         * The native object is automatically released when GC'd or close() is called.")
        appendLine("         */")
        appendLine("        operator fun invoke($ctorParams): $n {")
        if (cls.constructor.params.any { it.type.isStringLike() }) {
            appendLine("            Arena.ofConfined().use { arena ->")
            appendStringInvokeArgsAlloc("                ", cls.constructor.params)
            val ctorInvokeArgs = buildCtorInvokeArgs(cls.constructor.params)
            appendLine("                val h = NEW_HANDLE.invoke($ctorInvokeArgs) as Long")
            appendLine("                KneRuntime.checkError()")
            appendLine("                return fromNativeHandle(h)")
            appendLine("            }")
        } else {
            val ctorInvokeArgs = buildCtorInvokeArgs(cls.constructor.params)
            appendLine("            val h = NEW_HANDLE.invoke($ctorInvokeArgs) as Long")
            appendLine("            KneRuntime.checkError()")
            appendLine("            return fromNativeHandle(h)")
        }
        appendLine("        }")
        appendLine()

        appendLine("        internal fun fromNativeHandle(h: Long): $n {")
        appendLine("            val obj = $n(h)")
        appendLine("            CLEANER.register(obj) { runCatching { DISPOSE_HANDLE.invoke(h) } }")
        appendLine("            return obj")
        appendLine("        }")

        // Companion methods
        cls.companionMethods.forEach { method -> appendCompanionMethodProxy(method) }
        cls.companionProperties.forEach { prop -> appendCompanionPropertyProxy(prop) }

        appendLine("    }")
        appendLine()

        // Methods
        cls.methods.forEach { method -> appendMethodProxy(method, cls, p) }
        cls.properties.forEach { prop -> appendPropertyProxy(prop, cls) }

        // close()
        appendLine("    override fun close() {")
        appendLine("        runCatching { DISPOSE_HANDLE.invoke(handle) }")
        appendLine("    }")
        appendLine("}")
    }

    private fun StringBuilder.appendMethodProxy(fn: KneFunction, cls: KneClass, prefix: String) {
        val handleName = "${fn.name.uppercase()}_HANDLE"
        val params = fn.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }

        appendLine("    fun ${fn.name}($params): ${fn.returnType.jvmTypeName} {")

        val needsArena = fn.params.any { it.type.isStringLike() } || fn.returnType.isStringLike()
        if (needsArena) {
            appendLine("        Arena.ofConfined().use { arena ->")
            appendStringInvokeArgsAlloc("            ", fn.params)
            val invokeArgs = buildClassInvokeArgs(fn)
            appendCallAndReturn("            ", fn.returnType, handleName, invokeArgs)
            appendLine("        }")
        } else {
            val invokeArgs = buildClassInvokeArgsDirect(fn)
            appendCallAndReturn("        ", fn.returnType, handleName, invokeArgs)
        }

        appendLine("    }")
        appendLine()
    }

    private fun StringBuilder.appendPropertyProxy(prop: KneProperty, cls: KneClass) {
        val getHandleName = "GET_${prop.name.uppercase()}_HANDLE"
        if (prop.mutable) {
            appendLine("    var ${prop.name}: ${prop.type.jvmTypeName}")
        } else {
            appendLine("    val ${prop.name}: ${prop.type.jvmTypeName}")
        }
        appendLine("        get() {")
        val needsArena = prop.type.returnsViaBuffer()
        if (needsArena) {
            appendLine("            Arena.ofConfined().use { arena ->")
            appendLine("                val buf = arena.allocate($STRING_BUF_SIZE.toLong())")
            if (prop.type is KneType.NULLABLE) {
                appendLine("                val len = $getHandleName.invoke(handle, buf, $STRING_BUF_SIZE) as Int")
                appendLine("                KneRuntime.checkError()")
                appendLine("                return if (len < 0) null else buf.getString(0)")
            } else {
                appendLine("                $getHandleName.invoke(handle, buf, $STRING_BUF_SIZE)")
                appendLine("                KneRuntime.checkError()")
                appendLine("                return buf.getString(0)")
            }
            appendLine("            }")
        } else {
            appendCallAndReturn("            ", prop.type, getHandleName, "handle")
        }
        appendLine("        }")

        if (prop.mutable) {
            val setHandleName = "SET_${prop.name.uppercase()}_HANDLE"
            appendLine("        set(value) {")
            appendSetterInvoke("            ", setHandleName, prop.type, "handle")
            appendLine("        }")
        }
        appendLine()
    }

    // ── Companion method/property proxies ────────────────────────────────────

    private fun StringBuilder.appendCompanionMethodProxy(fn: KneFunction) {
        val handleName = "COMPANION_${fn.name.uppercase()}_HANDLE"
        val params = fn.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }

        appendLine()
        appendLine("        fun ${fn.name}($params): ${fn.returnType.jvmTypeName} {")

        val needsArena = fn.params.any { it.type.isStringLike() } || fn.returnType.isStringLike()
        if (needsArena) {
            appendLine("            Arena.ofConfined().use { arena ->")
            appendStringInvokeArgsAlloc("                ", fn.params)
            val invokeArgs = buildTopLevelInvokeArgs(fn)
            appendCallAndReturn("                ", fn.returnType, handleName, invokeArgs)
            appendLine("            }")
        } else {
            val invokeArgs = fn.params.joinToString(", ") { p -> buildJvmInvokeArg(p.name, p.type) }
            appendCallAndReturn("            ", fn.returnType, handleName, invokeArgs)
        }

        appendLine("        }")
    }

    private fun StringBuilder.appendCompanionPropertyProxy(prop: KneProperty) {
        val getHandleName = "COMPANION_GET_${prop.name.uppercase()}_HANDLE"
        appendLine()
        if (prop.mutable) {
            appendLine("        var ${prop.name}: ${prop.type.jvmTypeName}")
        } else {
            appendLine("        val ${prop.name}: ${prop.type.jvmTypeName}")
        }
        appendLine("            get() {")
        val needsArena = prop.type.returnsViaBuffer()
        if (needsArena) {
            appendLine("                Arena.ofConfined().use { arena ->")
            appendLine("                    val buf = arena.allocate($STRING_BUF_SIZE.toLong())")
            if (prop.type is KneType.NULLABLE) {
                appendLine("                    val len = $getHandleName.invoke(buf, $STRING_BUF_SIZE) as Int")
                appendLine("                    KneRuntime.checkError()")
                appendLine("                    return if (len < 0) null else buf.getString(0)")
            } else {
                appendLine("                    $getHandleName.invoke(buf, $STRING_BUF_SIZE)")
                appendLine("                    KneRuntime.checkError()")
                appendLine("                    return buf.getString(0)")
            }
            appendLine("                }")
        } else {
            appendCallAndReturn("                ", prop.type, getHandleName, "")
        }
        appendLine("            }")

        if (prop.mutable) {
            val setHandleName = "COMPANION_SET_${prop.name.uppercase()}_HANDLE"
            appendLine("            set(value) {")
            appendSetterInvoke("                ", setHandleName, prop.type, null)
            appendLine("            }")
        }
    }

    // ── Enum proxy ───────────────────────────────────────────────────────────

    private fun generateEnumProxy(enum: KneEnum, module: KneModule, pkg: String): String = buildString {
        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("enum class ${enum.simpleName} {")
        enum.entries.forEachIndexed { idx, entry ->
            val separator = if (idx < enum.entries.size - 1) "," else ";"
            appendLine("    $entry$separator")
        }
        appendLine("}")
    }

    // ── Top-level function object ────────────────────────────────────────────

    private fun generateFunctionObject(
        fns: List<KneFunction>,
        objectName: String,
        module: KneModule,
        pkg: String,
    ): String = buildString {
        val p = module.libName

        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("import java.lang.foreign.Arena")
        appendLine("import java.lang.foreign.FunctionDescriptor")
        appendLine("import java.lang.foreign.MemorySegment")
        appendLine("import java.lang.foreign.ValueLayout.*")
        appendLine("import java.lang.invoke.MethodHandle")
        appendLine()

        appendLine("object $objectName {")
        appendLine()

        fns.forEach { fn ->
            val handleName = "${fn.name.uppercase()}_HANDLE"
            val descriptor = buildTopLevelDescriptor(fn)
            appendLine("    private val $handleName: MethodHandle by lazy {")
            appendLine("        KneRuntime.handle(\"${p}_${fn.name}\", $descriptor)")
            appendLine("    }")
        }
        appendLine()

        fns.forEach { fn ->
            val handleName = "${fn.name.uppercase()}_HANDLE"
            val params = fn.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }
            appendLine("    fun ${fn.name}($params): ${fn.returnType.jvmTypeName} {")

            val needsArena = fn.params.any { it.type.isStringLike() } || fn.returnType.isStringLike()
            if (needsArena) {
                appendLine("        Arena.ofConfined().use { arena ->")
                appendStringInvokeArgsAlloc("            ", fn.params)
                val invokeArgs = buildTopLevelInvokeArgs(fn)
                appendCallAndReturn("            ", fn.returnType, handleName, invokeArgs)
                appendLine("        }")
            } else {
                val invokeArgs = fn.params.joinToString(", ") { fp ->
                    buildJvmInvokeArg(fp.name, fp.type)
                }
                appendCallAndReturn("        ", fn.returnType, handleName, invokeArgs)
            }

            appendLine("    }")
            appendLine()
        }

        appendLine("}")
    }

    // ── Descriptor builders ──────────────────────────────────────────────────

    private fun buildMethodDescriptor(fn: KneFunction): String {
        val paramLayouts = buildList {
            add("JAVA_LONG") // handle
            fn.params.forEach { p -> add(p.type.ffmLayout) }
            if (fn.returnType.returnsViaBuffer()) {
                add("ADDRESS"); add("JAVA_INT")
            }
        }
        return buildDescriptor(fn.returnType, paramLayouts)
    }

    private fun buildGetterDescriptor(prop: KneProperty): String {
        val paramLayouts = buildList {
            add("JAVA_LONG")
            if (prop.type.returnsViaBuffer()) {
                add("ADDRESS"); add("JAVA_INT")
            }
        }
        return buildDescriptor(prop.type, paramLayouts)
    }

    private fun buildCompanionGetterDescriptor(prop: KneProperty): String {
        val paramLayouts = buildList {
            if (prop.type.returnsViaBuffer()) {
                add("ADDRESS"); add("JAVA_INT")
            }
        }
        return buildDescriptor(prop.type, paramLayouts)
    }

    private fun buildTopLevelDescriptor(fn: KneFunction): String {
        val paramLayouts = buildList {
            fn.params.forEach { p -> add(p.type.ffmLayout) }
            if (fn.returnType.returnsViaBuffer()) {
                add("ADDRESS"); add("JAVA_INT")
            }
        }
        return buildDescriptor(fn.returnType, paramLayouts)
    }

    private fun buildDescriptor(returnType: KneType, paramLayouts: List<String>): String {
        val params = paramLayouts.filter { it.isNotEmpty() }.joinToString(", ")
        return if (returnType == KneType.UNIT || returnType.returnsViaBuffer()) {
            val retLayout = if (returnType.returnsViaBuffer()) "JAVA_INT" else ""
            if (retLayout.isEmpty()) "FunctionDescriptor.ofVoid($params)"
            else "FunctionDescriptor.of($retLayout${if (params.isNotEmpty()) ", $params" else ""})"
        } else {
            "FunctionDescriptor.of(${returnType.ffmLayout}${if (params.isNotEmpty()) ", $params" else ""})"
        }
    }

    private fun buildLayouts(types: List<KneType>): String =
        types.filter { it.ffmLayout.isNotEmpty() }.joinToString("") { ", ${it.ffmLayout}" }

    // ── Invoke arg builders ──────────────────────────────────────────────────

    private fun buildJvmInvokeArg(name: String, type: KneType): String = when (type) {
        KneType.STRING -> "${name}Seg"
        KneType.BOOLEAN -> "if ($name) 1 else 0"
        is KneType.OBJECT -> "$name.handle"
        is KneType.ENUM -> "$name.ordinal"
        is KneType.NULLABLE -> buildNullableJvmInvokeArg(name, type)
        else -> name
    }

    private fun buildNullableJvmInvokeArg(name: String, type: KneType.NULLABLE): String = when (type.inner) {
        KneType.STRING -> "${name}Seg"
        KneType.BOOLEAN -> "if ($name == null) -1 else if ($name) 1 else 0"
        KneType.INT -> "$name?.toLong() ?: Long.MIN_VALUE"
        KneType.LONG -> "$name ?: Long.MIN_VALUE"
        KneType.SHORT -> "$name?.toInt() ?: Int.MIN_VALUE"
        KneType.BYTE -> "$name?.toInt() ?: Int.MIN_VALUE"
        KneType.FLOAT -> "if ($name != null) $name.toRawBits().toLong() else Long.MIN_VALUE"
        KneType.DOUBLE -> "if ($name != null) $name.toRawBits() else Long.MIN_VALUE"
        is KneType.OBJECT -> "$name?.handle ?: 0L"
        is KneType.ENUM -> "$name?.ordinal ?: -1"
        else -> name
    }

    private fun buildCtorInvokeArgs(params: List<KneParam>): String {
        if (params.isEmpty()) return ""
        return params.joinToString(", ") { p -> buildJvmInvokeArg(p.name, p.type) }
    }

    private fun buildClassInvokeArgs(fn: KneFunction): String {
        val args = buildList {
            add("handle")
            fn.params.forEach { p -> add(buildJvmInvokeArg(p.name, p.type)) }
            if (fn.returnType.returnsViaBuffer()) { add("buf"); add("$STRING_BUF_SIZE") }
        }
        return args.joinToString(", ")
    }

    private fun buildClassInvokeArgsDirect(fn: KneFunction): String {
        val args = buildList {
            add("handle")
            fn.params.forEach { p -> add(buildJvmInvokeArg(p.name, p.type)) }
        }
        return args.joinToString(", ")
    }

    private fun buildTopLevelInvokeArgs(fn: KneFunction): String {
        val args = buildList {
            fn.params.forEach { p -> add(buildJvmInvokeArg(p.name, p.type)) }
            if (fn.returnType.returnsViaBuffer()) { add("buf"); add("$STRING_BUF_SIZE") }
        }
        return args.joinToString(", ")
    }

    // ── Code emission helpers ────────────────────────────────────────────────

    private fun StringBuilder.appendStringInvokeArgsAlloc(indent: String, params: List<KneParam>) {
        params.filter { it.type == KneType.STRING }.forEach { p ->
            appendLine("${indent}val ${p.name}Seg = arena.allocateFrom(${p.name})")
        }
        params.filter { it.type is KneType.NULLABLE && (it.type as KneType.NULLABLE).inner == KneType.STRING }.forEach { p ->
            appendLine("${indent}val ${p.name}Seg = if (${p.name} != null) arena.allocateFrom(${p.name}) else MemorySegment.NULL")
        }
    }

    /**
     * Emits a handle invocation with checkError() after the call.
     * For value-returning functions, stores result in a local var, checks error, then returns.
     */
    private fun StringBuilder.appendCallAndReturn(
        indent: String,
        returnType: KneType,
        handleName: String,
        invokeArgs: String,
    ) {
        when (returnType) {
            KneType.UNIT -> {
                appendLine("${indent}$handleName.invoke($invokeArgs)")
                appendLine("${indent}KneRuntime.checkError()")
            }
            KneType.STRING -> {
                appendLine("${indent}val buf = arena.allocate($STRING_BUF_SIZE.toLong())")
                appendLine("${indent}$handleName.invoke($invokeArgs)")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return buf.getString(0)")
            }
            KneType.BOOLEAN -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r != 0")
            }
            KneType.INT -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            KneType.LONG -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            KneType.DOUBLE -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Double")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            KneType.FLOAT -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Float")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            KneType.BYTE -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Byte")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            KneType.SHORT -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Short")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
            is KneType.OBJECT -> {
                appendLine("${indent}val resultHandle = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return ${returnType.simpleName}.fromNativeHandle(resultHandle)")
            }
            is KneType.ENUM -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return ${returnType.simpleName}.entries[_r]")
            }
            is KneType.NULLABLE -> appendNullableCallAndReturn(indent, returnType, handleName, invokeArgs)
        }
    }

    private fun StringBuilder.appendNullableCallAndReturn(
        indent: String,
        type: KneType.NULLABLE,
        handleName: String,
        invokeArgs: String,
    ) {
        when (type.inner) {
            KneType.STRING -> {
                appendLine("${indent}val buf = arena.allocate($STRING_BUF_SIZE.toLong())")
                appendLine("${indent}val len = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (len < 0) null else buf.getString(0)")
            }
            KneType.BOOLEAN -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw < 0) null else raw != 0")
            }
            KneType.INT -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Long.MIN_VALUE) null else raw.toInt()")
            }
            KneType.LONG -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Long.MIN_VALUE) null else raw")
            }
            KneType.SHORT -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Int.MIN_VALUE) null else raw.toShort()")
            }
            KneType.BYTE -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Int.MIN_VALUE) null else raw.toByte()")
            }
            KneType.FLOAT -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Long.MIN_VALUE) null else Float.fromBits(raw.toInt())")
            }
            KneType.DOUBLE -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw == Long.MIN_VALUE) null else Double.fromBits(raw)")
            }
            is KneType.OBJECT -> {
                appendLine("${indent}val resultHandle = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (resultHandle == 0L) null else ${type.inner.simpleName}.fromNativeHandle(resultHandle)")
            }
            is KneType.ENUM -> {
                appendLine("${indent}val raw = $handleName.invoke($invokeArgs) as Int")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return if (raw < 0) null else ${type.inner.simpleName}.entries[raw]")
            }
            KneType.UNIT -> {
                appendLine("${indent}$handleName.invoke($invokeArgs)")
                appendLine("${indent}KneRuntime.checkError()")
            }
            else -> {
                appendLine("${indent}val _r = $handleName.invoke($invokeArgs)")
                appendLine("${indent}KneRuntime.checkError()")
                appendLine("${indent}return _r")
            }
        }
    }

    private fun StringBuilder.appendSetterInvoke(indent: String, handleName: String, type: KneType, handleArg: String?) {
        val prefix = if (handleArg != null) "$handleArg, " else ""
        when (type) {
            KneType.STRING -> {
                appendLine("${indent}Arena.ofConfined().use { arena ->")
                appendLine("${indent}    val valueSeg = arena.allocateFrom(value)")
                appendLine("${indent}    $handleName.invoke(${prefix}valueSeg)")
                appendLine("${indent}    KneRuntime.checkError()")
                appendLine("${indent}}")
            }
            KneType.BOOLEAN -> {
                appendLine("${indent}$handleName.invoke(${prefix}if (value) 1 else 0)")
                appendLine("${indent}KneRuntime.checkError()")
            }
            is KneType.OBJECT -> {
                appendLine("${indent}$handleName.invoke(${prefix}value.handle)")
                appendLine("${indent}KneRuntime.checkError()")
            }
            is KneType.ENUM -> {
                appendLine("${indent}$handleName.invoke(${prefix}value.ordinal)")
                appendLine("${indent}KneRuntime.checkError()")
            }
            is KneType.NULLABLE -> appendNullableSetterInvoke(indent, handleName, type, handleArg)
            else -> {
                appendLine("${indent}$handleName.invoke(${prefix}value)")
                appendLine("${indent}KneRuntime.checkError()")
            }
        }
    }

    private fun StringBuilder.appendNullableSetterInvoke(indent: String, handleName: String, type: KneType.NULLABLE, handleArg: String?) {
        val prefix = if (handleArg != null) "$handleArg, " else ""
        when (type.inner) {
            KneType.STRING -> {
                appendLine("${indent}Arena.ofConfined().use { arena ->")
                appendLine("${indent}    val valueSeg = if (value != null) arena.allocateFrom(value) else MemorySegment.NULL")
                appendLine("${indent}    $handleName.invoke(${prefix}valueSeg)")
                appendLine("${indent}    KneRuntime.checkError()")
                appendLine("${indent}}")
            }
            else -> {
                val valueExpr = when (type.inner) {
                    KneType.BOOLEAN -> "if (value == null) -1 else if (value) 1 else 0"
                    KneType.INT -> "value?.toLong() ?: Long.MIN_VALUE"
                    KneType.LONG -> "value ?: Long.MIN_VALUE"
                    KneType.SHORT -> "value?.toInt() ?: Int.MIN_VALUE"
                    KneType.BYTE -> "value?.toInt() ?: Int.MIN_VALUE"
                    KneType.FLOAT -> "if (value != null) value.toRawBits().toLong() else Long.MIN_VALUE"
                    KneType.DOUBLE -> "if (value != null) value.toRawBits() else Long.MIN_VALUE"
                    is KneType.OBJECT -> "value?.handle ?: 0L"
                    is KneType.ENUM -> "value?.ordinal ?: -1"
                    else -> "value"
                }
                appendLine("${indent}$handleName.invoke(${prefix}$valueExpr)")
                appendLine("${indent}KneRuntime.checkError()")
            }
        }
    }
}
