package io.github.kdroidfilter.kotlinnativeexport.plugin.codegen

import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneClass
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneEnum
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneFunction
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneModule
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneParam
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneProperty
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneType

/**
 * Generates Kotlin/JVM FFM proxy code.
 *
 * Inspired by swift-java's FFMSwift2JavaGenerator:
 *  - Each exported symbol gets a descriptor class with FunctionDescriptor + MethodHandle
 *    (mirroring swift-java's inner descriptor classes per method).
 *  - Object lifecycle uses Java Cleaner + a captured Long handle
 *    (mirrors swift-java's AllocatingSwiftArena + swift_retain/swift_release pattern).
 *  - String I/O uses the output-buffer pattern (Arena.allocate + get/set ADDRESS).
 *
 * Generated classes have the exact same API as the native Kotlin classes,
 * making the bridge fully transparent to the JVM developer.
 */
class FfmProxyGenerator {

    companion object {
        private const val STRING_BUF_SIZE = 8192
    }

    /**
     * Generates all proxy files for the module.
     * Returns a map of filename → file content.
     */
    fun generate(module: KneModule, jvmPackage: String): Map<String, String> {
        val files = mutableMapOf<String, String>()

        // Shared runtime helper (one per module)
        files["KneRuntime.kt"] = generateRuntime(module.libName, jvmPackage)

        // One file per class
        module.classes.forEach { cls ->
            files["${cls.simpleName}.kt"] = generateClassProxy(cls, module, jvmPackage)
        }

        // One file per enum
        module.enums.forEach { enum ->
            files["${enum.simpleName}.kt"] = generateEnumProxy(enum, module, jvmPackage)
        }

        // Top-level functions → one object per module
        if (module.functions.isNotEmpty()) {
            val objectName = module.libName.replaceFirstChar { it.uppercaseChar() }
            files["$objectName.kt"] = generateFunctionObject(module.functions, objectName, module, jvmPackage)
        }

        return files
    }

    // ── Runtime helper ────────────────────────────────────────────────────────

    private fun generateRuntime(libName: String, pkg: String): String = buildString {
        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("import java.lang.foreign.Arena")
        appendLine("import java.lang.foreign.FunctionDescriptor")
        appendLine("import java.lang.foreign.Linker")
        appendLine("import java.lang.foreign.SymbolLookup")
        appendLine("import java.lang.invoke.MethodHandle")
        appendLine("import java.nio.file.Paths")
        appendLine()
        appendLine("/**")
        appendLine(" * Shared FFM runtime: loads the native library and resolves MethodHandles.")
        appendLine(" * Mirrors swift-java's SwiftRuntime symbol lookup pattern.")
        appendLine(" */")
        appendLine("internal object KneRuntime {")
        appendLine()
        appendLine("    val linker: Linker = Linker.nativeLinker()")
        appendLine("    private val globalArena: Arena = Arena.global()")
        appendLine()
        appendLine("    val library: SymbolLookup by lazy { loadLibrary(\"$libName\") }")
        appendLine()
        appendLine("    private fun loadLibrary(name: String): SymbolLookup {")
        appendLine("        val fileName = System.mapLibraryName(name)")
        appendLine("        val sep = if (System.getProperty(\"os.name\").lowercase().contains(\"win\")) \";\" else \":\"")
        appendLine("        val basePaths = System.getProperty(\"java.library.path\", \"\").split(sep)")
        appendLine("        // Also search next to the executable (GraalVM native-image), CWD, and lib/ subdirs")
        appendLine("        val extraDirs = mutableListOf(System.getProperty(\"user.dir\", \".\"))")
        appendLine("        try {")
        appendLine("            ProcessHandle.current().info().command().ifPresent { cmd ->")
        appendLine("                Paths.get(cmd).parent?.toString()?.let { extraDirs.add(it) }")
        appendLine("            }")
        appendLine("        } catch (_: Exception) {}")
        appendLine("        val allBases = (basePaths + extraDirs).distinct().filter { it.isNotBlank() }")
        appendLine("        val paths = allBases + allBases.map { Paths.get(it, \"lib\").toString() }")
        appendLine("        for (dir in paths) {")
        appendLine("            val file = Paths.get(dir, fileName).toFile()")
        appendLine("            if (file.exists()) return SymbolLookup.libraryLookup(file.toPath(), globalArena)")
        appendLine("        }")
        appendLine("        // Fallback: let the OS linker find it")
        appendLine("        return SymbolLookup.loaderLookup()")
        appendLine("    }")
        appendLine()
        appendLine("    fun handle(symbol: String, descriptor: FunctionDescriptor): MethodHandle =")
        appendLine("        linker.downcallHandle(")
        appendLine("            library.find(symbol).orElseThrow { UnsatisfiedLinkError(\"Symbol not found: \$symbol\") },")
        appendLine("            descriptor,")
        appendLine("        )")
        appendLine("}")
    }

    // ── Class proxy ───────────────────────────────────────────────────────────

    private fun generateClassProxy(cls: KneClass, module: KneModule, pkg: String): String = buildString {
        val p = module.libName
        val n = cls.simpleName

        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("import java.lang.foreign.Arena")
        appendLine("import java.lang.foreign.FunctionDescriptor")
        appendLine("import java.lang.foreign.ValueLayout.*")
        appendLine("import java.lang.invoke.MethodHandle")
        appendLine("import java.lang.ref.Cleaner")
        appendLine()

        appendLine("/**")
        appendLine(" * JVM proxy for Kotlin/Native class [$n].")
        appendLine(" * Uses FFM MethodHandles to dispatch every call to the native shared library.")
        appendLine(" * Object lifecycle is managed via Java Cleaner (automatic GC) or explicit close().")
        appendLine(" */")
        appendLine("class $n private constructor(internal val handle: Long) : AutoCloseable {")
        appendLine()

        // Companion: MethodHandles + factory
        appendLine("    companion object {")
        appendLine("        private val CLEANER = Cleaner.create()")
        appendLine()

        // MethodHandles — each in its own lazy val (mirrors swift-java's descriptor class per method)
        val ctorLayouts = buildLayouts(cls.constructor.params.map { it.type })
        appendLine("        private val NEW_HANDLE: MethodHandle by lazy {")
        appendLine("            KneRuntime.handle(\"${p}_${n}_new\",")
        appendLine("                FunctionDescriptor.of(JAVA_LONG$ctorLayouts))")
        appendLine("        }")
        appendLine("        private val DISPOSE_HANDLE: MethodHandle by lazy {")
        appendLine("            KneRuntime.handle(\"${p}_${n}_dispose\",")
        appendLine("                FunctionDescriptor.ofVoid(JAVA_LONG))")
        appendLine("        }")

        cls.methods.forEach { method ->
            val handleName = "${method.name.uppercase()}_HANDLE"
            val descriptor = buildMethodDescriptor(method)
            appendLine("        private val $handleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_${method.name}\",")
            appendLine("                $descriptor)")
            appendLine("        }")
        }

        cls.properties.forEach { prop ->
            val getHandleName = "GET_${prop.name.uppercase()}_HANDLE"
            val getDescriptor = buildGetterDescriptor(prop)
            appendLine("        private val $getHandleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_get_${prop.name}\",")
            appendLine("                $getDescriptor)")
            appendLine("        }")
            if (prop.mutable) {
                val setHandleName = "SET_${prop.name.uppercase()}_HANDLE"
                val setLayouts = buildLayouts(listOf(prop.type))
                appendLine("        private val $setHandleName: MethodHandle by lazy {")
                appendLine("            KneRuntime.handle(\"${p}_${n}_set_${prop.name}\",")
                appendLine("                FunctionDescriptor.ofVoid(JAVA_LONG$setLayouts))")
                appendLine("        }")
            }
        }

        // Companion method/property handles
        cls.companionMethods.forEach { method ->
            val handleName = "COMPANION_${method.name.uppercase()}_HANDLE"
            val descriptor = buildTopLevelDescriptor(method)
            appendLine("        private val $handleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_companion_${method.name}\",")
            appendLine("                $descriptor)")
            appendLine("        }")
        }
        cls.companionProperties.forEach { prop ->
            val getHandleName = "COMPANION_GET_${prop.name.uppercase()}_HANDLE"
            val getDescriptor = buildCompanionGetterDescriptor(prop)
            appendLine("        private val $getHandleName: MethodHandle by lazy {")
            appendLine("            KneRuntime.handle(\"${p}_${n}_companion_get_${prop.name}\",")
            appendLine("                $getDescriptor)")
            appendLine("        }")
            if (prop.mutable) {
                val setHandleName = "COMPANION_SET_${prop.name.uppercase()}_HANDLE"
                appendLine("        private val $setHandleName: MethodHandle by lazy {")
                appendLine("            KneRuntime.handle(\"${p}_${n}_companion_set_${prop.name}\",")
                appendLine("                FunctionDescriptor.ofVoid(${prop.type.ffmLayout}))")
                appendLine("        }")
            }
        }

        // Factory function (operator invoke = transparent construction)
        val ctorParams = cls.constructor.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }
        appendLine()
        appendLine("        /**")
        appendLine("         * Creates a new [$n] backed by a Kotlin/Native object.")
        appendLine("         * The native object is automatically released when GC'd or close() is called.")
        appendLine("         */")
        appendLine("        operator fun invoke($ctorParams): $n {")
        if (cls.constructor.params.any { it.type == KneType.STRING }) {
            appendLine("            Arena.ofConfined().use { arena ->")
            appendStringInvokeArgsAlloc("                ", cls.constructor.params)
            val ctorInvokeArgs = buildCtorInvokeArgs(cls.constructor.params)
            appendLine("                val h = NEW_HANDLE.invoke($ctorInvokeArgs) as Long")
            appendLine("                return fromNativeHandle(h)")
            appendLine("            }")
        } else {
            val ctorInvokeArgs = buildCtorInvokeArgs(cls.constructor.params)
            appendLine("            val h = NEW_HANDLE.invoke($ctorInvokeArgs) as Long")
            appendLine("            return fromNativeHandle(h)")
        }
        appendLine("        }")
        appendLine()

        // fromNativeHandle factory for wrapping handles returned by other methods
        appendLine("        internal fun fromNativeHandle(h: Long): $n {")
        appendLine("            val obj = $n(h)")
        appendLine("            CLEANER.register(obj) { runCatching { DISPOSE_HANDLE.invoke(h) } }")
        appendLine("            return obj")
        appendLine("        }")

        // Companion methods
        cls.companionMethods.forEach { method ->
            appendCompanionMethodProxy(method)
        }

        // Companion properties
        cls.companionProperties.forEach { prop ->
            appendCompanionPropertyProxy(prop)
        }

        appendLine("    }")
        appendLine()

        // Methods
        cls.methods.forEach { method -> appendMethodProxy(method, cls, p) }

        // Properties
        cls.properties.forEach { prop -> appendPropertyProxy(prop, cls) }

        // close()
        appendLine("    override fun close() {")
        appendLine("        runCatching { DISPOSE_HANDLE.invoke(handle) }")
        appendLine("    }")
        appendLine("}")
    }

    private fun StringBuilder.appendMethodProxy(fn: KneFunction, cls: KneClass, prefix: String) {
        val handleName = "${fn.name.uppercase()}_HANDLE"
        val params = fn.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }

        appendLine("    fun ${fn.name}($params): ${fn.returnType.jvmTypeName} {")

        val needsArena = fn.params.any { it.type == KneType.STRING } || fn.returnType == KneType.STRING
        if (needsArena) {
            appendLine("        Arena.ofConfined().use { arena ->")
            appendStringInvokeArgsAlloc("            ", fn.params)
            val invokeArgs = buildClassInvokeArgs(fn)
            appendCallAndReturn("            ", fn.returnType, handleName, invokeArgs)
            appendLine("        }")
        } else {
            val invokeArgs = buildClassInvokeArgsDirect(fn)
            appendCallAndReturn("        ", fn.returnType, handleName, invokeArgs)
        }

        appendLine("    }")
        appendLine()
    }

    private fun StringBuilder.appendPropertyProxy(prop: KneProperty, cls: KneClass) {
        val getHandleName = "GET_${prop.name.uppercase()}_HANDLE"
        if (prop.mutable) {
            appendLine("    var ${prop.name}: ${prop.type.jvmTypeName}")
        } else {
            appendLine("    val ${prop.name}: ${prop.type.jvmTypeName}")
        }
        appendLine("        get() {")
        val needsArena = prop.type == KneType.STRING
        if (needsArena) {
            appendLine("            Arena.ofConfined().use { arena ->")
            appendLine("                val buf = arena.allocate($STRING_BUF_SIZE.toLong())")
            appendLine("                $getHandleName.invoke(handle, buf, $STRING_BUF_SIZE)")
            appendLine("                return buf.getString(0)")
            appendLine("            }")
        } else {
            appendCallAndReturn("            ", prop.type, getHandleName, "handle")
        }
        appendLine("        }")

        if (prop.mutable) {
            val setHandleName = "SET_${prop.name.uppercase()}_HANDLE"
            appendLine("        set(value) {")
            appendSetterInvoke("            ", setHandleName, prop.type, "handle")
            appendLine("        }")
        }
        appendLine()
    }

    // ── Companion method/property proxies ─────────────────────────────────────

    private fun StringBuilder.appendCompanionMethodProxy(fn: KneFunction) {
        val handleName = "COMPANION_${fn.name.uppercase()}_HANDLE"
        val params = fn.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }

        appendLine()
        appendLine("        fun ${fn.name}($params): ${fn.returnType.jvmTypeName} {")

        val needsArena = fn.params.any { it.type == KneType.STRING } || fn.returnType == KneType.STRING
        if (needsArena) {
            appendLine("            Arena.ofConfined().use { arena ->")
            appendStringInvokeArgsAlloc("                ", fn.params)
            val invokeArgs = buildTopLevelInvokeArgs(fn)
            appendCallAndReturn("                ", fn.returnType, handleName, invokeArgs)
            appendLine("            }")
        } else {
            val invokeArgs = fn.params.joinToString(", ") { p -> buildJvmInvokeArg(p.name, p.type) }
            appendCallAndReturn("            ", fn.returnType, handleName, invokeArgs)
        }

        appendLine("        }")
    }

    private fun StringBuilder.appendCompanionPropertyProxy(prop: KneProperty) {
        val getHandleName = "COMPANION_GET_${prop.name.uppercase()}_HANDLE"
        appendLine()
        if (prop.mutable) {
            appendLine("        var ${prop.name}: ${prop.type.jvmTypeName}")
        } else {
            appendLine("        val ${prop.name}: ${prop.type.jvmTypeName}")
        }
        appendLine("            get() {")
        val needsArena = prop.type == KneType.STRING
        if (needsArena) {
            appendLine("                Arena.ofConfined().use { arena ->")
            appendLine("                    val buf = arena.allocate($STRING_BUF_SIZE.toLong())")
            appendLine("                    $getHandleName.invoke(buf, $STRING_BUF_SIZE)")
            appendLine("                    return buf.getString(0)")
            appendLine("                }")
        } else {
            appendCallAndReturn("                ", prop.type, getHandleName, "")
        }
        appendLine("            }")

        if (prop.mutable) {
            val setHandleName = "COMPANION_SET_${prop.name.uppercase()}_HANDLE"
            appendLine("            set(value) {")
            appendSetterInvoke("                ", setHandleName, prop.type, null)
            appendLine("            }")
        }
    }

    // ── Enum proxy ────────────────────────────────────────────────────────────

    private fun generateEnumProxy(enum: KneEnum, module: KneModule, pkg: String): String = buildString {
        val p = module.libName
        val n = enum.simpleName

        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("enum class $n {")
        enum.entries.forEachIndexed { idx, entry ->
            val separator = if (idx < enum.entries.size - 1) "," else ";"
            appendLine("    $entry$separator")
        }
        appendLine("}")
    }

    // ── Top-level function object ──────────────────────────────────────────────

    private fun generateFunctionObject(
        fns: List<KneFunction>,
        objectName: String,
        module: KneModule,
        pkg: String,
    ): String = buildString {
        val p = module.libName

        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("package $pkg")
        appendLine()
        appendLine("import java.lang.foreign.Arena")
        appendLine("import java.lang.foreign.FunctionDescriptor")
        appendLine("import java.lang.foreign.ValueLayout.*")
        appendLine("import java.lang.invoke.MethodHandle")
        appendLine()

        appendLine("object $objectName {")
        appendLine()

        fns.forEach { fn ->
            val handleName = "${fn.name.uppercase()}_HANDLE"
            val descriptor = buildTopLevelDescriptor(fn)
            appendLine("    private val $handleName: MethodHandle by lazy {")
            appendLine("        KneRuntime.handle(\"${p}_${fn.name}\", $descriptor)")
            appendLine("    }")
        }
        appendLine()

        fns.forEach { fn ->
            val handleName = "${fn.name.uppercase()}_HANDLE"
            val params = fn.params.joinToString(", ") { "${it.name}: ${it.type.jvmTypeName}" }
            appendLine("    fun ${fn.name}($params): ${fn.returnType.jvmTypeName} {")

            val needsArena = fn.params.any { it.type == KneType.STRING } || fn.returnType == KneType.STRING
            if (needsArena) {
                appendLine("        Arena.ofConfined().use { arena ->")
                appendStringInvokeArgsAlloc("            ", fn.params)
                val invokeArgs = buildTopLevelInvokeArgs(fn)
                appendCallAndReturn("            ", fn.returnType, handleName, invokeArgs)
                appendLine("        }")
            } else {
                val invokeArgs = fn.params.joinToString(", ") { p ->
                    buildJvmInvokeArg(p.name, p.type)
                }
                appendCallAndReturn("        ", fn.returnType, handleName, invokeArgs)
            }

            appendLine("    }")
            appendLine()
        }

        appendLine("}")
    }

    // ── Descriptor builders ───────────────────────────────────────────────────

    private fun buildMethodDescriptor(fn: KneFunction): String {
        val paramLayouts = buildList {
            add("JAVA_LONG") // handle
            fn.params.forEach { p -> add(p.type.ffmLayout) }
            if (fn.returnType == KneType.STRING) {
                add("ADDRESS") // outBuf
                add("JAVA_INT") // outLen
            }
        }
        return buildDescriptor(fn.returnType, paramLayouts)
    }

    private fun buildGetterDescriptor(prop: KneProperty): String {
        val paramLayouts = buildList {
            add("JAVA_LONG") // handle
            if (prop.type == KneType.STRING) {
                add("ADDRESS") // outBuf
                add("JAVA_INT") // outLen
            }
        }
        return buildDescriptor(prop.type, paramLayouts)
    }

    private fun buildCompanionGetterDescriptor(prop: KneProperty): String {
        val paramLayouts = buildList {
            if (prop.type == KneType.STRING) {
                add("ADDRESS") // outBuf
                add("JAVA_INT") // outLen
            }
        }
        return buildDescriptor(prop.type, paramLayouts)
    }

    private fun buildTopLevelDescriptor(fn: KneFunction): String {
        val paramLayouts = buildList {
            fn.params.forEach { p -> add(p.type.ffmLayout) }
            if (fn.returnType == KneType.STRING) {
                add("ADDRESS") // outBuf
                add("JAVA_INT") // outLen
            }
        }
        return buildDescriptor(fn.returnType, paramLayouts)
    }

    private fun buildDescriptor(returnType: KneType, paramLayouts: List<String>): String {
        val params = paramLayouts.filter { it.isNotEmpty() }.joinToString(", ")
        return if (returnType == KneType.UNIT || returnType == KneType.STRING) {
            val retLayout = if (returnType == KneType.STRING) "JAVA_INT" else ""
            if (retLayout.isEmpty()) "FunctionDescriptor.ofVoid($params)"
            else "FunctionDescriptor.of($retLayout${if (params.isNotEmpty()) ", $params" else ""})"
        } else {
            "FunctionDescriptor.of(${returnType.ffmLayout}${if (params.isNotEmpty()) ", $params" else ""})"
        }
    }

    private fun buildLayouts(types: List<KneType>): String =
        types.filter { it.ffmLayout.isNotEmpty() }.joinToString("") { ", ${it.ffmLayout}" }

    // ── Invoke arg builders ───────────────────────────────────────────────────

    /** Build the JVM invoke argument for a single parameter. */
    private fun buildJvmInvokeArg(name: String, type: KneType): String = when (type) {
        KneType.STRING -> "${name}Seg"
        KneType.BOOLEAN -> "if ($name) 1 else 0"
        is KneType.OBJECT -> "$name.handle"
        is KneType.ENUM -> "$name.ordinal"
        else -> name
    }

    private fun buildCtorInvokeArgs(params: List<KneParam>): String {
        if (params.isEmpty()) return ""
        return params.joinToString(", ") { p -> buildJvmInvokeArg(p.name, p.type) }
    }

    private fun buildClassInvokeArgs(fn: KneFunction): String {
        val args = buildList {
            add("handle")
            fn.params.forEach { p -> add(buildJvmInvokeArg(p.name, p.type)) }
            if (fn.returnType == KneType.STRING) {
                add("buf")
                add("$STRING_BUF_SIZE")
            }
        }
        return args.joinToString(", ")
    }

    private fun buildClassInvokeArgsDirect(fn: KneFunction): String {
        val args = buildList {
            add("handle")
            fn.params.forEach { p -> add(buildJvmInvokeArg(p.name, p.type)) }
        }
        return args.joinToString(", ")
    }

    private fun buildTopLevelInvokeArgs(fn: KneFunction): String {
        val args = buildList {
            fn.params.forEach { p -> add(buildJvmInvokeArg(p.name, p.type)) }
            if (fn.returnType == KneType.STRING) {
                add("buf")
                add("$STRING_BUF_SIZE")
            }
        }
        return args.joinToString(", ")
    }

    // ── Code emission helpers ─────────────────────────────────────────────────

    /**
     * Emits Arena allocations for all String parameters.
     * Each String param becomes a `val <name>Seg = arena.allocateFrom(<name>)`.
     */
    private fun StringBuilder.appendStringInvokeArgsAlloc(indent: String, params: List<KneParam>) {
        params.filter { it.type == KneType.STRING }.forEach { p ->
            appendLine("${indent}val ${p.name}Seg = arena.allocateFrom(${p.name})")
        }
    }

    /**
     * Emits a handle invocation and returns the result, including
     * string output-buffer handling when the return type is STRING.
     */
    private fun StringBuilder.appendCallAndReturn(
        indent: String,
        returnType: KneType,
        handleName: String,
        invokeArgs: String,
    ) {
        when (returnType) {
            KneType.UNIT -> appendLine("${indent}$handleName.invoke($invokeArgs)")
            KneType.STRING -> {
                appendLine("${indent}val buf = arena.allocate($STRING_BUF_SIZE.toLong())")
                appendLine("${indent}$handleName.invoke($invokeArgs)")
                appendLine("${indent}return buf.getString(0)")
            }
            KneType.BOOLEAN -> appendLine("${indent}return ($handleName.invoke($invokeArgs) as Int) != 0")
            KneType.INT -> appendLine("${indent}return $handleName.invoke($invokeArgs) as Int")
            KneType.LONG -> appendLine("${indent}return $handleName.invoke($invokeArgs) as Long")
            KneType.DOUBLE -> appendLine("${indent}return $handleName.invoke($invokeArgs) as Double")
            KneType.FLOAT -> appendLine("${indent}return $handleName.invoke($invokeArgs) as Float")
            KneType.BYTE -> appendLine("${indent}return $handleName.invoke($invokeArgs) as Byte")
            KneType.SHORT -> appendLine("${indent}return $handleName.invoke($invokeArgs) as Short")
            is KneType.OBJECT -> {
                appendLine("${indent}val resultHandle = $handleName.invoke($invokeArgs) as Long")
                appendLine("${indent}return ${returnType.simpleName}.fromNativeHandle(resultHandle)")
            }
            is KneType.ENUM -> {
                appendLine("${indent}return ${returnType.simpleName}.entries[$handleName.invoke($invokeArgs) as Int]")
            }
        }
    }

    /** Emits a setter invoke with proper type conversion. */
    private fun StringBuilder.appendSetterInvoke(indent: String, handleName: String, type: KneType, handleArg: String?) {
        val prefix = if (handleArg != null) "$handleArg, " else ""
        when (type) {
            KneType.STRING -> {
                appendLine("${indent}Arena.ofConfined().use { arena ->")
                appendLine("${indent}    val valueSeg = arena.allocateFrom(value)")
                appendLine("${indent}    $handleName.invoke(${prefix}valueSeg)")
                appendLine("${indent}}")
            }
            KneType.BOOLEAN -> appendLine("${indent}$handleName.invoke(${prefix}if (value) 1 else 0)")
            is KneType.OBJECT -> appendLine("${indent}$handleName.invoke(${prefix}value.handle)")
            is KneType.ENUM -> appendLine("${indent}$handleName.invoke(${prefix}value.ordinal)")
            else -> appendLine("${indent}$handleName.invoke(${prefix}value)")
        }
    }
}
