package io.github.kdroidfilter.kotlinnativeexport.plugin.codegen

import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneClass
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneEnum
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneFunction
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneModule
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneParam
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneProperty
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneType

/**
 * Generates Kotlin/Native bridge code using @CName + StableRef.
 *
 * Inspired by swift-java's Swift @_cdecl thunk generation (SwiftThunkTranslator).
 * Each Kotlin class/function gets a C-compatible symbol via @CName, which the
 * JVM side can call directly through FFM MethodHandles.
 *
 * Object lifecycle mirrors swift-java's approach:
 *   - Constructor → StableRef.create(obj).asCPointer().toLong()  (opaque Long handle)
 *   - Methods     → recover StableRef from handle, call method
 *   - Dispose     → StableRef.dispose()  (equivalent to Swift's swift_release)
 *
 * All bridge functions are wrapped in try/catch. Errors are stored in a
 * @ThreadLocal variable and queried by the JVM side via kne_hasError/kne_getLastError.
 */
class NativeBridgeGenerator {

    /** Whether this type uses the output-buffer pattern for returns. */
    private fun KneType.returnsViaBuffer(): Boolean =
        this == KneType.STRING || this == KneType.BYTE_ARRAY ||
        (this is KneType.NULLABLE && (inner == KneType.STRING || inner == KneType.BYTE_ARRAY))

    fun generate(module: KneModule): String = buildString {
        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("@file:Suppress(\"all\", \"NOTHING_TO_INLINE\")")
        appendLine("@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class, kotlin.experimental.ExperimentalNativeApi::class)")
        appendLine()
        appendLine("import kotlinx.cinterop.*")
        module.packages.forEach { pkg ->
            appendLine("import $pkg.*")
        }
        appendLine()

        // Thread-local error state for exception propagation
        appendLine("@kotlin.native.concurrent.ThreadLocal")
        appendLine("private var _kneLastError: String? = null")
        appendLine()

        appendErrorFunctions(module.libName)

        module.classes.forEach { cls -> appendClass(cls, module.libName) }
        module.enums.forEach { enum -> appendEnum(enum, module.libName) }
        module.functions.forEach { fn -> appendTopLevelFunction(fn, module.libName) }
    }

    // ── Error query functions ────────────────────────────────────────────────

    private fun StringBuilder.appendErrorFunctions(prefix: String) {
        appendLine("@CName(\"${prefix}_kne_hasError\")")
        appendLine("fun `${prefix}_kne_hasError`(): Int = if (_kneLastError != null) 1 else 0")
        appendLine()
        appendLine("@CName(\"${prefix}_kne_getLastError\")")
        appendLine("fun `${prefix}_kne_getLastError`(outBuf: CPointer<ByteVar>?, outLen: Int): Int {")
        appendLine("    val err = _kneLastError ?: return -1")
        appendLine("    _kneLastError = null")
        appendLine("    val bytes = err.encodeToByteArray()")
        appendLine("    val writeLen = minOf(bytes.size, outLen - 1)")
        appendLine("    bytes.forEachIndexed { i, b -> if (i < writeLen) outBuf?.set(i, b) }")
        appendLine("    outBuf?.set(writeLen, 0)")
        appendLine("    return bytes.size")
        appendLine("}")
        appendLine()
    }

    // ── Try/catch helpers ────────────────────────────────────────────────────

    private fun StringBuilder.appendTryCatchStart() {
        appendLine("    _kneLastError = null")
        appendLine("    try {")
    }

    private fun StringBuilder.appendTryCatchEnd(returnType: KneType) {
        appendLine("    } catch (e: Throwable) {")
        appendLine("        _kneLastError = e.message ?: e::class.simpleName ?: \"Unknown error\"")
        if (returnType != KneType.UNIT) {
            appendLine("        return ${defaultErrorValue(returnType)}")
        }
        appendLine("    }")
    }

    private fun defaultErrorValue(type: KneType): String = when (type) {
        KneType.INT -> "0"
        KneType.LONG -> "0L"
        KneType.DOUBLE -> "0.0"
        KneType.FLOAT -> "0.0f"
        KneType.BOOLEAN -> "0"
        KneType.BYTE -> "0"
        KneType.SHORT -> "0"
        KneType.STRING -> "0"
        KneType.UNIT -> ""
        is KneType.OBJECT -> "0L"
        is KneType.ENUM -> "0"
        is KneType.NULLABLE -> when (type.inner) {
            KneType.STRING -> "-1"
            KneType.BOOLEAN, is KneType.ENUM -> "-1"
            KneType.INT, KneType.LONG, KneType.FLOAT, KneType.DOUBLE -> "Long.MIN_VALUE"
            KneType.SHORT, KneType.BYTE -> "Int.MIN_VALUE"
            is KneType.OBJECT -> "0L"
            else -> "0"
        }
        KneType.BYTE_ARRAY -> "0"
        is KneType.FUNCTION -> "0"
        is KneType.DATA_CLASS -> ""
    }

    // ── Classes ──────────────────────────────────────────────────────────────

    private fun StringBuilder.appendClass(cls: KneClass, prefix: String) {
        val p = prefix
        val n = cls.simpleName
        val fq = cls.fqName

        // Constructor
        val ctorArgs = cls.constructor.params.joinToString(", ") { param ->
            "${param.name}: ${param.type.nativeBridgeType}"
        }
        val ctorCall = cls.constructor.params.joinToString(", ") { param ->
            buildParamConversion(param.name, param.type)
        }
        appendLine("@CName(\"${p}_${n}_new\")")
        appendLine("fun `${p}_${n}_new`($ctorArgs): Long {")
        appendTryCatchStart()
        appendLine("    return StableRef.create($fq($ctorCall)).asCPointer().toLong()")
        appendTryCatchEnd(KneType.LONG) // Long handle
        appendLine("}")
        appendLine()

        // Dispose
        appendLine("@CName(\"${p}_${n}_dispose\")")
        appendLine("fun `${p}_${n}_dispose`(handle: Long) {")
        appendTryCatchStart()
        appendLine("    handle.toCPointer<COpaque>()!!.asStableRef<$fq>().dispose()")
        appendTryCatchEnd(KneType.UNIT)
        appendLine("}")
        appendLine()

        // Methods
        cls.methods.forEach { method -> appendMethod(method, cls, p) }

        // Properties
        cls.properties.forEach { prop -> appendProperty(prop, cls, p) }

        // Companion methods
        cls.companionMethods.forEach { method -> appendCompanionMethod(method, cls, p) }

        // Companion properties
        cls.companionProperties.forEach { prop -> appendCompanionProperty(prop, cls, p) }
    }

    /** Check if a type is DATA_CLASS or NULLABLE(DATA_CLASS). */
    private fun isDataClassReturn(type: KneType): Boolean =
        type is KneType.DATA_CLASS || (type is KneType.NULLABLE && type.inner is KneType.DATA_CLASS)

    private fun extractDataClass(type: KneType): KneType.DATA_CLASS? = when (type) {
        is KneType.DATA_CLASS -> type
        is KneType.NULLABLE -> type.inner as? KneType.DATA_CLASS
        else -> null
    }

    private fun StringBuilder.appendMethod(fn: KneFunction, cls: KneClass, prefix: String) {
        val symbolName = "${prefix}_${cls.simpleName}_${fn.name}"
        val returnsViaBuffer = fn.returnType.returnsViaBuffer()
        val returnsDataClass = isDataClassReturn(fn.returnType)
        val returnDc = extractDataClass(fn.returnType)
        val returnsNullableDataClass = fn.returnType is KneType.NULLABLE && fn.returnType.inner is KneType.DATA_CLASS

        // Build param list — expand DATA_CLASS and NULLABLE(DATA_CLASS) params into flat fields
        val extraParams = if (returnsViaBuffer) ", outBuf: CPointer<ByteVar>?, outLen: Int" else ""
        val paramList = buildExpandedParamList(fn.params)
        val dcOutParams = if (returnDc != null) buildDataClassOutParams(returnDc) else ""
        val allParams = "handle: Long${if (paramList.isNotEmpty()) ", $paramList" else ""}$extraParams$dcOutParams"

        // Nullable data class returns Int (0=null, 1=present). Plain data class returns void.
        val returnDecl = when {
            returnsNullableDataClass -> ": Int"
            returnDc != null -> ""
            else -> buildReturnDecl(fn.returnType)
        }

        appendLine("@CName(\"$symbolName\")")
        appendLine("fun `$symbolName`($allParams)$returnDecl {")
        appendTryCatchStart()
        appendLine("    val obj = handle.toCPointer<COpaque>()!!.asStableRef<${cls.fqName}>().get()")
        appendObjectParamConversions(fn)
        val callArgs = fn.params.joinToString(", ") { p -> buildCallArg(p.name, p.type) }
        if (returnsNullableDataClass) {
            appendNullableDataClassReturn("obj.${fn.name}($callArgs)", returnDc!!)
        } else if (returnDc != null) {
            appendDataClassReturn("obj.${fn.name}($callArgs)", returnDc)
        } else {
            appendReturnStatement("obj.${fn.name}($callArgs)", fn.returnType)
        }
        appendTryCatchEnd(if (returnsNullableDataClass) KneType.INT else if (returnDc != null) KneType.UNIT else fn.returnType)
        appendLine("}")
        appendLine()
    }

    /** Expand params: DATA_CLASS becomes individual field params (recursive), ByteArray adds size param. */
    private fun buildExpandedParamList(params: List<KneParam>): String =
        params.flatMap { p ->
            val dc = extractDataClass(p.type)
            when {
                dc != null -> {
                    val flat = flattenDataClassFields(dc, p.name)
                    val fields = flat.map { (name, type) ->
                        when {
                            type == KneType.STRING -> "$name: CPointer<ByteVar>?"
                            type == KneType.BYTE_ARRAY -> "$name: CPointer<ByteVar>?, ${name}_size: Int"
                            else -> "$name: ${type.nativeBridgeType}"
                        }
                    }
                    if (p.type is KneType.NULLABLE) listOf("${p.name}_isNull: Int") + fields else fields
                }
                p.type == KneType.BYTE_ARRAY -> listOf("${p.name}: CPointer<ByteVar>?", "${p.name}_size: Int")
                else -> listOf("${p.name}: ${p.type.nativeBridgeType}")
            }
        }.joinToString(", ")

    /** Build out-params for DATA_CLASS return (one per field, recursive for nested data class). */
    private fun buildDataClassOutParams(dc: KneType.DATA_CLASS, prefix: String = "out"): String =
        flattenDataClassFields(dc, prefix).joinToString("") { (paramName, type) ->
            when {
                type == KneType.STRING -> ", $paramName: CPointer<ByteVar>?, ${paramName}_len: Int"
                type == KneType.BYTE_ARRAY -> ", $paramName: CPointer<ByteVar>?, ${paramName}_len: Int"
                else -> ", $paramName: CPointer<${type.nativePointerType}>?"
            }
        }

    /** Build a constructor expression from flattened params, recursively handling nested data classes. */
    private fun buildDataClassCtorExpr(dc: KneType.DATA_CLASS, prefix: String): String {
        val fieldArgs = dc.fields.joinToString(", ") { f ->
            val paramName = "${prefix}_${f.name}"
            when (f.type) {
                KneType.BOOLEAN -> "${f.name} = $paramName != 0"
                KneType.STRING -> "${f.name} = $paramName?.toKString() ?: \"\""
                is KneType.ENUM -> "${f.name} = ${f.type.fqName}.entries[$paramName]"
                is KneType.OBJECT -> "${f.name} = $paramName.toCPointer<COpaque>()!!.asStableRef<${f.type.fqName}>().get()"
                is KneType.DATA_CLASS -> "${f.name} = ${buildDataClassCtorExpr(f.type, paramName)}"
                else -> "${f.name} = $paramName"
            }
        }
        return "${dc.fqName}($fieldArgs)"
    }

    /** Flatten data class fields, expanding nested data classes with prefixed names. */
    private fun flattenDataClassFields(dc: KneType.DATA_CLASS, prefix: String): List<Pair<String, KneType>> =
        dc.fields.flatMap { f ->
            val name = "${prefix}_${f.name}"
            if (f.type is KneType.DATA_CLASS) flattenDataClassFields(f.type, name)
            else listOf(Pair(name, f.type))
        }

    /** Write data class fields to out-params (recursive for nested data classes). */
    private fun StringBuilder.appendDataClassReturn(expr: String, dc: KneType.DATA_CLASS) {
        appendLine("    val _result = $expr")
        writeDataClassFields("_result", dc, "out")
    }

    private fun StringBuilder.writeDataClassFields(objExpr: String, dc: KneType.DATA_CLASS, prefix: String) {
        dc.fields.forEach { f ->
            val outName = "${prefix}_${f.name}"
            val valueExpr = "$objExpr.${f.name}"
            when (f.type) {
                KneType.STRING -> {
                    appendLine("    val ${outName}_bytes = $valueExpr.encodeToByteArray()")
                    appendLine("    val ${outName}_writeLen = minOf(${outName}_bytes.size, ${outName}_len - 1)")
                    appendLine("    ${outName}_bytes.forEachIndexed { i, b -> if (i < ${outName}_writeLen) $outName?.set(i, b) }")
                    appendLine("    $outName?.set(${outName}_writeLen, 0)")
                }
                KneType.BOOLEAN -> appendLine("    $outName!![0] = if ($valueExpr) 1 else 0")
                is KneType.ENUM -> appendLine("    $outName!![0] = $valueExpr.ordinal")
                is KneType.OBJECT -> appendLine("    $outName!![0] = StableRef.create($valueExpr).asCPointer().toLong()")
                is KneType.DATA_CLASS -> writeDataClassFields(valueExpr, f.type, outName)
                else -> appendLine("    $outName!![0] = $valueExpr")
            }
        }
    }

    /** Write nullable data class fields to out-params. Returns 0 for null, 1 for present. */
    private fun StringBuilder.appendNullableDataClassReturn(expr: String, dc: KneType.DATA_CLASS) {
        appendLine("    val _result = $expr")
        appendLine("    if (_result == null) return 0")
        writeDataClassFields("_result", dc, "out")
        appendLine("    return 1")
    }

    private fun StringBuilder.appendProperty(prop: KneProperty, cls: KneClass, prefix: String) {
        val getterName = "${prefix}_${cls.simpleName}_get_${prop.name}"
        val extraParams = if (prop.type.returnsViaBuffer()) ", outBuf: CPointer<ByteVar>?, outLen: Int" else ""
        val returnDecl = buildReturnDecl(prop.type)

        appendLine("@CName(\"$getterName\")")
        appendLine("fun `$getterName`(handle: Long$extraParams)$returnDecl {")
        appendTryCatchStart()
        appendLine("    val obj = handle.toCPointer<COpaque>()!!.asStableRef<${cls.fqName}>().get()")
        appendReturnStatement("obj.${prop.name}", prop.type)
        appendTryCatchEnd(prop.type)
        appendLine("}")
        appendLine()

        if (prop.mutable) {
            val setterName = "${prefix}_${cls.simpleName}_set_${prop.name}"
            val valueParam = "value: ${prop.type.nativeBridgeType}"
            appendLine("@CName(\"$setterName\")")
            appendLine("fun `$setterName`(handle: Long, $valueParam) {")
            appendTryCatchStart()
            appendLine("    val obj = handle.toCPointer<COpaque>()!!.asStableRef<${cls.fqName}>().get()")
            appendSetterBody("obj.${prop.name}", prop.type)
            appendTryCatchEnd(KneType.UNIT)
            appendLine("}")
            appendLine()
        }
    }

    // ── Companion methods/properties ────────────────────────────────────────��

    private fun StringBuilder.appendCompanionMethod(fn: KneFunction, cls: KneClass, prefix: String) {
        val symbolName = "${prefix}_${cls.simpleName}_companion_${fn.name}"
        val returnsViaBuffer = fn.returnType.returnsViaBuffer()

        val extraParams = if (returnsViaBuffer) ", outBuf: CPointer<ByteVar>?, outLen: Int" else ""
        val paramList = fn.params.joinToString(", ") { "${it.name}: ${it.type.nativeBridgeType}" }
        val allParams = "$paramList$extraParams".trimStart(',', ' ')

        val returnDecl = buildReturnDecl(fn.returnType)

        appendLine("@CName(\"$symbolName\")")
        appendLine("fun `$symbolName`($allParams)$returnDecl {")
        appendTryCatchStart()
        appendObjectParamConversions(fn)
        val callArgs = fn.params.joinToString(", ") { p -> buildCallArg(p.name, p.type) }
        appendReturnStatement("${cls.fqName}.${fn.name}($callArgs)", fn.returnType)
        appendTryCatchEnd(fn.returnType)
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendCompanionProperty(prop: KneProperty, cls: KneClass, prefix: String) {
        val getterName = "${prefix}_${cls.simpleName}_companion_get_${prop.name}"
        val getterParams = if (prop.type.returnsViaBuffer()) "outBuf: CPointer<ByteVar>?, outLen: Int" else ""
        val returnDecl = buildReturnDecl(prop.type)

        appendLine("@CName(\"$getterName\")")
        appendLine("fun `$getterName`($getterParams)$returnDecl {")
        appendTryCatchStart()
        appendReturnStatement("${cls.fqName}.${prop.name}", prop.type)
        appendTryCatchEnd(prop.type)
        appendLine("}")
        appendLine()

        if (prop.mutable) {
            val setterName = "${prefix}_${cls.simpleName}_companion_set_${prop.name}"
            val valueParam = "value: ${prop.type.nativeBridgeType}"
            appendLine("@CName(\"$setterName\")")
            appendLine("fun `$setterName`($valueParam) {")
            appendTryCatchStart()
            appendSetterBody("${cls.fqName}.${prop.name}", prop.type)
            appendTryCatchEnd(KneType.UNIT)
            appendLine("}")
            appendLine()
        }
    }

    // ── Enums ────────────────────────────────────────────────────────────────

    private fun StringBuilder.appendEnum(enum: KneEnum, prefix: String) {
        val p = prefix
        val n = enum.simpleName
        val fq = enum.fqName

        appendLine("@CName(\"${p}_${n}_name\")")
        appendLine("fun `${p}_${n}_name`(ordinal: Int, outBuf: CPointer<ByteVar>?, outLen: Int): Int {")
        appendTryCatchStart()
        appendStringReturn("$fq.entries[ordinal].name")
        appendTryCatchEnd(KneType.STRING) // returns Int (byte count)
        appendLine("}")
        appendLine()

        appendLine("@CName(\"${p}_${n}_count\")")
        appendLine("fun `${p}_${n}_count`(): Int {")
        appendTryCatchStart()
        appendLine("    return $fq.entries.size")
        appendTryCatchEnd(KneType.INT)
        appendLine("}")
        appendLine()
    }

    // ── Top-level functions ──────────────────────────────────────────────────

    private fun StringBuilder.appendTopLevelFunction(fn: KneFunction, prefix: String) {
        val symbolName = "${prefix}_${fn.name}"
        val returnsViaBuffer = fn.returnType.returnsViaBuffer()
        val extraParams = if (returnsViaBuffer) ", outBuf: CPointer<ByteVar>?, outLen: Int" else ""
        val paramList = fn.params.joinToString(", ") { "${it.name}: ${it.type.nativeBridgeType}" }
        val allParams = "$paramList$extraParams"

        val returnDecl = buildReturnDecl(fn.returnType)

        appendLine("@CName(\"$symbolName\")")
        appendLine("fun `$symbolName`($allParams)$returnDecl {")
        appendTryCatchStart()
        appendObjectParamConversions(fn)
        val callArgs = fn.params.joinToString(", ") { p -> buildCallArg(p.name, p.type) }
        appendReturnStatement("${fn.name}($callArgs)", fn.returnType)
        appendTryCatchEnd(fn.returnType)
        appendLine("}")
        appendLine()
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    /** Build the return type declaration for a bridge function. */
    private fun buildReturnDecl(type: KneType): String = when {
        type.returnsViaBuffer() -> ": Int" // byte count (or -1 for null)
        type == KneType.UNIT -> ""
        type is KneType.OBJECT -> ": Long"
        type is KneType.ENUM -> ": Int"
        type is KneType.NULLABLE -> ": ${type.nativeBridgeType}"
        else -> ": ${type.nativeBridgeType}"
    }

    /** Convert a parameter value at the call site. */
    private fun buildParamConversion(paramName: String, type: KneType): String = when {
        type == KneType.BOOLEAN -> "$paramName != 0"
        type == KneType.STRING -> "$paramName?.toKString() ?: \"\""
        type == KneType.BYTE_ARRAY -> "${paramName}Arr"
        type is KneType.OBJECT -> "${paramName}Obj"
        type is KneType.ENUM -> "${type.fqName}.entries[$paramName]"
        type is KneType.FUNCTION -> "${paramName}Fn"
        type is KneType.DATA_CLASS -> "${paramName}Obj"
        type is KneType.NULLABLE && type.inner is KneType.DATA_CLASS -> "${paramName}Obj"
        type is KneType.NULLABLE -> buildNullableParamConversion(paramName, type)
        else -> paramName
    }

    private fun buildNullableParamConversion(paramName: String, type: KneType.NULLABLE): String = when (type.inner) {
        KneType.STRING -> "$paramName?.toKString()"
        KneType.BOOLEAN -> "if ($paramName >= 0) ($paramName != 0) else null"
        KneType.INT -> "if ($paramName != Long.MIN_VALUE) $paramName.toInt() else null"
        KneType.LONG -> "if ($paramName != Long.MIN_VALUE) $paramName else null"
        KneType.SHORT -> "if ($paramName != Int.MIN_VALUE) $paramName.toShort() else null"
        KneType.BYTE -> "if ($paramName != Int.MIN_VALUE) $paramName.toByte() else null"
        KneType.FLOAT -> "if ($paramName != Long.MIN_VALUE) Float.fromBits($paramName.toInt()) else null"
        KneType.DOUBLE -> "if ($paramName != Long.MIN_VALUE) Double.fromBits($paramName) else null"
        is KneType.OBJECT -> "if ($paramName != 0L) $paramName.toCPointer<COpaque>()!!.asStableRef<${type.inner.fqName}>().get() else null"
        is KneType.ENUM -> "if ($paramName >= 0) ${type.inner.fqName}.entries[$paramName] else null"
        else -> paramName
    }

    /** Build the call argument expression for a parameter. */
    private fun buildCallArg(paramName: String, type: KneType): String = when {
        type == KneType.STRING -> "${paramName}Str"
        type == KneType.BYTE_ARRAY -> "${paramName}Arr"
        type == KneType.BOOLEAN -> "$paramName != 0"
        type is KneType.OBJECT -> "${paramName}Obj"
        type is KneType.ENUM -> "${type.fqName}.entries[$paramName]"
        type is KneType.FUNCTION -> "${paramName}Fn"
        type is KneType.DATA_CLASS -> "${paramName}Obj"
        type is KneType.NULLABLE && type.inner is KneType.DATA_CLASS -> "${paramName}Obj"
        type is KneType.NULLABLE -> buildNullableCallArg(paramName, type)
        else -> paramName
    }

    private fun buildNullableCallArg(paramName: String, type: KneType.NULLABLE): String = when (type.inner) {
        KneType.STRING -> "${paramName}Str"
        is KneType.OBJECT -> "${paramName}Obj"
        KneType.BOOLEAN -> "if ($paramName >= 0) ($paramName != 0) else null"
        KneType.INT -> "if ($paramName != Long.MIN_VALUE) $paramName.toInt() else null"
        KneType.LONG -> "if ($paramName != Long.MIN_VALUE) $paramName else null"
        KneType.SHORT -> "if ($paramName != Int.MIN_VALUE) $paramName.toShort() else null"
        KneType.BYTE -> "if ($paramName != Int.MIN_VALUE) $paramName.toByte() else null"
        KneType.FLOAT -> "if ($paramName != Long.MIN_VALUE) Float.fromBits($paramName.toInt()) else null"
        KneType.DOUBLE -> "if ($paramName != Long.MIN_VALUE) Double.fromBits($paramName) else null"
        is KneType.ENUM -> "if ($paramName >= 0) ${type.inner.fqName}.entries[$paramName] else null"
        else -> paramName
    }

    /** Emit local variable conversions for String, ByteArray, Object, and Function params (including nullable variants). */
    private fun StringBuilder.appendObjectParamConversions(fn: KneFunction) {
        fn.params.filter { it.type == KneType.STRING }.forEach { p ->
            appendLine("    val ${p.name}Str = ${p.name}?.toKString() ?: \"\"")
        }
        fn.params.filter { it.type == KneType.BYTE_ARRAY }.forEach { p ->
            appendLine("    val ${p.name}Arr = ByteArray(${p.name}_size) { ${p.name}!![it] }")
        }
        fn.params.filter { it.type is KneType.OBJECT }.forEach { p ->
            val objType = p.type as KneType.OBJECT
            appendLine("    val ${p.name}Obj = ${p.name}.toCPointer<COpaque>()!!.asStableRef<${objType.fqName}>().get()")
        }
        fn.params.filter { it.type is KneType.NULLABLE && (it.type as KneType.NULLABLE).inner == KneType.STRING }.forEach { p ->
            appendLine("    val ${p.name}Str = ${p.name}?.toKString()")
        }
        fn.params.filter { it.type is KneType.NULLABLE && (it.type as KneType.NULLABLE).inner is KneType.OBJECT }.forEach { p ->
            val objType = (p.type as KneType.NULLABLE).inner as KneType.OBJECT
            appendLine("    val ${p.name}Obj = if (${p.name} != 0L) ${p.name}.toCPointer<COpaque>()!!.asStableRef<${objType.fqName}>().get() else null")
        }
        fn.params.filter { it.type is KneType.FUNCTION }.forEach { p ->
            val fnType = p.type as KneType.FUNCTION
            appendFunctionParamConversion(p.name, fnType)
        }
        // Reconstruct data classes from flattened fields (including nullable variants and nested)
        fn.params.forEach { p ->
            val dc = extractDataClass(p.type) ?: return@forEach
            val ctorExpr = buildDataClassCtorExpr(dc, p.name)
            if (p.type is KneType.NULLABLE) {
                appendLine("    val ${p.name}Obj = if (${p.name}_isNull != 0) null else $ctorExpr")
            } else {
                appendLine("    val ${p.name}Obj = $ctorExpr")
            }
        }
    }

    /** Generate a Kotlin lambda wrapper that calls through the native CFunction pointer. */
    private fun StringBuilder.appendFunctionParamConversion(paramName: String, fnType: KneType.FUNCTION) {
        // Expand DATA_CLASS params into individual fields at C ABI level
        val cFuncParams = fnType.paramTypes.flatMap { expandCFuncParamTypes(it) }.joinToString(", ")
        val cFuncReturn = cFunctionReturnType(fnType.returnType)
        val cFuncType = "CFunction<($cFuncParams) -> $cFuncReturn>"

        val lambdaParams = fnType.paramTypes.mapIndexed { i, t -> "_p$i: ${t.jvmTypeName}" }
        val lambdaParamsStr = lambdaParams.joinToString(", ")
        val hasStringInvoke = fnType.paramTypes.any {
            it == KneType.STRING || (it is KneType.DATA_CLASS && it.fields.any { f -> f.type == KneType.STRING })
        }

        appendLine("    val ${paramName}Fn: ${fnType.jvmTypeName} = { $lambdaParamsStr ->")
        if (hasStringInvoke) {
            appendLine("        memScoped {")
        }
        appendLine("        val _fnPtr = ${paramName}.toCPointer<$cFuncType>()!!")

        // Build invoke args — decompose DATA_CLASS into fields, convert enum to ordinal
        val invokeArgs = fnType.paramTypes.mapIndexed { i, t ->
            when (t) {
                KneType.BOOLEAN -> "if (_p$i) 1 else 0"
                KneType.STRING -> "_p$i.cstr.ptr"
                is KneType.ENUM -> "_p$i.ordinal"
                is KneType.DATA_CLASS -> t.fields.joinToString(", ") { f ->
                    when (f.type) {
                        KneType.BOOLEAN -> "if (_p$i.${f.name}) 1 else 0"
                        KneType.STRING -> "_p$i.${f.name}.cstr.ptr"
                        else -> "_p$i.${f.name}"
                    }
                }
                else -> "_p$i"
            }
        }.joinToString(", ")

        if (fnType.returnType == KneType.UNIT) {
            appendLine("        _fnPtr.invoke($invokeArgs)")
        } else if (fnType.returnType == KneType.BOOLEAN) {
            appendLine("        _fnPtr.invoke($invokeArgs) != 0")
        } else if (fnType.returnType == KneType.STRING) {
            appendLine("        _fnPtr.invoke($invokeArgs)?.toKString() ?: \"\"")
        } else if (fnType.returnType is KneType.ENUM) {
            appendLine("        ${fnType.returnType.fqName}.entries[_fnPtr.invoke($invokeArgs)]")
        } else if (fnType.returnType is KneType.DATA_CLASS) {
            val dc = fnType.returnType as KneType.DATA_CLASS
            appendLine("        val _retPtr = _fnPtr.invoke($invokeArgs)!!")
            var offset = 0
            val fieldArgs = dc.fields.joinToString(", ") { f ->
                val expr = when (f.type) {
                    KneType.INT -> { val r = "(_retPtr + $offset)!!.reinterpret<IntVar>().pointed.value"; offset += 4; r }
                    KneType.LONG -> { val r = "(_retPtr + $offset)!!.reinterpret<LongVar>().pointed.value"; offset += 8; r }
                    KneType.DOUBLE -> { val r = "(_retPtr + $offset)!!.reinterpret<DoubleVar>().pointed.value"; offset += 8; r }
                    KneType.FLOAT -> { val r = "(_retPtr + $offset)!!.reinterpret<FloatVar>().pointed.value"; offset += 4; r }
                    KneType.BOOLEAN -> { val r = "(_retPtr + $offset)!!.reinterpret<IntVar>().pointed.value != 0"; offset += 4; r }
                    KneType.SHORT -> { val r = "(_retPtr + $offset)!!.reinterpret<ShortVar>().pointed.value"; offset += 2; r }
                    KneType.BYTE -> { val r = "(_retPtr + $offset)!!.reinterpret<ByteVar>().pointed.value"; offset += 1; r }
                    KneType.STRING -> { val r = "(_retPtr + $offset)!!.reinterpret<CPointerVar<ByteVar>>().pointed.value?.toKString() ?: \"\""; offset += 8; r }
                    else -> { offset += 8; "0" }
                }
                "${f.name} = $expr"
            }
            appendLine("        ${dc.fqName}($fieldArgs)")
        } else {
            appendLine("        _fnPtr.invoke($invokeArgs)")
        }
        if (hasStringInvoke) {
            appendLine("        }")
        }
        appendLine("    }")
    }

    /** Expand a type into its C ABI param type(s). DATA_CLASS becomes multiple field types. */
    private fun expandCFuncParamTypes(type: KneType): List<String> = when (type) {
        is KneType.DATA_CLASS -> type.fields.map { cFunctionParamType(it.type) }
        else -> listOf(cFunctionParamType(type))
    }

    /** Map a KneType to the corresponding C-ABI type for CFunction signatures. */
    private fun cFunctionParamType(type: KneType): String = when (type) {
        KneType.INT -> "Int"
        KneType.LONG -> "Long"
        KneType.DOUBLE -> "Double"
        KneType.FLOAT -> "Float"
        KneType.BOOLEAN -> "Int" // C uses int for bool
        KneType.BYTE -> "Byte"
        KneType.SHORT -> "Short"
        KneType.STRING -> "CPointer<ByteVar>?"
        else -> "Int" // fallback
    }

    private fun cFunctionReturnType(type: KneType): String = when (type) {
        KneType.UNIT -> "Unit"
        KneType.BOOLEAN -> "Int" // C uses int for bool
        KneType.STRING -> "CPointer<ByteVar>?"
        is KneType.DATA_CLASS -> "CPointer<ByteVar>?" // pointer to struct
        else -> cFunctionParamType(type)
    }

    /** Emit the return statement for a given expression and type. */
    private fun StringBuilder.appendReturnStatement(expr: String, type: KneType) {
        when (type) {
            KneType.BYTE_ARRAY -> appendByteArrayReturn(expr)
            KneType.STRING -> appendStringReturn(expr)
            KneType.UNIT -> appendLine("    $expr")
            KneType.BOOLEAN -> appendLine("    return if ($expr) 1 else 0")
            is KneType.OBJECT -> appendLine("    return StableRef.create($expr).asCPointer().toLong()")
            is KneType.ENUM -> appendLine("    return ($expr).ordinal")
            is KneType.NULLABLE -> appendNullableReturn(expr, type)
            else -> appendLine("    return $expr")
        }
    }

    /** Emit return statement for a nullable expression. */
    private fun StringBuilder.appendNullableReturn(expr: String, type: KneType.NULLABLE) {
        appendLine("    val _result = $expr")
        when (type.inner) {
            KneType.STRING -> {
                appendLine("    if (_result == null) return -1")
                appendLine("    val bytes = _result.encodeToByteArray()")
                appendLine("    val writeLen = minOf(bytes.size, outLen - 1)")
                appendLine("    bytes.forEachIndexed { i, b -> if (i < writeLen) outBuf?.set(i, b) }")
                appendLine("    outBuf?.set(writeLen, 0)")
                appendLine("    return bytes.size")
            }
            KneType.BOOLEAN -> appendLine("    return if (_result == null) -1 else if (_result) 1 else 0")
            KneType.INT -> appendLine("    return _result?.toLong() ?: Long.MIN_VALUE")
            KneType.LONG -> appendLine("    return _result ?: Long.MIN_VALUE")
            KneType.SHORT -> appendLine("    return _result?.toInt() ?: Int.MIN_VALUE")
            KneType.BYTE -> appendLine("    return _result?.toInt() ?: Int.MIN_VALUE")
            KneType.FLOAT -> appendLine("    return _result?.toRawBits()?.toLong() ?: Long.MIN_VALUE")
            KneType.DOUBLE -> appendLine("    return _result?.toRawBits() ?: Long.MIN_VALUE")
            is KneType.OBJECT -> appendLine("    return if (_result != null) StableRef.create(_result).asCPointer().toLong() else 0L")
            is KneType.ENUM -> appendLine("    return _result?.ordinal ?: -1")
            KneType.UNIT -> appendLine("    _result")
            else -> appendLine("    return _result")
        }
    }

    /** Emit the setter body for a property assignment. */
    private fun StringBuilder.appendSetterBody(target: String, type: KneType) {
        when (type) {
            KneType.STRING -> appendLine("    $target = value?.toKString() ?: \"\"")
            KneType.BOOLEAN -> appendLine("    $target = value != 0")
            is KneType.ENUM -> appendLine("    $target = ${type.fqName}.entries[value]")
            is KneType.OBJECT -> appendLine("    $target = value.toCPointer<COpaque>()!!.asStableRef<${type.fqName}>().get()")
            is KneType.NULLABLE -> appendNullableSetterBody(target, type)
            else -> appendLine("    $target = value")
        }
    }

    private fun StringBuilder.appendNullableSetterBody(target: String, type: KneType.NULLABLE) {
        when (type.inner) {
            KneType.STRING -> appendLine("    $target = value?.toKString()")
            KneType.BOOLEAN -> appendLine("    $target = if (value >= 0) (value != 0) else null")
            KneType.INT -> appendLine("    $target = if (value != Long.MIN_VALUE) value.toInt() else null")
            KneType.LONG -> appendLine("    $target = if (value != Long.MIN_VALUE) value else null")
            KneType.SHORT -> appendLine("    $target = if (value != Int.MIN_VALUE) value.toShort() else null")
            KneType.BYTE -> appendLine("    $target = if (value != Int.MIN_VALUE) value.toByte() else null")
            KneType.FLOAT -> appendLine("    $target = if (value != Long.MIN_VALUE) Float.fromBits(value.toInt()) else null")
            KneType.DOUBLE -> appendLine("    $target = if (value != Long.MIN_VALUE) Double.fromBits(value) else null")
            is KneType.OBJECT -> appendLine("    $target = if (value != 0L) value.toCPointer<COpaque>()!!.asStableRef<${type.inner.fqName}>().get() else null")
            is KneType.ENUM -> appendLine("    $target = if (value >= 0) ${type.inner.fqName}.entries[value] else null")
            else -> appendLine("    $target = value")
        }
    }

    private fun StringBuilder.appendStringReturn(expr: String) {
        appendLine("    val result = $expr")
        appendLine("    val bytes = result.encodeToByteArray()")
        appendLine("    val writeLen = minOf(bytes.size, outLen - 1)")
        appendLine("    bytes.forEachIndexed { i, b -> if (i < writeLen) outBuf?.set(i, b) }")
        appendLine("    outBuf?.set(writeLen, 0)")
        appendLine("    return bytes.size")
    }

    private fun StringBuilder.appendByteArrayReturn(expr: String) {
        appendLine("    val result = $expr")
        appendLine("    val writeLen = minOf(result.size, outLen)")
        appendLine("    result.forEachIndexed { i, b -> if (i < writeLen) outBuf?.set(i, b) }")
        appendLine("    return result.size")
    }
}
