package io.github.kdroidfilter.kotlinnativeexport.plugin.codegen

import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneClass
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneFunction
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneModule
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneProperty
import io.github.kdroidfilter.kotlinnativeexport.plugin.ir.KneType

/**
 * Generates Kotlin/Native bridge code using @CName + StableRef.
 *
 * Inspired by swift-java's Swift @_cdecl thunk generation (SwiftThunkTranslator).
 * Each Kotlin class/function gets a C-compatible symbol via @CName, which the
 * JVM side can call directly through FFM MethodHandles.
 *
 * Object lifecycle mirrors swift-java's approach:
 *   - Constructor → StableRef.create(obj).asCPointer().toLong()  (opaque Long handle)
 *   - Methods     → recover StableRef from handle, call method
 *   - Dispose     → StableRef.dispose()  (equivalent to Swift's swift_release)
 */
class NativeBridgeGenerator {

    fun generate(module: KneModule): String = buildString {
        appendLine("// Auto-generated by kotlin-native-export plugin. Do not modify.")
        appendLine("@file:Suppress(\"all\", \"NOTHING_TO_INLINE\")")
        appendLine("@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class, kotlin.experimental.ExperimentalNativeApi::class)")
        appendLine()
        appendLine("import kotlinx.cinterop.*")
        module.packages.forEach { pkg ->
            appendLine("import $pkg.*")
        }
        appendLine()

        module.classes.forEach { cls -> appendClass(cls, module.libName) }
        module.functions.forEach { fn -> appendTopLevelFunction(fn, module.libName) }
    }

    // ── Classes ──────────────────────────────────────────────────────────────

    private fun StringBuilder.appendClass(cls: KneClass, prefix: String) {
        val p = prefix
        val n = cls.simpleName
        val fq = cls.fqName

        // Constructor
        val ctorArgs = cls.constructor.params.joinToString(", ") { param ->
            "${param.name}: ${param.type.nativeBridgeType}"
        }
        val ctorCall = cls.constructor.params.joinToString(", ") { param ->
            when (param.type) {
                KneType.BOOLEAN -> "${param.name} != 0"
                KneType.STRING -> "${param.name}?.toKString() ?: \"\""
                else -> param.name
            }
        }
        appendLine("@CName(\"${p}_${n}_new\")")
        appendLine("fun `${p}_${n}_new`($ctorArgs): Long =")
        appendLine("    StableRef.create($fq($ctorCall)).asCPointer().toLong()")
        appendLine()

        // Dispose — equivalent to swift_release in swift-java
        appendLine("@CName(\"${p}_${n}_dispose\")")
        appendLine("fun `${p}_${n}_dispose`(handle: Long) =")
        appendLine("    handle.toCPointer<COpaque>()!!.asStableRef<$fq>().dispose()")
        appendLine()

        // Methods
        cls.methods.forEach { method -> appendMethod(method, cls, p) }

        // Properties — generate getter (and setter if mutable)
        cls.properties.forEach { prop -> appendProperty(prop, cls, p) }
    }

    private fun StringBuilder.appendMethod(fn: KneFunction, cls: KneClass, prefix: String) {
        val symbolName = "${prefix}_${cls.simpleName}_${fn.name}"
        val hasStringParam = fn.params.any { it.type == KneType.STRING }
        val returnsString = fn.returnType == KneType.STRING

        // Build C-level parameter list
        val extraParams = if (returnsString) ", outBuf: CPointer<ByteVar>?, outLen: Int" else ""
        val paramList = fn.params.joinToString(", ") { "${it.name}: ${it.type.nativeBridgeType}" }
        val allParams = "handle: Long${if (paramList.isNotEmpty()) ", $paramList" else ""}$extraParams"

        val returnDecl = when {
            returnsString -> ": Int"
            fn.returnType == KneType.UNIT -> ""
            else -> ": ${fn.returnType.nativeBridgeType}"
        }

        appendLine("@CName(\"$symbolName\")")
        appendLine("fun `$symbolName`($allParams)$returnDecl {")
        appendLine("    val obj = handle.toCPointer<COpaque>()!!.asStableRef<${cls.fqName}>().get()")

        // Convert String params
        fn.params.filter { it.type == KneType.STRING }.forEach { p ->
            appendLine("    val ${p.name}Str = ${p.name}?.toKString() ?: \"\"")
        }

        val callArgs = fn.params.joinToString(", ") { p ->
            when (p.type) {
                KneType.STRING -> "${p.name}Str"
                KneType.BOOLEAN -> "${p.name} != 0"
                else -> p.name
            }
        }

        when {
            returnsString -> appendStringReturn("obj.${fn.name}($callArgs)")
            fn.returnType == KneType.UNIT -> appendLine("    obj.${fn.name}($callArgs)")
            fn.returnType == KneType.BOOLEAN ->
                appendLine("    return if (obj.${fn.name}($callArgs)) 1 else 0")
            else -> appendLine("    return obj.${fn.name}($callArgs)")
        }

        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendProperty(prop: KneProperty, cls: KneClass, prefix: String) {
        val getterName = "${prefix}_${cls.simpleName}_get_${prop.name}"
        val extraParams = if (prop.type == KneType.STRING) ", outBuf: CPointer<ByteVar>?, outLen: Int" else ""
        val returnDecl = when {
            prop.type == KneType.STRING -> ": Int"
            prop.type == KneType.UNIT -> ""
            else -> ": ${prop.type.nativeBridgeType}"
        }

        appendLine("@CName(\"$getterName\")")
        appendLine("fun `$getterName`(handle: Long$extraParams)$returnDecl {")
        appendLine("    val obj = handle.toCPointer<COpaque>()!!.asStableRef<${cls.fqName}>().get()")
        when {
            prop.type == KneType.STRING -> appendStringReturn("obj.${prop.name}")
            prop.type == KneType.BOOLEAN -> appendLine("    return if (obj.${prop.name}) 1 else 0")
            else -> appendLine("    return obj.${prop.name}")
        }
        appendLine("}")
        appendLine()

        if (prop.mutable) {
            val setterName = "${prefix}_${cls.simpleName}_set_${prop.name}"
            val valueParam = "value: ${prop.type.nativeBridgeType}"
            appendLine("@CName(\"$setterName\")")
            appendLine("fun `$setterName`(handle: Long, $valueParam) {")
            appendLine("    val obj = handle.toCPointer<COpaque>()!!.asStableRef<${cls.fqName}>().get()")
            when (prop.type) {
                KneType.STRING -> appendLine("    obj.${prop.name} = value?.toKString() ?: \"\"")
                KneType.BOOLEAN -> appendLine("    obj.${prop.name} = value != 0")
                else -> appendLine("    obj.${prop.name} = value")
            }
            appendLine("}")
            appendLine()
        }
    }

    // ── Top-level functions ───────────────────────────────────────────────────

    private fun StringBuilder.appendTopLevelFunction(fn: KneFunction, prefix: String) {
        val symbolName = "${prefix}_${fn.name}"
        val returnsString = fn.returnType == KneType.STRING
        val extraParams = if (returnsString) ", outBuf: CPointer<ByteVar>?, outLen: Int" else ""
        val paramList = fn.params.joinToString(", ") { "${it.name}: ${it.type.nativeBridgeType}" }
        val allParams = "$paramList$extraParams"

        val returnDecl = when {
            returnsString -> ": Int"
            fn.returnType == KneType.UNIT -> ""
            else -> ": ${fn.returnType.nativeBridgeType}"
        }

        appendLine("@CName(\"$symbolName\")")
        appendLine("fun `$symbolName`($allParams)$returnDecl {")

        fn.params.filter { it.type == KneType.STRING }.forEach { p ->
            appendLine("    val ${p.name}Str = ${p.name}?.toKString() ?: \"\"")
        }

        val callArgs = fn.params.joinToString(", ") { p ->
            when (p.type) {
                KneType.STRING -> "${p.name}Str"
                KneType.BOOLEAN -> "${p.name} != 0"
                else -> p.name
            }
        }

        when {
            returnsString -> appendStringReturn("${fn.name}($callArgs)")
            fn.returnType == KneType.UNIT -> appendLine("    ${fn.name}($callArgs)")
            fn.returnType == KneType.BOOLEAN ->
                appendLine("    return if (${fn.name}($callArgs)) 1 else 0")
            else -> appendLine("    return ${fn.name}($callArgs)")
        }

        appendLine("}")
        appendLine()
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Appends code to write a Kotlin String result to an output buffer.
     * The output-buffer pattern avoids any native heap allocation:
     * the JVM allocates the buffer via Arena, the native side fills it.
     */
    private fun StringBuilder.appendStringReturn(expr: String) {
        appendLine("    val result = $expr")
        appendLine("    val bytes = result.encodeToByteArray()")
        appendLine("    val writeLen = minOf(bytes.size, outLen - 1)")
        appendLine("    bytes.forEachIndexed { i, b -> if (i < writeLen) outBuf?.set(i, b) }")
        appendLine("    outBuf?.set(writeLen, 0)")
        appendLine("    return bytes.size")
    }
}
